### ISSUE TITLE
读取binlog写入kafka配置断点续传功能没有生效

### ISSUE THREAD

**Issue by liumengkai** [DTStack/chunjun#1010]
我在参考了下面两个连接之后设置chunjun的断点续传功能，但是checkpoint没有生效
```
https://dtstack.github.io/chunjun-web/docs/chunjunDocs/restore/
https://www.yuque.com/alipaypokwr69ggn/czbhl8/rnrhgg
```

系统:
macos 12.0.1

flink version:1.12.7

chunjun:v1.12.5

详细信息：

1.配置conf/flink-conf.yaml，增加下面两个配置：
state.checkpoints.dir: hdfs://localhost:9000/checkpoint checkPoint的地址
state.checkpoints.num-retained: 10      checkPoint保存个数

2.在配置中确认添加:
"restore": {
          "isRestore": true,
          "restoreColumnName": "table",
          "restoreColumnIndes": 2
        }
3.提交任务命令行增加checkpoint时间间隔设置
```
bin/start-chunjun \
    -mode yarn-per-job \
    -jobType sync \
    -job /Users/liu/Documents/my_flinkx/chunjun/json/test.json \
    -chunjunDistDir $CHUNJUN_HOME  \
    -hadoopConfDir $HADOOP_HOME/etc/hadoop \
    -flinkLibDir $FLINK_HOME/lib \
    -confProp "{\"flink.checkpoint.interval\":10000}"
```

现象：

1.flink任务提交成功，但是checkpoints tab页面显示没有信息
2.task manager 中的log显示已经读取到了checkpoint相关配置，但是kafkaproducer的checkpoint 是not enable 的

![image](https://user-images.githubusercontent.com/31892927/176088984-a86a2093-a666-4d30-958b-123fa9b09d53.png)

![image](https://user-images.githubusercontent.com/31892927/176094875-a3e1068d-45a9-4eec-9cd3-bea2f885461d.png)

![image](https://user-images.githubusercontent.com/31892927/176095294-329eb71e-c1bf-4d56-9a98-1418308ea50d.png)

问题：
checkpoint没有生效是因为kafkaproducer没有开启checkpoint嘛？应该如何开启呢？

**Comment by liumengkai** [comment]
@libailin sorry to bother you again :-)
I read that doc and still something is wrong,can you give some advises?

**Comment by liumengkai** [comment]
change 'flink.checkpoint.interval' to 'execution.checkpointing.interval' after flink1.10

**Comment by J1aHe** [comment]
看看json
