### ISSUE TITLE
restore配置

### ISSUE THREAD

**Issue by star10k** [DTStack/chunjun#1015]
大哥们,是这么配置的吧。没做其他操作和配置了。帮我看看,如何看效果呢  我感觉没生效时的
"restore": {
        "isResore": true,
        "restoreColumnName": "id",
        "restoreColumnIndex": 0
}
参考的官方文档： https://dtstack.github.io/chunjun-web/docs/chunjunDocs/restore
没生效：
... update startLocation, before = null, after = 0  
... AND `id` >= 0 AND `id` < 13449646

**Comment by liumengkai** [comment]
@star10k 
This question is family with mine #1010
I think chunjun doc didn't say enough for this context,this context need to be rich by someone has already done with it :-)

**Comment by star10k** [comment]
> @star10k This question is similar with mine #1010 I think chunjun doc didn't say enough for this context,this context need to be rich by someone has already done with it :-)
Thanks,You said very nice , I hope you can help me solve this problem .  Because the recovery scheme  is so important.   You are a big cow and you are a great man  .
