### ISSUE TITLE
kafkareader指定timestamp消费无效

### ISSUE THREAD

**Issue by IsisPolei** [DTStack/chunjun#1018]
任务json如下：
{
  "job": {
    "content": [
      {
        "reader": {
          "parameter": {
            "topic": "xxx",
            "mode": "timestamp",
            "timestamp": 1656620100000,
            "codec": "json",
            "column": [
              {
                "name": "user_id",
                "type": "int"
              },
              {
                "name": "score",
                "type": "double"
              },
              {
                "name": "business",
                "type": "string"
              },
              {
                "name": "p_day",
                "type": "string"
              },
              {
                "name": "p_type",
                "type": "string"
              }
            ],
            "consumerSettings": {
              "bootstrap.servers": "xxx",
              "auto.commit.enable": "false"
            }
          },
          "name": "kafkareader"
        },
        "writer": {
          "name": "hdfswriter",
          "parameter": {
            "path": "hdfs://xxx",
            "defaultFS": "hdfs://xxx",
            "column": [
              {
                "name": "user_id",
                "type": "int"
              },
              {
                "name": "score",
                "type": "double"
              },
              {
                "name": "business",
                "type": "string"
              },
              {
                "name": "p_day",
                "type": "string"
              },
              {
                "name": "p_type",
                "type": "string"
              }
            ],
            "fileType": "text",
            "maxFileSize": 1073741824,
            "nextCheckRows": 5000,
            "fieldDelimiter": ",",
            "encoding": "utf-8",
            "fileName": "2",
            "writeMode": "overwrite",
            "hadoopConfig": {
             ...
            }
          }
        }
      }
    ],
    "setting": {
      "restore": {
        "isRestore": true,
        "isStream": true
      },
      "speed": {
        "readerChannel": 1,
        "writerChannel": 1
      }
    }
  }
}
实际消费时控制台信息如下：
![image](https://user-images.githubusercontent.com/41672192/176873572-7a399a09-b418-4f9b-a9e9-928041330eb9.png)
![image](https://user-images.githubusercontent.com/41672192/176873637-22e42328-acc2-4087-aac5-b6879fd27ee6.png)

实际消费到的数据并不是从指定的timestamp  1656620100000开始

**Comment by IsisPolei** [comment]
chunjun version：master

**Comment by yanghuaiGit** [comment]
![image](https://user-images.githubusercontent.com/38883656/182793783-02cd6cac-a949-4329-b4a4-152675302be3.png)

this log  show your start timestamp rathen than your screenshots

**Comment by yanghuaiGit** [comment]
i used chunjun master，it is ok
