### ISSUE TITLE
1.11版本 hdfs->mysql flink web ui 无日志

### ISSUE THREAD

**Issue by mztt-elfine** [DTStack/chunjun#1027]
<img width="1128" alt="1657100444" src="https://user-images.githubusercontent.com/42823423/177521452-c5080025-20be-4e76-94d8-22477f01d54f.png">

**Comment by FlechazoW** [comment]
你好，能否f12查看下这个页面的信息呢？另外，你这个是1.11_release版本吗？

**Comment by mztt-elfine** [comment]
是的1.11_release版本的，json见附件，日志没做过改动，请大佬看看
















在 2022-07-15 17:40:24，"tiezhu" ***@***.***> 写道：

你好，能否f12查看下这个页面的信息呢？另外，你这个是1.11_release版本吗？

**Comment by ll076110** [comment]
You may need to locate whether your YARN log file path has changed

**Comment by ChestnutQiang** [comment]
export FLINK_CONF_DIR=$FLINK_HOME/conf
export FLINK_OPT_DIR=$FLINK_HOME/opt
export FLINK_LIB_DIR=$FLINK_HOME/lib

把 flink 的环境变量配置好，应该就可以解决。

**Comment by mztt-elfine** [comment]
jar包冲突 hive里的log4j 和flinkx里的冲突导致
