### ISSUE TITLE
[Question][Core] How to configure the name-mapping?

### ISSUE THREAD

**Issue by FlechazoW** [DTStack/chunjun#1036]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [X] I had googled my question but i didn't get any help.

- [X] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

## 问题描述

当第一次启动作业时，会解析JSON内容， 获取BinlogConf 与 JdbcConf， 此时是可以获取到clickhouse connection的。

![image](https://user-images.githubusercontent.com/35768015/178126148-f3c650c0-4814-4aba-b95c-f74034de0784.png)

![image](https://user-images.githubusercontent.com/35768015/178126154-f0a05606-3ea8-4741-8a90-a6614e497efc.png)

![image](https://user-images.githubusercontent.com/35768015/178126159-cde20996-644d-44e3-8167-fce6c32841f1.png)

当尝试第一次在mysql表中添加新的一条数据记录时，会提示 table adc.white_list not found.
跟踪源码时，发现获取表元数据的时候，显示dbConn为clickhouse的实例连接，但是schmea却是获取到binlog数据变化时的schma信息。所以导致在clickhous中表未发现。

## 解决方案
目前在clickhouse中新建与mysql中相同的库表名称。解决该问题。 

其它方案：也许可以通过namemapping来完成与RowData的映射。 但是没摸索清楚namemapping该如何来写。  后面在研究。 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ll076110** [comment]
Take mysql database mysqltest and table c_test as an example. Write clickhouse database test and table one as an example.
"nameMapping": {
          "schemaMappings": {
            "mysqltest": "test"
          },
          "tableMappings": {
            "mysqltest": {
              "c_test": "one"
            }
          },
          "fieldMappings": {
            "mysqltest": {
              "c_test": {
                "id": "id",
                "username": "name"
              }
            }
          }
        }
