### ISSUE TITLE
chunjun1.12版本——执行MYSQL-DM时，任务一直处于执行状态(所提供日志最后一行)，但是DM到其他库是没有问题

### ISSUE THREAD

**Issue by biandou1313** [DTStack/chunjun#1041]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

[JdbcConf]: 
{
  "semantic" : "at-least-once",
  "errorRecord" : 0,
  "checkFormat" : true,
  "parallelism" : 1,
  "pollingInterval" : 5000,
  "increment" : false,
  "flushIntervalMills" : 10000,
  "polling" : false,
  "mode" : "INSERT",
  "password" : "******",
  "metricPluginRoot" : "null\\metrics",
  "restoreColumnIndex" : -1,
  "connection" : [ {
    "table" : [ "GHZ" ],
    "jdbcUrl" : "jdbc:dm://172.18.8.113:5236/mysqlreader",
    "allReplace" : false
  } ],
  "table" : "GHZ",
  "queryTimeOut" : 0,
  "fetchSize" : 0,
  "useMaxFunc" : false,
  "column" : [ {
    "name" : "ID",
    "type" : "INT",
    "index" : 0,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "NAME",
    "type" : "VARCHAR",
    "index" : 1,
    "notNull" : false,
    "part" : false
  } ],
  "errorPercentage" : -1,
  "fieldNameList" : [ "ID", "NAME" ],
  "withNoLock" : false,
  "increColumnIndex" : -1,
  "allReplace" : false,
  "splitStrategy" : "range",
  "jdbcUrl" : "jdbc:dm://172.18.8.113:5236/mysqlreader",
  "batchSize" : 1024,
  "speedBytes" : 0,
  "metricPluginName" : "prometheus",
  "properties" : {
    "password" : "******",
    "user" : "SYSDBA"
  },
  "username" : "SYSDBA"
} 
2022-07-12 12:00:11,980 - 6271 INFO  [Source: mysqlsourcefactory -> Sink: dmsinkfactory (1/1)#0] com.dtstack.flinkx.source.DtInputFormatSourceFunction:Start initialize input format state, is restored:false
2022-07-12 12:00:11,984 - 6275 INFO  [Source: mysqlsourcefactory -> Sink: dmsinkfactory (1/1)#0] com.dtstack.flinkx.source.DtInputFormatSourceFunction:End initialize input format state
2022-07-12 12:00:11,987 - 6278 WARN  [flink-akka.actor.default-dispatcher-4] org.apache.flink.runtime.taskmanager.TaskManagerLocation:No hostname could be resolved for the IP address 127.0.0.1, using IP address as host name. Local input split assignment (such as for HDFS files) may be impacted.
Tue Jul 12 12:00:12 CST 2022 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2022-07-12 12:00:12,251 - 6542 INFO  [Legacy Source Thread - Source: mysqlsourcefactory -> Sink: dmsinkfactory (1/1)#0] com.dtstack.flinkx.connector.jdbc.source.JdbcInputFormat:Executing sql is: 'SELECT `id`, `name` FROM `ghz` WHERE  1=1 '
2022-07-12 12:00:12,258 - 6549 INFO  [Legacy Source Thread - Source: mysqlsourcefactory -> Sink: dmsinkfactory (1/1)#0] com.dtstack.flinkx.source.format.BaseRichInputFormat:[JdbcInputFormat] open successfully, 
inputSplit = JdbcInputSplit{mod=0, endLocation='null', startLocation='null', startLocationOfSplit='null', endLocationOfSplit='null'}, 
[JdbcConf]: 
{
  "semantic" : "at-least-once",
  "errorRecord" : 0,
  "checkFormat" : true,
  "parallelism" : 1,
  "pollingInterval" : 5000,
  "increment" : false,
  "flushIntervalMills" : 10000,
  "polling" : false,
  "querySql" : "SELECT `id`, `name` FROM `ghz` WHERE  1=1 ",
  "mode" : "INSERT",
  "password" : "******",
  "metricPluginRoot" : "null\\metrics",
  "restoreColumnIndex" : -1,
  "connection" : [ {
    "table" : [ "ghz" ],
    "jdbcUrl" : [ "jdbc:mysql://172.18.8.113:3306/test_fjf" ]
  } ],
  "table" : "ghz",
  "queryTimeOut" : 300,
  "fetchSize" : -2147483648,
  "useMaxFunc" : false,
  "column" : [ {
    "name" : "id",
    "type" : "INT",
    "index" : 0,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "name",
    "type" : "VARCHAR",
    "index" : 1,
    "notNull" : false,
    "part" : false
  } ],
  "errorPercentage" : -1,
  "fieldNameList" : [ ],
  "withNoLock" : false,
  "increColumnIndex" : -1,
  "allReplace" : false,
  "splitStrategy" : "range",
  "jdbcUrl" : "jdbc:mysql://172.18.8.113:3306/test_fjf",
  "batchSize" : 1,
  "speedBytes" : 0,
  "metricPluginName" : "prometheus",
  "properties" : {
    "password" : "******",
    "user" : "root"
  },
  "username" : "root"
} 
2022-07-12 12:00:22,509 - 16800 INFO  [Legacy Source Thread - Source: mysqlsourcefactory -> Sink: dmsinkfactory (1/1)#0] com.dtstack.flinkx.source.format.BaseRichInputFormat:subtask input close finished

### What you expected to happen

可以执行完成

### How to reproduce

[JdbcConf]: 
{
  "semantic" : "at-least-once",
  "errorRecord" : 0,
  "checkFormat" : true,
  "parallelism" : 1,
  "pollingInterval" : 5000,
  "increment" : false,
  "flushIntervalMills" : 10000,
  "polling" : false,
  "mode" : "INSERT",
  "password" : "******",
  "metricPluginRoot" : "null\\metrics",
  "restoreColumnIndex" : -1,
  "connection" : [ {
    "table" : [ "GHZ" ],
    "jdbcUrl" : "jdbc:dm://172.18.8.113:5236/mysqlreader",
    "allReplace" : false
  } ],
  "table" : "GHZ",
  "queryTimeOut" : 0,
  "fetchSize" : 0,
  "useMaxFunc" : false,
  "column" : [ {
    "name" : "ID",
    "type" : "INT",
    "index" : 0,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "NAME",
    "type" : "VARCHAR",
    "index" : 1,
    "notNull" : false,
    "part" : false
  } ],
  "errorPercentage" : -1,
  "fieldNameList" : [ "ID", "NAME" ],
  "withNoLock" : false,
  "increColumnIndex" : -1,
  "allReplace" : false,
  "splitStrategy" : "range",
  "jdbcUrl" : "jdbc:dm://172.18.8.113:5236/mysqlreader",
  "batchSize" : 1024,
  "speedBytes" : 0,
  "metricPluginName" : "prometheus",
  "properties" : {
    "password" : "******",
    "user" : "SYSDBA"
  },
  "username" : "SYSDBA"
} 
2022-07-12 12:00:11,980 - 6271 INFO  [Source: mysqlsourcefactory -> Sink: dmsinkfactory (1/1)#0] com.dtstack.flinkx.source.DtInputFormatSourceFunction:Start initialize input format state, is restored:false
2022-07-12 12:00:11,984 - 6275 INFO  [Source: mysqlsourcefactory -> Sink: dmsinkfactory (1/1)#0] com.dtstack.flinkx.source.DtInputFormatSourceFunction:End initialize input format state
2022-07-12 12:00:11,987 - 6278 WARN  [flink-akka.actor.default-dispatcher-4] org.apache.flink.runtime.taskmanager.TaskManagerLocation:No hostname could be resolved for the IP address 127.0.0.1, using IP address as host name. Local input split assignment (such as for HDFS files) may be impacted.
Tue Jul 12 12:00:12 CST 2022 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2022-07-12 12:00:12,251 - 6542 INFO  [Legacy Source Thread - Source: mysqlsourcefactory -> Sink: dmsinkfactory (1/1)#0] com.dtstack.flinkx.connector.jdbc.source.JdbcInputFormat:Executing sql is: 'SELECT `id`, `name` FROM `ghz` WHERE  1=1 '
2022-07-12 12:00:12,258 - 6549 INFO  [Legacy Source Thread - Source: mysqlsourcefactory -> Sink: dmsinkfactory (1/1)#0] com.dtstack.flinkx.source.format.BaseRichInputFormat:[JdbcInputFormat] open successfully, 
inputSplit = JdbcInputSplit{mod=0, endLocation='null', startLocation='null', startLocationOfSplit='null', endLocationOfSplit='null'}, 
[JdbcConf]: 
{
  "semantic" : "at-least-once",
  "errorRecord" : 0,
  "checkFormat" : true,
  "parallelism" : 1,
  "pollingInterval" : 5000,
  "increment" : false,
  "flushIntervalMills" : 10000,
  "polling" : false,
  "querySql" : "SELECT `id`, `name` FROM `ghz` WHERE  1=1 ",
  "mode" : "INSERT",
  "password" : "******",
  "metricPluginRoot" : "null\\metrics",
  "restoreColumnIndex" : -1,
  "connection" : [ {
    "table" : [ "ghz" ],
    "jdbcUrl" : [ "jdbc:mysql://172.18.8.113:3306/test_fjf" ]
  } ],
  "table" : "ghz",
  "queryTimeOut" : 300,
  "fetchSize" : -2147483648,
  "useMaxFunc" : false,
  "column" : [ {
    "name" : "id",
    "type" : "INT",
    "index" : 0,
    "notNull" : false,
    "part" : false
  }, {
    "name" : "name",
    "type" : "VARCHAR",
    "index" : 1,
    "notNull" : false,
    "part" : false
  } ],
  "errorPercentage" : -1,
  "fieldNameList" : [ ],
  "withNoLock" : false,
  "increColumnIndex" : -1,
  "allReplace" : false,
  "splitStrategy" : "range",
  "jdbcUrl" : "jdbc:mysql://172.18.8.113:3306/test_fjf",
  "batchSize" : 1,
  "speedBytes" : 0,
  "metricPluginName" : "prometheus",
  "properties" : {
    "password" : "******",
    "user" : "root"
  },
  "username" : "root"
} 
2022-07-12 12:00:22,509 - 16800 INFO  [Legacy Source Thread - Source: mysqlsourcefactory -> Sink: dmsinkfactory (1/1)#0] com.dtstack.flinkx.source.format.BaseRichInputFormat:subtask input close finished

### Anything else

a

### Version

1.12_release

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by biandou1313** [comment]
![image](https://user-images.githubusercontent.com/34857750/178437171-f7e4117e-9840-4b25-9d1f-93576a21c481.png)
![1657612017](https://user-images.githubusercontent.com/34857750/178437324-c72751a4-ee7f-49fa-9c02-b36f6429e05e.png)
![1657612062(1)](https://user-images.githubusercontent.com/34857750/178437476-cb502b65-2249-4169-bb7b-ac0e4a6eae54.png)

**Comment by FlechazoW** [comment]
我看任务已经close了，为什么还会是一直处于执行状态呢？

**Comment by biandou1313** [comment]
我也是奇怪 仍无其实已经关闭 但是主程序还在运行



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Paddy ***@***.***&gt;; 
发送时间: 2022年7月12日(星期二) 下午3:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DTStack/chunjun] chunjun1.12版本——执行MYSQL-DM时，任务一直处于执行状态(所提供日志最后一行)，但是DM到其他库是没有问题 (Issue #1041)





 
我看任务已经close了，为什么还会是一直处于执行状态呢？

**Comment by FlechazoW** [comment]
“主程序还在运行” 是指？

**Comment by biandou1313** [comment]
测试：
  // 定义 DM JDBC 驱动串
        String jdbcString = "dm.jdbc.driver.DmDriver";
        // 定义 DM URL 连接串
        String urlString = "jdbc:dm://172.18.8.113:5236/SYSDBA";
        // 定义连接用户名
        String userName = "SYSDBA";
        // 定义连接用户口令
        String password = "SYSDBA";
        // 定义连接对象
        Connection conn = null;
        Class.forName(jdbcString);
        conn = DriverManager.getConnection(urlString, userName, password);
        String sql = "INSERT INTO GHZ(ID,NAME)" + "VALUES(?,?);";

        String sql2="MERGE INTO \"GHZ\" T1 USING (SELECT ? ID, ? NAME FROM DUAL) T2 ON (T1.\"ID\" = T2.\"ID\")  WHEN MATCHED THEN UPDATE SET \"T1\".\"NAME\" =NVL(\"T2\".\"NAME\",\"T1\".\"NAME\") WHEN NOT MATCHED THEN INSERT (\"ID\", \"NAME\") VALUES (T2.\"ID\", T2.\"NAME\")";
        conn.setAutoCommit(false);
        PreparedStatement  prest = conn.prepareStatement(sql);
        for (int i = 20; i <= 25; i++) {
            prest.setInt(1, i);
            prest.setString(2, "wuhandameng");
            prest.addBatch();
        }
        prest.executeBatch();
        conn.commit();

        prest.close();
        conn.close();

**Comment by biandou1313** [comment]
public static void main(String[] args) throws ClassNotFoundException, SQLException {
        // 定义 DM JDBC 驱动串
        String jdbcString = "dm.jdbc.driver.DmDriver";
        // 定义 DM URL 连接串
        String urlString = "jdbc:dm://172.18.8.113:5236/SYSDBA";
        // 定义连接用户名
        String userName = "SYSDBA";
        // 定义连接用户口令
        String password = "SYSDBA";
        // 定义连接对象
        Connection conn = null;
        Class.forName(jdbcString);
        conn = DriverManager.getConnection(urlString, userName, password);
        String sql = "INSERT INTO GHZ(ID,NAME)" + "VALUES(?,?);";

        String sql2="MERGE INTO \"GHZ\" T1 USING (SELECT ? ID, ? NAME FROM DUAL) T2 ON (T1.\"ID\" = T2.\"ID\")  WHEN MATCHED THEN UPDATE SET \"T1\".\"NAME\" =NVL(\"T2\".\"NAME\",\"T1\".\"NAME\") WHEN NOT MATCHED THEN INSERT (\"ID\", \"NAME\") VALUES (T2.\"ID\", T2.\"NAME\")";
//        conn.setAutoCommit(false);
        PreparedStatement  prest = conn.prepareStatement(sql);
        for (int i = 20; i <= 25; i++) {
            prest.setInt(1, i);
            prest.setString(2, "wuhandameng");
            prest.addBatch();
        }
        prest.executeBatch();
        conn.commit();

        prest.close();
        conn.close();
    }

**Comment by biandou1313** [comment]
按照你们提供的驱动，我写了一个测试用例，执行批量操作，语句也是同步oracle-dm 的 ，我拿出来单独执行，也是运行卡死状态
![1657673676(1)](https://user-images.githubusercontent.com/34857750/178625437-fc239fc2-0092-410a-bb71-6cb8723709c3.png)

**Comment by FlechazoW** [comment]
我是否可以理解为，你的分析结论是：程序卡死在executeBatch() 这个方法里？

**Comment by chaozwn** [comment]
@biandou1313 我测试了一下，功能是正常的，不知道是不是你配置上的问题，可以参考我的配置

{
  "job": {
    "content": [
      {
        "reader": {
          "name": "mysqlreader",
          "parameter": {
            "column": [
              {
                "name": "ID",
                "type": "int"
              },
              {
                "name": "NAME",
                "type": "string"
              }
            ],
            "username": "root",
            "password": "123456",
            "connection": [
              {
                "jdbcUrl": [
                  "jdbc:mysql://localhost:40057/test?useSSL=false"
                ],
                "table": [
                  "Test1"
                ]
              }
            ]
          }
        },
        "writer": {
          "name": "dmwriter",
          "parameter": {
            "username": "SYSDBA",
            "password": "SYSDBA",
            "connection": [
              {
                "jdbcUrl": "jdbc:dm://127.0.0.1:45236",
                "schema": "TEST",
                "table": [
                  "GHZ"
                ]
              }
            ],
            "writeMode": "insert",
            "column": [
              {
                "name": "ID",
                "type": "int"
              },
              {
                "name": "NAME",
                "type": "string"
              }
            ]
          }
        }
      }
    ],
    "setting": {
      "speed": {
        "channel": 1,
        "bytes": 0
      }
    }
  }
}

**Comment by FlechazoW** [comment]
长时间未收到回复，如果仍然存在问题，可重新打开此issue
