### ISSUE TITLE
[Bug] [bin] failed to start chunjun job in local mode if FLINK_HOME and HADOOP_HOME ware not set.

### ISSUE THREAD

**Issue by lvyanquan** [DTStack/chunjun#1043]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

I tried to submit a chunjun job in local mode, since I had not hadoop environment,
FLINK_HOME and HADOOP_HOME ware not set and remained empty.

### What you expected to happen

submit job successfully

### How to reproduce

submit job in local mode using script of CHUNJUN_HOME/bin/chunjun-local.sh, do not set environment config of FLINK_HOME and HADOOP_HOME 

### Version

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
PR merged.
