### ISSUE TITLE
[Clickhouse] Transactions are not supported  && JdbcOutputFormat  open() failed

### ISSUE THREAD

**Issue by berg-xu** [DTStack/chunjun#1048]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

问题背景：
基于Flink SQL模式执行作业，获取mysql binlog数据sink到clickhouse中。执行的作业sql内容脚本如下：

CREATE TABLE source
(
     id          bigint
    ,item        VARCHAR
) WITH (
      'connector' = 'binlog-x'
      ,'url' = 'jdbc:mysql://127.0.0.1:3306/adc?useSSL=false'
      ,'host' = '127.0.0.1'
      ,'port' = '3306'
      ,'username' = 'root'
      ,'password' = 'root'
      ,'table' = 'adc.white_list'
      ,'cat' = 'insert,delete,update'
      -- ,'timestamp' = '1656644111000'
      ,'connection-charset' = 'UTF-8'
      ,'buffer-size' = '1024'
      ,'parallel' = 'true'
      ,'parallel-thread-size' = '2'
      ,'is-gtid-mode' = 'false'
      ,'query-time-out' = '300000'
      ,'connect-time-out' = '60000'
      ,'timestamp-format.standard' = 'SQL'
      );

CREATE TABLE sink (
   id BIGINT
  ,item String
  ,PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'connector' = 'clickhouse-x'
   ,'url' = 'jdbc:clickhouse://127.0.0.1:7205/adc'
   ,'schema' = 'adc'
   ,'table-name' = 'white_list'
   ,'username' = 'root'
   ,'password' = 'root'
   ,'sink.buffer-flush.max-rows' = '1024'
   ,'sink.buffer-flush.interval' = '10000'
   ,'sink.all-replace' = 'true'
   ,'sink.semantic' = 'exactly-once' --'at-least-once'
   ,'sink.parallelism' = '1'
);

insert into sink
select *
from source u

问题如下：
![image](https://user-images.githubusercontent.com/45385723/178913988-89e896c0-3a12-4366-9178-10c6e0f4bf18.png)

原因是当 'sink.semantic' = 'exactly-once' 时，

![image](https://user-images.githubusercontent.com/45385723/178914489-33d7fe8f-3ba2-4909-bb61-86cec557f38d.png)

![image](https://user-images.githubusercontent.com/45385723/178914618-a0f90ade-05a4-4b4b-92f0-f0315888b1dc.png)

目前解决方案是替换 'sink.semantic'的值'exactly-once' 为 'at-least-once'. 

![image](https://user-images.githubusercontent.com/45385723/178915030-ff33cd90-614f-458b-b6ab-b7dbd3947dfe.png)

请问有什么更好的方案没？ 该如何来做？

### What you expected to happen

无

### How to reproduce

无

### Version

1.12_release

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
因为clickhouse 驱动不支持手动提交事务，所以clickhouse sink 不支持 exactly-once，只能是 at-least-once
