### ISSUE TITLE
[Clickhouse] [JdbcOutputFormat] No value present

### ISSUE THREAD

**Issue by berg-xu** [DTStack/chunjun#1049]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

问题背景：
基于Flink SQL模式执行作业，获取mysql binlog数据sink到clickhouse中。执行的作业sql内容脚本如下：

CREATE TABLE source
(
id bigint
,item VARCHAR
) WITH (
'connector' = 'binlog-x'
,'url' = 'jdbc:mysql://127.0.0.1:3306/adc?useSSL=false'
,'host' = '127.0.0.1'
,'port' = '3306'
,'username' = 'root'
,'password' = 'root'
,'table' = 'adc.white_list'
,'cat' = 'insert,delete,update'
-- ,'timestamp' = '1656644111000'
,'connection-charset' = 'UTF-8'
,'buffer-size' = '1024'
,'parallel' = 'true'
,'parallel-thread-size' = '2'
,'is-gtid-mode' = 'false'
,'query-time-out' = '300000'
,'connect-time-out' = '60000'
,'timestamp-format.standard' = 'SQL'
);

CREATE TABLE sink (
id BIGINT
,item String
,PRIMARY KEY (id) NOT ENFORCED
) WITH (
'connector' = 'clickhouse-x'
,'url' = 'jdbc:clickhouse://127.0.0.1:7205/adc'
,'schema' = 'adc'
,'table-name' = 'white_list'
,'username' = 'root'
,'password' = 'root'
,'sink.buffer-flush.max-rows' = '1024'
,'sink.buffer-flush.interval' = '10000'
,'sink.all-replace' = 'true'
,'sink.semantic' = 'at-least-once'
,'sink.parallelism' = '1'
);

insert into sink
select *
from source u

问题如下：

![image](https://user-images.githubusercontent.com/45385723/178915695-c67253e1-179a-4a08-9a68-d8d6018a8186.png)

原因是：

Mode是从JdbcConf中获取， jdbcconf内容如下：
JdbcConf{fullColumn=null, insertSqlMode='null', fieldDelim='null', nullDelim='null', withNoLock=false, properties=null, username='root', password='root', connection=[SinkConnectionConf{table=[white_list], schema='adc', username='null', password='null', jdbcUrl='jdbc:clickhouse://127.0.0.1:7205/adc', allReplace=true}], where='null', customSql='null', orderByColumn='null', querySql='null', splitPk='null', splitStrategy='null', fetchSize=0, queryTimeOut=0, connectTimeOut=0, increment=false, polling=false, increColumn='null', increColumnIndex=-1, increColumnType='null', startLocation='null', pollingInterval=5000, restoreColumn='null', restoreColumnType='null', restoreColumnIndex=-1, useMaxFunc=false, **mode='UPDATE',** preSql=null, postSql=null, uniqueKey=[id], updateKey=null, allReplace=true}

当然， 我并不明白这里的mode=UPDATE是如何判定获取？

然后根据MODE=UPDATE， 执行getUpsertStatement(）方法，

![image](https://user-images.githubusercontent.com/45385723/178916332-136aabd9-a124-41c0-8e36-7faa7dbf49e7.png)

因为ClickhouseDialect中并未实现getUpsertStatement方法，导致返回空。

![image](https://user-images.githubusercontent.com/45385723/178917106-3d409a42-1b2f-44c5-88d0-aeb9ca189210.png)

解决方案：
目前查看了clickhouse相关文档， 不支持upsert语法。 因此针对upsert操作仅仅是直接调用insert操作来避免修该错误。
clickouse 中的upsert语法具体该如何来实现了？ 求指导。 

另外， 每次遇到源端mysql数据执行DML更新操作时，  都会获取缓存的操作key，获取DynamicPreparedStmt。 DynamicPreparedStmt这个该如何理解？ 求指导指导。

![image](https://user-images.githubusercontent.com/45385723/178918020-cec0ec19-b5ab-4beb-8d82-723916b2f12c.png)

### What you expected to happen

无

### How to reproduce

无

### Version

1.12_release

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
sql 模式下，mode == update 的判断依据是create table sql 定义中定义了primary key即为update mode。

**Comment by waryars** [comment]
clickhouse的MergeTree引擎是支持update\delete操作的
