### ISSUE TITLE
http请求get方法的参数怎么写？返回结果还需要xml解析，怎么写sql语句？

### ISSUE THREAD

**Issue by 15656215623** [DTStack/chunjun#1051]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [ ] I had googled my question but i didn't get any help.

- [ ] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

http请求 地址是  http://ip:8082/ERPService.asmx/GetItemInOutSpec?ComCode=102&HCode=nn12

![image](https://user-images.githubusercontent.com/49744386/179133538-68e662f2-c23d-4b06-b4ee-8105fd525b7a.png)
1、这个后面跟的参数，是写在body里面吗？
2、返回的结果需要xml解析，我改怎么写呢？

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 15656215623** [comment]
@FlechazoW

**Comment by ll076110** [comment]
parameters can be written in "params".
parsing XML is not currently supported

**Comment by 15656215623** [comment]
好的，知道了
