### ISSUE TITLE
怎么更新mysql表里的数据啊？  更新部分字段，其他字段都不用动的（表里面有很多字段都不用动的）。

### ISSUE THREAD

**Issue by 15656215623** [DTStack/chunjun#1055]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [ ] I had googled my question but i didn't get any help.

- [ ] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

需求
1、我需要更新mysql表里面的2个字段weight和meter；其他的很多字段不需要动的
2、我的head_code和F_Id是唯一的
![image](https://user-images.githubusercontent.com/49744386/179185584-b89725a5-c1d9-483a-9728-2ab50874962c.png)
 请问我改怎么写？

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 15656215623** [comment]
好的。我有一个疑问，redis查找是 tablename_id_name    非要这种的？如果是tablename_name 没有id行不行？
我感觉redis的查找的命名比较麻烦。

**Comment by FlechazoW** [comment]
由于redis的特殊性，它本身是没有表的概念，所以为了能在维表关联上有条件查询，只能在key 上做条件查询，如果是tablename_name 没有id的情况，在join on 条件里，就不能用id作为join key。

**Comment by 15656215623** [comment]
你是一个兢兢业业的开发者，有耐心，有热情，谦逊，
