### ISSUE TITLE
flinksql嵌套的if else语句怎么写啊？ 

### ISSUE THREAD

**Issue by 15656215623** [DTStack/chunjun#1057]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [ ] I had googled my question but i didn't get any help.

- [ ] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

我需要实现以下的需求，但是不知道怎么写？
if(ssxr<10){
.......处理程序
}else{
.....处理程序
if(inner==0&&outneer==0){
...处理程序
}else{
..处理程序
}
}
这里的ssxr  inner   outnner都是从source表或者维表获取的数据，这种嵌套的if else 怎么写啊？求教！！！！
无所不能的chunjun社区

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
Use 'case when'.

**Comment by 15656215623** [comment]
我用了case when 比较复杂的嵌套用法，但是一直报错
我的代码如下
-- 源表 
CREATE TABLE source1 (
    id varchar,
    inners float,
    outs float,
    spec float,
    --机头号
    SSXR float,
    -- 线速度
    VSXZL float,
    --长度
    CWW float
) WITH(
    'connector' = 'emqx-x',
    'broker' = 'tcp://10.20.1.16:1883',
    'topic' = 'zt',
    'isCleanSession' = 'true',
    'qos' = '0',
    'username' = 'admin',
    'password' = 'public',
    'format' = 'json'
);
--结果表
-- 源表 
CREATE TABLE sink1 (
    id varchar,
    inners float,
    outs float,
    spec float,
    --机头号
    SSXR float,
    -- 线速度
    VSXZL float,
    --长度
    CWW float
) WITH(
    'connector' = 'emqx-x',
    'broker' = 'tcp://10.20.1.16:1883',
    'topic' = 'zt1',
    'isCleanSession' = 'true',
    'qos' = '0',
    'username' = 'admin',
    'password' = 'public',
    'format' = 'json'
);
--case when嵌套
insert into sink1 
select 
 id,
 case when SSXR<10 then cww=0
      else 
        case when inners=0 and outs=0 then cww=ABS(6*spec*VSXZL)
             else cww=(1*outs*outs+2*inners*inners)*VSXZL
             end 
      end as cww
inners,
outs,
spec,
SSXR,
VSXZL
 from source1




错误信息如下
![image](https://user-images.githubusercontent.com/49744386/179434334-b04eba0c-a4f2-4430-a62c-579544ec94ef.png)

**Comment by 15656215623** [comment]
我现在改了很多部分，然后我发现，case when这一部分的值是boolean类型，原本是float类型，为什么会这样呢？
-- 源表 
CREATE TABLE source1 (
    id varchar,
    i_meter float,
    outs float,
    spec float,
    --机头号
    SSXR float,
    -- 线速度
    VSXZL float,
    --长度
    CWW float
) WITH(
    'connector' = 'emqx-x',
    'broker' = 'tcp://10.20.1.16:1883',
    'topic' = 'zt',
    'isCleanSession' = 'true',
    'qos' = '0',
    'username' = 'admin',
    'password' = 'public',
    'format' = 'json'
);
--结果表
-- 源表 
CREATE TABLE sink1 (
    id varchar,
    i_meter float,
    outs float,
    spec float,
    --机头号
    SSXR float,
    -- 线速度
    VSXZL float,
    --长度
    CWW float
) WITH(
    'connector' = 'emqx-x',
    'broker' = 'tcp://10.20.1.16:1883',
    'topic' = 'zt1',
    'isCleanSession' = 'true',
    'qos' = '0',
    'username' = 'admin',
    'password' = 'public',
    'format' = 'json'
);
--case when嵌套
insert into sink1 
select 
 id,
 case when SSXR<10 then CWW=0
      else 
        case when i_meter=0 and outs=0 then CWW=ABS(6*spec*VSXZL)
             else CWW=(1*outs*outs+2*i_meter*i_meter)*VSXZL
             end 
      end as CWW,
i_meter,
outs,
spec,
SSXR,
VSXZL
 from source1


![image](https://user-images.githubusercontent.com/49744386/179436091-8410bdf3-5afe-4a19-8b0e-190f75b54968.png)

**Comment by 15656215623** [comment]
已经解决了！
1、第一个错误是没有加,
2、第二个错误是 不够清晰的了解case when的用法
    case when 条件 then 结果（不是赋值表达式，是一个计算表达式或单独的结果就可以了）

附上我正确的代码
-- 源表 
CREATE TABLE source1 (
    id varchar,
    i_meter float,
    outs float,
    spec float,
    --机头号
    SSXR float,
    -- 线速度
    VSXZL float,
    --长度
    CWW float
) WITH(
    'connector' = 'emqx-x',
    'broker' = 'tcp://10.20.1.16:1883',
    'topic' = 'zt',
    'isCleanSession' = 'true',
    'qos' = '0',
    'username' = 'admin',
    'password' = 'public',
    'format' = 'json'
);
--结果表
-- 源表 
CREATE TABLE sink1 (
    id varchar,
    i_meter float,
    outs float,
    spec float,
    --机头号
    SSXR float,
    -- 线速度
    VSXZL float,
    --长度
    CWW float
) WITH(
    'connector' = 'emqx-x',
    'broker' = 'tcp://10.20.1.16:1883',
    'topic' = 'zt1',
    'isCleanSession' = 'true',
    'qos' = '0',
    'username' = 'admin',
    'password' = 'public',
    'format' = 'json'
);
--case when嵌套
insert into sink1 
select 
 id,
 case when SSXR<10 then 0
      else 
        (
        case when i_meter=0 and outs=0 then ABS(6*spec*VSXZL)
        else ((1*outs*outs+2*i_meter*i_meter)*VSXZL)
        end 
        )
      end as CWW,
i_meter,
outs,
spec,
SSXR,
VSXZL
 from source1


正确的截图

source数据
![image](https://user-images.githubusercontent.com/49744386/179438478-03fc8d4f-d669-4c62-8478-284d57204500.png)

sink接受的数据
![image](https://user-images.githubusercontent.com/49744386/179438468-a798faa3-d421-41e7-a218-a179638852d9.png)
