### ISSUE TITLE
怎么实现 相同的计算处理流程，但是emqx主题不一样？大概有100个这样流程的主题，难道要搞100多个的.sql文件？

### ISSUE THREAD

**Issue by 15656215623** [DTStack/chunjun#1069]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [ ] I had googled my question but i didn't get any help.

- [ ] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

1、emqx的主题不同 但是名称和id相关  topic=amqp_id

-- 源表 
CREATE TABLE source1 (
    id varchar,
    com_code int,
    head_code varchar,
    --机头号
    SSXR float,
    -- 线速度
    VSXZL float,
    --长度
    CWW float,
    --重量
    PROCTIME AS PROCTIME()
) WITH(
    'connector' = 'emqx-x',
    'broker' = 'tcp://192.168.123.29:1883',
    'topic' = 'amq/topic',
    'isCleanSession' = 'true',
    'qos' = '0',
    'username' = 'OPC_102',
    'password' = 'Opc_2020',
    'format' = 'json'
);

2、处理的流程一模一样
3、我写好一个流程，类似的主题有100多个，难道我要搞100个sql文件，然后一个个修改里面的主题，然后部署吗？
4、我该怎么处理呢？求指点

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
不知道emqx支不支持正则匹配topic，如果不支持，那么大概率需要配置这么多任务。

**Comment by FlechazoW** [comment]
长时间未收到回复，如果仍然存在问题，可重新打开此issue
