### ISSUE TITLE
flinksql 如何定时执行任务？

### ISSUE THREAD

**Issue by 15656215623** [DTStack/chunjun#1070]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [ ] I had googled my question but i didn't get any help.

- [ ] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

需求
    每天晚上10点，执行一次job流程
    百度了很多，他们要求从linux下手。。。。

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
用Taier，Taier 可以定时调度任务。
