### ISSUE TITLE
http插件的get请求  不管怎么写，提交以后都是Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by 15656215623** [DTStack/chunjun#1074]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [ ] I had googled my question but i didn't get any help.

- [ ] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

http请求的get模式，我不管怎么写 都会报错，报错的信息是Caused by: java.lang.NullPointerException
flinksql语句代码如下
-- CREATE TABLE source
-- (
--     Spec  varchar,
--      InR  varchar,
--       obj.  varchar
-- ) WITH (
--       'connector' = 'http-x'
--       ,'url' = 'http://192.168.1.153:8082/ERPService.asmx/GetItemInOutSpec2'
--       ,'intervalTime'= '3000'
--        ,'method'='get'
--        ,'decode'= 'json'
--        ,'header'='[
--         {
--                 "key": "Cookie",
--                 "value": ""
--               },
--         {
--                 "key": "Content-Type",
--                 "value": "text/plain;charset=UTF-8"
--               }
--             ]'
--        --,'params'='[]'
--        ,'params'='[
--         { 
--           "key":"ComCode",
--           "value":102,
--           "type": "int"
--         },
--          {  
--         "key":"HCode",
--           "value":"nn12",
--           "type":"String"
--         }
--        ]'
--       );
CREATE TABLE source
(
    Spec  varchar,
     InR  varchar,
        OutR  varchar
) WITH (
      'connector' = 'http-x'
      ,'url' = 'http://192.168.1.63:1880/dudu'
      ,'intervalTime'= '3000'
       ,'method'='get'
       ,'decode'= 'json'
       ,'header'='[
        {
                "key": "Cookie",
                "value": ""
              },
        {
                "key": "Content-Type",
                "value": "text/json;charset=UTF-8"
              }
            ]'
       ,'params'='[
        { 
          "key":"ComCode",
          "value":102,
          "type": "int"
        },
         {  
        "key":"HCode",
          "value":"nn12",
          "type":"String"
        }
       ]'
      );

CREATE TABLE sink1 (
    Spec  varchar,
     InR  varchar,
      OutR  varchar
) WITH(
    'connector' = 'emqx-x',
    'broker' = 'tcp://10.20.1.16:1883',
    'topic' = 'zt1',
    'isCleanSession' = 'true',
    'qos' = '0',
    'username' = 'admin',
    'password' = 'public',
    'format' = 'json'
);
insert into sink1 select Spec,InR,OutR from source;

报错信息如下
![image](https://user-images.githubusercontent.com/49744386/179649267-a19da1b1-c76f-4d59-b757-da6c677c3655.png)

页面返回的结果如下
![image](https://user-images.githubusercontent.com/49744386/179649323-ba0b1266-1f8b-4949-9373-63c9ec703bbf.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 15656215623** [comment]
@FlechazoW

**Comment by 15656215623** [comment]
现在问题已经解决了！简直就是痛苦与折磨，可怕极了！！！
一、空指针异常
空指针异常是因为
![image](https://user-images.githubusercontent.com/49744386/180393532-2e2d5c60-b9fe-4186-a80a-480b3f44f1f6.png)
需要做的改变如下
![image](https://user-images.githubusercontent.com/49744386/180393698-751d7a67-594f-412e-b4c4-e1c1d402c89e.png)

然后编译打包以后，还是会报错
![lQLPJxaE2DTFvCTNA13NBqOwTivRIJ-23IAC2rgEu8CWAA_1699_861](https://user-images.githubusercontent.com/49744386/180394011-6eca06e8-f24b-4363-9625-58cc5da15d99.png)

顺便说一下，这个打包会很慢大约十几分钟，然后chunjun-dist有800M多，建议只需要打包子项目，提交子项目就可以了，要学会思考，有脑子！

二、类冲突
![image](https://user-images.githubusercontent.com/49744386/180394373-de72ea46-bf12-4c87-abae-b5ca7358a8c1.png)
为什么别人一看就知道是类冲突呢？

![image](https://user-images.githubusercontent.com/49744386/180395959-8709009c-5a69-46ae-b9f8-a0822cc3667a.png)
ClassNotFoundException这个是有类，但是不行，或许跟版本有关系等
NoClassDefFoundError是找不到这个类

![image](https://user-images.githubusercontent.com/49744386/180396270-784cafaa-7ab6-41b4-b4b8-04ffc25ef363.png)

![image](https://user-images.githubusercontent.com/49744386/180396526-19a7da9e-3e19-4d14-83d0-8a2305455b1c.png)

到这里可以了!

贴上我的成功截图

CREATE TABLE source
(
OutR  varchar
) WITH (
      'connector' = 'http-x'
      ,'url' = 'http://192.168.122.113:1880/dudu'
      ,'intervalTime'= '3000'
       ,'method'='get'
       ,'decode'= 'json'
        ,'params'= '[
         {  
          "key":"ComCode",
          "value":"112",
          "type":"String"
        }
       ]'
      );

CREATE TABLE sink1 (
      OutR  varchar
) WITH(
    'connector' = 'emqx-x',
    'broker' = 'tcp://10.20.1.16:1883',
    'topic' = 'zt1',
    'isCleanSession' = 'true',
    'qos' = '0',
    'username' = 'admin',
    'password' = 'public',
    'format' = 'json'
);
insert into sink1 
select 
*
 from source;

![image](https://user-images.githubusercontent.com/49744386/180396705-3cc1cf6b-a28e-4a8f-8393-d5d9ef281c84.png)

![image](https://user-images.githubusercontent.com/49744386/180396733-82fe8227-cd05-490d-96f5-f2127abe2015.png)

**Comment by FlechazoW** [comment]
优秀，可以提交给pr了。

**Comment by 15656215623** [comment]
总结一下
 1、一开始我打算本地跑代码，然后debug 但是一直运行有问题；因此很长时间觉得是代码的不规范，有问题等，没有想到底层的问题，一开始方向就有问题；
2、空指针异常这个解决办法，还是chunjun的渡劫说的，本来不信的，觉得鬼扯，别人都成功了，为什么我这里有问题；
后来实在是没有办法了，才这样
3、然后发现又报httpclient的问题，以为是缺少jar包，发现不是的；怎么搞都不对！
4、后来实在想不到原因了，群里有人说是jar包冲突，我当时觉得牛头不对马嘴，太鬼扯了
5、后来发现本地模式跑没有任何问题。这个时候才觉得群里说的有道理了
6、根据渡劫的回答，我指定了http-client的版本，然后重新编译，才成功了

怎么说呢？  还是要本地可以调试。不然问题出在哪里都不知道！！！！
其次，自己基础处理问题的能力不行，NoClassFoundException和ClassNoFoundExceptionError完全是两个错误。但是自己从来没有注意过，还以为是缺jar包呢！！！！
方向完全不对！！！欸

这次能搞出来，完全是在大家的帮助下搞出来的，不然根本不可能搞出来，自己的思维与所有的都风牛马不及！！
惭愧
