### ISSUE TITLE
About parameter  channel，readerChannel writerChannel  need same

### ISSUE THREAD

**Issue by CrazyFz** [DTStack/chunjun#1082]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [ ] I had googled my question but i didn't get any help.

- [ ] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

version
flink ：1.12.7
flinkX:  1.12.7
flink start with the cluster
when I user parameter like     
  "speed": {
        "channel": 1,
        "readerChannel": 1,
        "writerChannel": 1,
        "bytes": 0
      }
the job can success
But when I user parameter like     
  "speed": {
        "channel": 1,
        "readerChannel": 1,
        "writerChannel": 2,
        "bytes": 0
      }
the job is fail
![image](https://user-images.githubusercontent.com/22133156/180253572-82598f3c-3954-4f7b-b722-8ddb6bbbe61d.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
Can you provide a complete script of the task?

**Comment by CrazyFz** [comment]
问题产生来自于Fflink集群部署的时候没有设置好多通道参数，此参数在flink-conf.yaml中taskmanager.numberOfTaskSlots，如果这里设置不够大，就只开启的通道不能超过这个数，否则就会报错
