### ISSUE TITLE
mysql->mysql同步任务启动报错，找不到源表：Caused by: com.dtstack.chunjun.throwable.ChunJunRuntimeException: table td_user_source not found.

### ISSUE THREAD

**Issue by Flamelay** [DTStack/chunjun#1083]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

（虚拟机上启动chunjun执行Windows下mysql数据库的同步任务报错如下）

> 2022-07-21 19:10:06.000 [flink-akka.actor.default-dispatcher-8] INFO  org.apache.flink.runtime.blob.BlobServer  - Stopped BLOB server at 0.0.0
> 2022-07-21 19:10:06.000 [flink-akka.actor.default-dispatcher-8] INFO  org.apache.flink.runtime.rpc.akka.AkkaRpcService  - Stopped Akka RPC ser
> Exception in thread "main" org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
>         at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:144)
>         at org.apache.flink.runtime.minicluster.MiniCluster.executeJobBlocking(MiniCluster.java:811)
>         at com.dtstack.chunjun.environment.MyLocalStreamEnvironment.execute(MyLocalStreamEnvironment.java:174)
>         at com.dtstack.chunjun.Main.exeSyncJob(Main.java:227)
>         at com.dtstack.chunjun.Main.main(Main.java:122)
>         at com.dtstack.chunjun.client.local.LocalClusterClientHelper.submit(LocalClusterClientHelper.java:35)
>         at com.dtstack.chunjun.client.Launcher.main(Launcher.java:119)
> Caused by: org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
>         at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:118)
>         at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.jav
>         at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:233)
>         at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:224)
>         at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:215)
>         at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:666)
>         at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:89)
>         at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:446)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:305)
>         at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:212)
>         at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:77)
>         at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:158)
>         at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)
>         at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)
>         at scala.PartialFunction.applyOrElse(PartialFunction.scala:123)
>         at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122)
>         at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)
>         at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
>         at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
>         at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
>         at akka.actor.Actor.aroundReceive(Actor.scala:517)
>         at akka.actor.Actor.aroundReceive$(Actor.scala:515)
>         at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225)
>         at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
>         at akka.actor.ActorCell.invoke(ActorCell.scala:561)
>         at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
>         at akka.dispatch.Mailbox.run(Mailbox.scala:225)
>         at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
>         at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
>         at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
>         at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
>         at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
> Caused by: com.dtstack.chunjun.throwable.ChunJunRuntimeException: table td_user_source not found.
>
>  at com.dtstack.chunjun.connector.jdbc.util.JdbcUtil.getTableMetaData(JdbcUtil.java:143)
>         at com.dtstack.chunjun.connector.mysql.source.MysqlInputFormat.getTableMetaData(MysqlInputFormat.java:36)
>         at com.dtstack.chunjun.connector.jdbc.source.JdbcInputFormat.openInternal(JdbcInputFormat.java:124)
>         at com.dtstack.chunjun.source.format.BaseRichInputFormat.open(BaseRichInputFormat.java:161)
>         at com.dtstack.chunjun.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:126)
>         at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
>         at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)
>         at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:267)

JSON：

{
  "job": {
    "content": [
      {
        "reader": {
          "name": "mysqlreader",
          "parameter": {
            "column": [
              {
                "name": "id",
                "type": "int"
              },
              {
                "name": "name",
                "type": "string"
              },
              {
                "name": "phone",
                "type": "string"
              }
            ],
            "username": "xxxx",
            "password": "xxxx",
            "connection": [
              {
                "jdbcUrl": [
                  "jdbc:mysql://x.x.x.x:3306/source?useSSL=false"
                ],
                "table": [
                  "td_user_source"
                ]
              }
            ]
          }
        },
        "writer": {
          "name": "mysqlwriter",
          "parameter": {
            "username": "xxxx",
            "password": "xxxx",
            "connection": [
              {
                "jdbcUrl": "jdbc:mysql://x.x.x.x:3306/target?useSSL=false",
                "table": [
                  "tb_user_target"
                ]
              }
            ],
            "writeMode": "insert",
            "column": [
              {
                "name": "id",
                "type": "int"
              },
              {
                "name": "name",
                "type": "string"
              },
              {
                "name": "phone",
                "type": "string"
              }
            ]
          }
        }
      }
    ],
    "setting": {
      "speed": {
        "channel": 1,
          "bytes": 0
      }
    }
  }
}

### What you expected to happen

Caused by: com.dtstack.chunjun.throwable.ChunJunRuntimeException: table td_user_source not found.

### How to reproduce

Caused by: com.dtstack.chunjun.throwable.ChunJunRuntimeException: table td_user_source not found.

### Version

1.12_release

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ll076110** [comment]
首先你得确定mysql数据库中是否存在该源表td_user_source

**Comment by Flamelay** [comment]
> 首先你得确定mysql数据库中是否存在该源表td_user_source

是有的，我本来以为是虚拟机访问Windows数据库的问题，结果测试Linux里的mysql还是一样的问题

**Comment by ll076110** [comment]
mysql是什么版本呢

**Comment by Flamelay** [comment]
> mysql是什么版本呢

用的5.7的

**Comment by ll076110** [comment]
好好检查一下你的配置，我试了mysql5.7是没问题的

**Comment by FlechazoW** [comment]
你试下加上schema参数呢？

**Comment by Flamelay** [comment]
> 你试下加上schema参数呢？

是数据库的schema_name值吗？我这里默认和数据库同名

**Comment by FlechazoW** [comment]
> > 你试下加上schema参数呢？
> 
> 是数据库的schema_name值吗？我这里默认和数据库同名

我的意思是，在任务脚本中加上schema参数，这个和table同级。

**Comment by Flamelay** [comment]
> 好好检查一下你的配置，我试了mysql5.7是没问题的



> > > 你试下加上schema参数呢？
> > 
> > 
> > 是数据库的schema_name值吗？我这里默认和数据库同名
> 
> 我的意思是，在任务脚本中加上schema参数，这个和table同级。

我想问的是加的这个参数值是在数据库查出来的那个schema_name值吗？我加的是  “schema“： “source” ，结果加上也不行

**Comment by Flamelay** [comment]
> > > 你试下加上schema参数呢？
> > 
> > 
> > 是数据库的schema_name值吗？我这里默认和数据库同名
> 
> 我的意思是，在任务脚本中加上schema参数，这个和table同级。

我想问的是加的这个参数值是在数据库查出来的那个schema_name值吗？我加的是 “schema“： “source” ，结果加上也不行

**Comment by Flamelay** [comment]
> 好好检查一下你的配置，我试了mysql5.7是没问题的

大佬，我这除了要检查JSON参数的设置还有啥配置需要检查呀？

**Comment by FlechazoW** [comment]
在connection里，加上schema 参数。参考如下：

<img width="469" alt="image" src="https://user-images.githubusercontent.com/35768015/180905135-d89f41e3-672c-45e1-ba68-1b892973ee22.png">

**Comment by FlechazoW** [comment]
长时间未收到回复，并且本地未复现，先关闭该issue，如问题仍然存在，可重开此issue。
