### ISSUE TITLE
[Question][connector-es6] does es-sink support nested and object data type?

### ISSUE THREAD

**Issue by geosmart** [DTStack/chunjun#1085]
### Search before asking

- [x] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [x] I had googled my question but i didn't get any help.

- [x] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

I want to read binlog and sink to es, and I handle the binlog event with udtf .

the udtf output row format is the same as the es document mapping.

so I  need the es sink connector to support nested data type  and object data type

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by PaddyMelody** [comment]
you can use ElasticSearch7Writer to write nested and object data in sync mode

**Comment by geosmart** [comment]
> you can use ElasticSearch7Writer to write nested and object data in sync mode

does this pr implement both es6 and es7?
https://github.com/DTStack/chunjun/commit/77f9c4cfcf4e715bacb504ae7707e8e59c140d67

**Comment by PaddyMelody** [comment]
In fact, we transmitted the NESTED type as a JSON STRING, which will be parsed before writing
<img width="898" alt="image" src="https://user-images.githubusercontent.com/46181516/182082837-0057c79f-e875-49c0-959c-6370f1668568.png">
<img width="969" alt="image" src="https://user-images.githubusercontent.com/46181516/182082868-dc1e5538-3907-4b89-bf1d-116307e97fd0.png">
This ‘null’ indicates that we do not care about the inner structure of the NESTED type.Therefore, the NESTED type is only supported in SYNC mode now

**Comment by geosmart** [comment]
@PaddyMelody thanks, finally got it. 
I develop  a udf call by transformer sql to parse  binlog  and sink the udf result rows  to es for realtime fulltext index.
