### ISSUE TITLE
Null pointer exception occurs when postgresql handles null values

### ISSUE THREAD

**Issue by shaolei7788** [DTStack/chunjun#1090]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

PostgresqlColumnConverter#createExternalConverter

case FLOAT:
                return (val, index, statement) ->
                        statement.setFloat(index, ((ColumnRowData) val).getField(index).asFloat());

((ColumnRowData) val).getField(index).asFloat() 等于null时 ，调用 setFloat(int fieldIndex, float x) 会发生异常，因为 Float 等于null时不能转为float

### What you expected to happen

correct deal with null value

### How to reproduce

see What happened

### Anything else

no

### Version

1.12_release

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by KinoMin** [comment]
刚好我也遇到了doris->mysql空值问题，提交了一个pr，你可以尝试一下
https://github.com/DTStack/chunjun/pull/1081/commits/0476231fa4b4132fed63168bcf67f8c21a3ae883

**Comment by shaolei7788** [comment]
> 刚好我也遇到了doris->mysql空值问题，提交了一个pr，你可以尝试一下 [0476231](https://github.com/DTStack/chunjun/commit/0476231fa4b4132fed63168bcf67f8c21a3ae883)

谢谢回复，你这个解决办法，对我说的那种情况没有，我自己已经临时修复了

**Comment by KinoMin** [comment]
已经在 (#1099 ) 解决了这个问题
