### ISSUE TITLE
[Question][setting] mysql批量插入mysql时，设置errorLimit，结果很疑惑

### ISSUE THREAD

**Issue by mztt-elfine** [DTStack/chunjun#1095]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [X] I had googled my question but i didn't get any help.

- [X] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

使用mysql批量插入mysql时，设置limit值无效
任务json如下：
`
{
    "job": {
      "content": [
        {
          "reader": {
            "name": "mysqlreader",
            "parameter": {
              "column": [
                {
                  "name": "id",
                  "type": "int"
                },
                {
                  "name": "message",
                  "type": "varchar"
                }
              ],
              "username": "root",
              "password": "123456",
              "connection": [
                {
                  "jdbcUrl": [
                    "jdbc:mysql://localhost:3306/mydb?useSSL=false"
                  ],
                  "table": [
                    "t6"
                  ]
                }
              ]
            }
          },
          "writer": {
            "name": "mysqlwriter",
            "parameter": {
              "username": "root",
              "password": "123456",
              "connection": [
                {
                  "jdbcUrl": "jdbc:mysql://localhost:3306/mydb?useSSL=false",
                  "table": [
                    "t5"
                  ]
                }
              ],
              "writeMode": "insert",
              "column": [
                {
                  "name": "id",
                  "type": "int"
                },
                {
                  "name": "message",
                  "type": "int"
                }
              ]
            }
          }
        }
      ],
      "setting": {
        "speed": {
          "channel": 1,
          "bytes": 0
        },
        "errorLimit" : {
          "record": 500,
          "percentage": 96.0
        }
      }
    }
  }
`

（源字段message） varchar类型->int类型字段（ 目标表字段message），理论上应该同步不了数据, 但是查看数据终端没报错，查看数据如下
<img width="402" alt="1658914843(1)" src="https://user-images.githubusercontent.com/42823423/181218081-87a61111-21c2-43a7-aa51-eef2fda45211.png">

version: 1.12_release

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
1.12_release 脏数据配置这部分内容已经做了调整。详情请看文档：https://dtstack.github.io/chunjun/documents

**Comment by mztt-elfine** [comment]
> 1.12_release 脏数据配置这部分内容已经做了调整。详情请看文档：https://dtstack.github.io/chunjun/documents
看过，看到代码里errorRecord，errorPercentage已经不使用了，就想确认下errorLimit的配置1.12已经丢弃了吗

**Comment by FlechazoW** [comment]
1.12 是重构了，考虑兼容sql 任务和 sync 同步任务，所以将 errorLimit舍弃了。

**Comment by mztt-elfine** [comment]
> 1.12 是重构了，考虑兼容sql 任务和 sync 同步任务，所以将 errorLimit舍弃了。

好的，感谢大佬

**Comment by FlechazoW** [comment]
是否可以关闭这个issue了呢？

**Comment by mztt-elfine** [comment]
> 是否可以关闭这个issue了呢？

可以的，谢谢大佬
