### ISSUE TITLE
找不到或无法加载主类 .home.chunjun-dist.lib.chunjun-clients-master.jar

### ISSUE THREAD

**Issue by zjialin** [DTStack/chunjun#1102]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [ ] I had googled my question but i didn't get any help.

- [X] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

错误: 找不到或无法加载主类 .home.chunjun-dist.lib.chunjun-clients-master.jar
[root@node3 chunjun-dist]# echo $FLINK_HTME

[root@node3 chunjun-dist]# echo $FLINK_HOME
/home/flink-1.12.7
[root@node3 chunjun-dist]# echo $CHUNJUN_HOME
/home/chunjun-dist
[root@node3 chunjun-dist]# echo $JAVA_HOME
/home/jdk1.8.0_333
[root@node3 chunjun-dist]# sh bin/chunjun-local.sh  -job chunjun-examples/json/stream/stream.json

          #                               #
          #                               #
          #
  #####   ######   #     #  # ####     ####   #     #  # ####
 #        #     #  #     #  ##    #       #   #     #  ##    #
 #        #     #  #     #  #     #       #   #     #  #     #
 #        #     #  #    ##  #     #       #   #    ##  #     #
  #####   #     #   #### #  #     #       #    #### #  #     #
                                          #
                                      ####

CHUNJUN_HOME is auto set  /home/chunjun-dist
FLINK_HOME is /home/flink-1.12.7
HADOOP_HOME is 
ChunJun starting ...
start command: /home/jdk1.8.0_333/bin/java -cp /home/chunjun-dist/lib/* com.dtstack.chunjun.client.Launcher -job chunjun-examples/json/stream/stream.json -mode local -jobType sync -chunjunDistDir /home/chunjun-dist -flinkConfDir /home/flink-1.12.7/conf -flinkLibDir /home/flink-1.12.7/lib
错误: 找不到或无法加载主类 .home.chunjun-dist.lib.chunjun-clients-master.jar
[root@node3 chunjun-dist]# 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
执行命令的当前路径下有哪些东西呢？

**Comment by zjialin** [comment]
drwxr-xr-x  2 501 games     308 7月  22 10:11 bin
-rw-r--r--  1 501 games 8591111 7月  25 10:37 chunjun-core-master.jar
drwxr-xr-x  4 501 games      29 7月  15 18:15 chunjun-examples
drwxr-xr-x 41 501 games    4096 7月  22 10:16 connector
drwxr-xr-x  3 501 games      19 7月  22 10:15 ddl
drwxr-xr-x  4 501 games      30 7月  22 10:15 dirty-data-collector
drwxr-xr-x  2 501 games      52 7月  29 13:37 docker-build
drwxr-xr-x  5 501 games      54 7月  12 14:50 docs
drwxr-xr-x  3 501 games      22 7月  22 10:14 formats
drwxr-xr-x  2 501 games    4096 7月  15 18:15 jars
drwxr-xr-x  2 501 games      67 7月  16 09:21 lib
drwxr-xr-x  4 501 games      37 7月  22 10:14 metrics
-rw-r--r--  1 501 games    7849 7月  20 11:14 README_CH.md
-rw-r--r--  1 501 games    9116 7月  20 11:14 README.md
drwxr-xr-x  3 501 games      19 7月  22 10:15 restore-plugins

**Comment by zjialin** [comment]
drwxr-xr-x  2 501 games     308 7月  22 10:11 bin
-rw-r--r--  1 501 games 8591111 7月  25 10:37 chunjun-core-master.jar
drwxr-xr-x  4 501 games      29 7月  15 18:15 chunjun-examples
drwxr-xr-x 41 501 games    4096 7月  22 10:16 connector
drwxr-xr-x  3 501 games      19 7月  22 10:15 ddl
drwxr-xr-x  4 501 games      30 7月  22 10:15 dirty-data-collector
drwxr-xr-x  2 501 games      52 7月  29 13:37 docker-build
drwxr-xr-x  5 501 games      54 7月  12 14:50 docs
drwxr-xr-x  3 501 games      22 7月  22 10:14 formats
drwxr-xr-x  2 501 games    4096 7月  15 18:15 jars
drwxr-xr-x  2 501 games      67 7月  16 09:21 lib
drwxr-xr-x  4 501 games      37 7月  22 10:14 metrics
-rw-r--r--  1 501 games    7849 7月  20 11:14 README_CH.md
-rw-r--r--  1 501 games    9116 7月  20 11:14 README.md
drwxr-xr-x  3 501 games      19 7月  22 10:15 restore-plugins

**Comment by zjialin** [comment]
我就是按照官方文档操作的

**Comment by FlechazoW** [comment]
lib 下是否有两个jar呢？有的话，请删除时间较早的那个

**Comment by zjialin** [comment]
是的
-rw-r--r-- 1 501 games 182610702 7月  13 10:34 chunjun-clients.jar
-rw-r--r-- 1 501 games 182611442 7月  25 10:41 chunjun-clients-master.jar
请问删除那一个？ 是我才从官方下载的

**Comment by FlechazoW** [comment]
13号的那个

**Comment by zjialin** [comment]
ok 谢谢

**Comment by FlechazoW** [comment]
已在最新的release包中删除了多余的jar包。
