### ISSUE TITLE
chunjun 支持mysql 的cdc  吗？请问如何配置的

### ISSUE THREAD

**Issue by zjialin** [DTStack/chunjun#1105]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [X] I had googled my question but i didn't get any help.

- [X] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

chunjun 支持mysql 的cdc  吗？请问如何配置的 是否还需其他的依赖

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
binlog 支持，详情请看文档-> https://dtstack.github.io/chunjun/documents

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/35768015/181725162-1e8e05d2-3cd4-4434-96eb-fdc8e9f54e97.png">

**Comment by FlechazoW** [comment]
如果文档内容不够详细可以重新打开这个issue，我们会继续跟进。
