### ISSUE TITLE
Where can I download chunjun-dist of Flink1.14

### ISSUE THREAD

**Issue by zhilinli123** [DTStack/chunjun#1114]
### Search before asking

- [x] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [x] I had googled my question but i didn't get any help.

- [x] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

Did I check the official website and find no detailed documents of relevant cases for reference

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
We don't have stable version for flink 1.14, only beta version.

**Comment by zhilinli123** [comment]
@FlechazoW  How am I supposed to launch the test version when there's no documentation for it and the previous ones were 1.12

**Comment by FlechazoW** [comment]
Chunjun '1.14 beta' branch is similar with 'master' branch, and only 'local-test' mode is available.
