### ISSUE TITLE
Flink Standalone 运行不了报错

### ISSUE THREAD

**Issue by yimingtech** [DTStack/chunjun#1116]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [ ] I had googled my question but i didn't get any help.

- [ ] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

![image](https://user-images.githubusercontent.com/4756021/182140862-06d17764-80ac-430d-9157-390e197b0aa1.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yimingtech** [comment]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/4756021/182145106-e274a593-afe4-4371-9e88-0ae1492891c7.png">
环境变量设置好之后，报这个问题了

**Comment by FlechazoW** [comment]
能将报错信息截图完整呢？

**Comment by FlechazoW** [comment]
我这没有复现出该问题，具体执行路径的内容可以看下视频：https://www.bilibili.com/video/BV1TT41137UV?spm_id_from=333.999.0.0&vd_source=f1ba2b9ca22c992869690d82e9d3411d
