### ISSUE TITLE
[Question][PostgreSQL Source] which situation is fit for jdbcConf.isIncrement()=true && jdbcConf.isPolling()=false

### ISSUE THREAD

**Issue by baisui1981** [DTStack/chunjun#1130]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [X] I had googled my question but i didn't get any help.

- [X] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

which situation is fit for jdbcConf.isIncrement()=true && jdbcConf.isPolling()=false, as below

https://github.com/DTStack/chunjun/blob/0d3c3fb5602d79ec501f52d027560f43a18d8d3e/chunjun-connectors/chunjun-connector-jdbc-base/src/main/java/com/dtstack/chunjun/connector/jdbc/source/JdbcInputFormat.java#L140-L142

As my opinion, use CDC from db by polling mode ,the boolean ` jdbcConf.isIncrement()` and `jdbcConf.isPolling()` both should be true, My question is ,in which statutation fit for:
``` java
 jdbcConf.isIncrement()=true && jdbcConf.isPolling()=false
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by PaddyMelody** [comment]
1.The Polling mode extends the incremental mode(We distinguish whether a job is increment based on whether IncreColumn exists)
2.The polling mode must be the increment mode, but the increment mode is not necessarily the polling mode
3.The polling mode does not rely on endLocation
