### ISSUE TITLE
chunjun可以保持数据执行的时序吗

### ISSUE THREAD

**Issue by weiugn** [DTStack/chunjun#1135]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [X] I had googled my question but i didn't get any help.

- [X] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

hello, 可以帮忙解答一下这个问题吗。
比如一条记录在源库前后有两个update操作，然后写入到目的库的时候前的update先执行，后的update后执行。chunjun有机制来保持这个时序吗？

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
可以的，实时采集插件，如binlog，logminer都是保证采集数据的顺序性。

**Comment by weiugn** [comment]
好的，感谢您的回复，然后想再问一下mysql-source, mongodb-source, es7-source这些是实时采集插件吗，还有写入插件能保证顺序性吗？
