### ISSUE TITLE
chunjun master版本 按照文档 编译 然后运行 找不到主类

### ISSUE THREAD

**Issue by biandou1313** [DTStack/chunjun#1148]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

CHUNJUN_HOME is auto set  
FLINK_HOME is /opt/flink/flink-1.12.2
HADOOP_HOME is /opt/hadoop/hadoop-2.7.4
ChunJun starting ...
start command: /usr/java/jdk1.8.0_261/bin/java -cp /../lib/* com.dtstack.chunjun.client.Launcher -job /opt/flinkx/flinkx-1.15/job/test111.json -mode yarn-per-job -jobType sync -chunjunDistDir  -flinkConfDir /opt/flink/flink-1.12.2/conf -flinkLibDir /opt/flink/flink-1.12.2/lib -hadoopConfDir /opt/hadoop/hadoop-2.7.4/etc/hadoop
错误: 找不到或无法加载主类 ....lib.debug

### What you expected to happen

![Uploading image.png…]()

### How to reproduce

![image](https://user-images.githubusercontent.com/34857750/184561288-798bc6d3-c751-41ae-a980-1d70e0d0ea46.png)

### Anything else

![image](https://user-images.githubusercontent.com/34857750/184561271-801c8155-c7e2-4035-ab1e-1b31f67fb283.png)

### Version

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by biandou1313** [comment]
![image](https://user-images.githubusercontent.com/34857750/184561600-242af143-2ffc-40d3-8ae6-3d225fa53fca.png)
这个jar 压根就没有主类

**Comment by FlechazoW** [comment]
我们目前没有1.15版本呐。。

**Comment by biandou1313** [comment]
> 我们目前没有1.15版本呐。。

master分支

**Comment by ljx072115** [comment]
这个我也遇到过，我这边是通过bin/chunjun-local提交的，只能在bin目录下执行，可以看下submit.sh 脚本，他那个lib目录是写死了的 ../lib

**Comment by lvyanquan** [comment]
CHUNJUN_HOME 这个环境变量需要手动设置一下

**Comment by FlechazoW** [comment]
This issue has been open too long for us to help, if you still have the same problem, please re-open an issue.
