### ISSUE TITLE
[Doc][quick-start] How to start a Flink standalone cluster with chunjun dependencies

### ISSUE THREAD

**Issue by lvyanquan** [DTStack/chunjun#1168]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar document issue.

### Description

if we just start a Flink standalone cluster with command like
```
bash $FLINK_HOME/bin/start-cluster.sh
```
you will meet class not found exception because dependencies of chunjun are not included.

Some document should be add to explain how to start a Flink standalone cluster with chunjun dependencies before using start-cluster.sh.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
PR merged.
