### ISSUE TITLE
[Bug] [Doris Sink]  param of batchSize set to Doris Sink config is useless

### ISSUE THREAD

**Issue by baisui1981** [DTStack/chunjun#1171]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

By the document of [Chunjun Doris Sink](https://dtstack.github.io/chunjun/documents/ChunJun%E8%BF%9E%E6%8E%A5%E5%99%A8@doris@dorisbatch-sink) , adding config param of `batchSize` with value of 100,

 When I debug the code processing of Doris Sink as below:

https://github.com/DTStack/chunjun/blob/ee6aeaa6ff0211d423295457d686e7111e4d4136/chunjun-core/src/main/java/com/dtstack/chunjun/sink/format/BaseRichOutputFormat.java#L212

As debug, value of  `config.getBatchSize()` is **1** (not 100) ,this led to `DorisStreamLoad` commit record immediately without any locally buffering

I has review the Doris Sink Code as below，
https://github.com/DTStack/chunjun/blob/ee6aeaa6ff0211d423295457d686e7111e4d4136/chunjun-connectors/chunjun-connector-doris/src/main/java/com/dtstack/chunjun/connector/doris/options/DorisConf.java#L179-L182

when I append code then  `batchSize` will take effect.
```java
jdbcConf.setBatchSize(this.getBatchSize())
```

### What you expected to happen

make the param of batchSize set to Doris Sink config take effect.

### How to reproduce

as described above

### Version

1.12_release

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by PaddyMelody** [comment]
Thanks for your issue. Could you provide a PullRequest to fix it？

**Comment by baisui1981** [comment]
> 
sure

**Comment by baisui1981** [comment]
> Thanks for your issue. Could you provide a PullRequest to fix it？

sure
