### ISSUE TITLE
[Feature][Assembly] rename chunjun install filename

### ISSUE THREAD

**Issue by huaxiapanda** [DTStack/chunjun#1183]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar feature requirement.

### Description

now ，the chunjun install filename is chunjun-assembly-1.12-SNAPSHOT-chunjun-dist.tar.gz but the docs more used chunjun-dist.tar.gz.modify assembly.xml and chunjun-assembly's pom.xml to rename install file name
![image](https://user-images.githubusercontent.com/55483248/186561797-441c02ef-b482-4793-9dc8-2da2d96e720e.png)

### Use case

the install filename is chunjun-dist-1.12.SNAPSHOT.tar.gz
![image](https://user-images.githubusercontent.com/55483248/186562831-001843c8-053c-4d95-98a0-777dd951bb77.png)
![image](https://user-images.githubusercontent.com/55483248/186562957-2c45e15d-ffe5-41b3-a499-fd80e910c7b9.png)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
PR merged.
