### ISSUE TITLE
找不到或无法加载主类 .data.flinkx.chunjun-dist....lib.flink-annotations-1.12.7.jar[Question][Module Name] Ask for question

### ISSUE THREAD

**Issue by xuph2019** [DTStack/chunjun#1270]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [ ] I had googled my question but i didn't get any help.

- [ ] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

![image](https://user-images.githubusercontent.com/59075791/191154209-dfc9d33d-2f8d-4fec-967d-4ad430aca03f.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liumengkai** [comment]
Make your lib like this,delete other jar or move them out，only keep ‘chunjun-clients.jar’ ，and try again

<img width="365" alt="image" src="https://user-images.githubusercontent.com/31892927/191403300-a292a3d4-7ae8-4c49-98f6-b456f6a89afc.png">

**Comment by zou79189747** [comment]
解决了吗？
