### ISSUE TITLE
ftp作为sink，报错空指针，FtpOutputFormat未进行实例化

### ISSUE THREAD

**Issue by lujisen** [DTStack/chunjun#1282]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/28383245/191910575-048cf3d6-fae1-49c8-87c6-b326f460dc02.png)
![image](https://user-images.githubusercontent.com/28383245/191910645-5850c7a0-8264-44f4-ac11-69e4c938ebc2.png)

### What you expected to happen

已编译打印日志 是local  standalone模式都已进行测试

### How to reproduce

已编译打印日志 是local  standalone模式都已进行测试

### Version

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
请问你是sql任务还是json同步任务呢？
