### ISSUE TITLE
[Bug] [Standalone] Error uploading binlog job to standalone cluster

### ISSUE THREAD

**Issue by PaddyMelody** [DTStack/chunjun#1338]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

My standalone enabled the HA configuration，When I uploaded the binlog job for the second time, the task reported an error
The error appears to have occurred in jobmanager
<img width="1768" alt="image" src="https://user-images.githubusercontent.com/46181516/197457058-6680c06b-5cd5-40d0-bf94-5636af7debd3.png">

### What you expected to happen

The job runs no matter how many times it is submitted

### How to reproduce

just launches the standalone cluster of two JobManagers, three TaskManagers, and uploads binlog jobs twice

### Version

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
PR merged. #1339
