### ISSUE TITLE
[Feature][core] support muti params after -p

### ISSUE THREAD

**Issue by liumengkai** [DTStack/chunjun#1388]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar feature requirement.

### Description

As we know we can set params after -p like this 
```
-p mysql_server=127.0.0.1
```
Then we can use it in our json file like this
```
${mysql_server}
```

But we don't support -p with comma like this
```
-p bootstrap=host1:9092,host2:9092
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
PR merged.
