### ISSUE TITLE
[Doc][README.md] fix \r problems caused by windows

### ISSUE THREAD

**Issue by zhengchaoken** [DTStack/chunjun#1402]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar document issue.

### Description

在windows环境下打包时，sh脚本中换行为\r。会导致在linux下运行示例脚本时异常

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
PR merged.
