### ISSUE TITLE
[Bug] [oraclelogminer-x] oracleLogmr_to_stream.sql报错

### ISSUE THREAD

**Issue by waryars** [DTStack/chunjun#1438]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/118407740/206323313-5ff03a50-3722-4bd0-8361-73de2b7c6ea5.png)

### What you expected to happen

oracleLogmr_to_stream.sql报错，to_kafka的sql脚本也是一样，在local模式下运行，需要解决掉报错，能正常运行。

### How to reproduce

一、环境准备：
oracle11g，归档及logmr已开启，source表结构：
SQL> desc TEST_LOGMR
 Name						       Null?	Type
 ----------------------------------------------------- -------- ------------------------------------
 ID								NUMBER(38)
 TDATE								DATE
 CNAME								VARCHAR2(50)
 SAL_AMT							NUMBER(10,2)

二、sql配置脚本：
[root@t-hadoop01 sql-script]# cat oraclelogmr_stream.sql
CREATE TABLE source
(
        id int,
	tdate timestamp,
	cname varchar,
	sal_amt  decimal(10,2) 
) WITH (
      'connector' = 'oraclelogminer-x'
      ,'url' = 'jdbc:oracle:thin:@172.16.44.55:1521:orcl'
      ,'username' = 'roma_logminer'
      ,'password' = 'password'
      ,'cat' = 'insert,delete,update'
      ,'table' = 'sys.test_logmr'
      ,'timestamp-format.standard' = 'SQL'
      );

CREATE TABLE sink
(
        id int,
	tdate timestamp,
	cname varchar,
	sal_amt  decimal(10,2) 
) WITH (
      'connector' = 'stream-x'
      );

insert into sink
select *
from source u;

三、执行命令：
[root@t-hadoop01 chunjun-dist112]# sh bin/chunjun-local.sh -job sql-script/oraclelogmr_stream.sql  

四、执行结果：
报错，见What happened

### Version

1.12_release

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zoudaokoulife** [comment]
@waryars 
it's a bug,you can fix it by com.dtstack.chunjun.connector.oraclelogminer.table.OraclelogminerDynamicTableFactory#getLogMinerConf
"
 logMinerConf.setPavingData(true); ==> change to false
 logMinerConf.setSplit(true);
"

we  will fix it next time.
