### ISSUE TITLE
[Improve][jdbc] improvement jdbc read/write performance

### ISSUE THREAD

**Issue by zoudaokoulife** [DTStack/chunjun#1469]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar feature requirement.

### Description

when test the jdbc connector，we find some function take more time. and compare to datax,  at one parall the bps less then it. 
   target: one  parall bps ~= datax, and multi parall better then it

### Use case

none

### Related issues

no issuse

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
pr merged. close as #1488
