### ISSUE TITLE
[Bug] [hbase connector] hbase default ttl

### ISSUE THREAD

**Issue by liumengkai** [DTStack/chunjun#1485]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

cell ttl is millisecond not second。

![image](https://user-images.githubusercontent.com/31892927/212071894-2570a735-e96c-46fa-a6af-db86ff1e8f52.png)

### What you expected to happen

default ttl is Integer.MAX_VALUE * 1000

### How to reproduce

hbase writer without ttl config

### Version

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
Merged pr #1486
