### ISSUE TITLE
[Feature][http] http读取数据支持字段对应数据为数组的拆分

### ISSUE THREAD

**Issue by yanghuaiGit** [DTStack/chunjun#1494]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar feature requirement.

### Description

![image](https://user-images.githubusercontent.com/38883656/216913081-491f62a8-1390-4a11-be14-540d33d1c7aa.png)

返回的数据是一个json，里面有一个字段data对应的数据是json数组，想把这个json数组的里每个json作为一个数据发送给下游，而不是整体作为一个数据给下游

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
close #1495
