### ISSUE TITLE
[Bug] BaseRichOutputFormat 抛出NoRestartException 可能会导致任务无法正常停止

### ISSUE THREAD

**Issue by zhourui999** [DTStack/chunjun#1501]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/40812600/218686651-039b181d-ff51-4789-8b32-749bb42fa4aa.png">

timerWriteException 这个变量的赋值只会在定时任务失败后，如果是preCommit调用则会导致抛出的NoRestartException被吃掉

### What you expected to happen

任务停止

### How to reproduce

关闭定时提交的任务initTimingSubmitTask()

### Version

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zoudaokoulife** [comment]
这个地方确实是一个bug;
![image](https://user-images.githubusercontent.com/5635921/218960024-b85ac544-af0a-405c-8cc8-c0ac9ef913f5.png)

这个地方不应该只是打印日志；

**Comment by zoudaokoulife** [comment]
@zhourui999 你要修复下这个bug吗？

**Comment by zhourui999** [comment]
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/40812600/219298309-4be84619-a281-478c-804c-2f3cdfa5522d.png">
我本地的改了，建议加上       checkTimerWriteException(); 要不然脏数据产生有时也不能立马停止。目前是产生一个脏数据后，需要后续继续有数据过来才能停止程序
