### ISSUE TITLE
[Feature][core] sql模式里支持set 语法

### ISSUE THREAD

**Issue by libailin** [DTStack/chunjun#1525]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar feature requirement.

### Description

在sql模式支持 set 语法，例如读取kafka时设置以下 参数

```
SET table.exec.mini-batch.enabled=TRUE;
SET table.exec.mini-batch.allow-latency=5s;
SET table.exec.mini-batch.size=5000;
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
PR merged. close #1526
