### ISSUE TITLE
请问，哪个版本是可编译的稳定的？

### ISSUE THREAD

**Issue by taotaizhu-pw** [DTStack/chunjun#1527]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar question.

- [ ] I had googled my question but i didn't get any help.

- [ ] I had read the documentation: [ChunJun doc](https://dtstack.github.io/chunjun) but it didn't help me.

### Description

尝试了master，1.14_beta两个版本， 各有不同的编译错误。 

master报错：
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.4.0:compile (scala-compile-first) on project chunjun-core: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:4.4.0:compile failed: An API incompatibility was encountered while executing net.alchim31.maven:scala-maven-plugin:4.4.0:compile: java.lang.NoSuchMethodError: org.fusesource.jansi.AnsiConsole.wrapOutputStream(Ljava/io/OutputStream;)Ljava/io/OutputStream;

1.14_bata的flinkx_client没有被放在最外层的pom.xml里，加入后也是各类不同的报错。

请问哪个版本或者分支、tag是可以正常编译的？ 用eclipse或者idea在windows环境下，可以么？ 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mutouh** [comment]
研究一上午，master实测用项目里指定的maven wrapper是可以的，不要用自己安装的maven。用readme里的构建命令`./mvnw clean package`，可以跳过测试`./mvnw clean package -DskipTests`

**Comment by FlechazoW** [comment]
建议版本 1.12_release/ master
