### ISSUE TITLE
[Bug] [startrock] feNodes parameter verification problem 

### ISSUE THREAD

**Issue by yanghuaiGit** [DTStack/chunjun#1571]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

The feNodes parameter cannot be empty. The array is not checked to see if it is empty

### What you expected to happen

throw exception when check fenodes parameter

### How to reproduce

check fenodes can not empty

### Version

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FlechazoW** [comment]
pr merged. close #1572
