### ISSUE TITLE
[功能][chun-connectots]缺少人大金仓数据源连接

### ISSUE THREAD

**Issue by Shenmoheti** [DTStack/chunjun#1588]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar feature requirement.

### Description

生产环境上需要对接人大金仓的数据源，自己有人大金仓的jar包，如果因为版权的问题，建议让用户自己增加需要依赖的jar包，只需要提供解决方法；

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Shenmoheti** [comment]
问题比较紧急

**Comment by ChestnutQiang** [comment]
建议是去把 jar 传到 maven 私服上去，然后自己开发一个 connector 插件。可以参考 B 站的视频，如何开发一个 connector 插件。
https://www.bilibili.com/video/BV1864y1t7Kv/?spm_id_from=333.788.recommend_more_video.17&vd_source=3989a956376b0b9791de10f841730852

**Comment by baisui1981** [comment]
我看了一下 他提供的 驱动https://www.kingbase.com.cn/qd/index.htm，你指的是哪个驱动？

**Comment by libailin** [comment]
恩，强烈建议驱动升级到8.6.0版本。

```
<dependency>
	<groupId>com.kingbase8</groupId>
	<artifactId>kingbase8</artifactId>
	<version>8.6.0</version>
</dependency>
```
