### ISSUE TITLE
[Bug] [chunjun-client]NullPointerException in Local mode 

### ISSUE THREAD

**Issue by losesinal** [DTStack/chunjun#1629]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

NullPointerException in Launcher
Exception in thread "main" java.lang.NullPointerException
        at com.dtstack.chunjun.client.Launcher.main(Launcher.java:88)

### What you expected to happen

when this code run 
   try (ClusterClient<?> client = clusterClientHelper.submit(jobDeployer)) {
            log.info(client.getClusterId() + " submit successfully.");
        }
the client maybe null。

### How to reproduce

when use local mode it will happen on the end of Main .

### Version

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lvyanquan** [comment]
close as the pr is merged
