### ISSUE TITLE
[Feature][hive] 支持jdbc方式读取hive 

### ISSUE THREAD

**Issue by libailin** [DTStack/chunjun#1649]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar feature requirement.

### Description

特点：
1. 支持自定义hive sql方式读取
2. json && sql模式均支持
3. 支持配置hive 作业名称

### Use case

```

CREATE TABLE source
(
    num          bigint
) WITH (
      'connector' = 'hive-x'
      ,'url' = 'jdbc:hive2://ip:10000/test'
      ,'username' = 'username'
      ,'password' = 'pwd'
      ,'table-name' = ''
      ,'default-fs' = ''
      ,'file-type' = ''
      ,'properties.mapred.job.name' = 'yarn applicaiton name'
      ,'scan.custom-sql' = 'select count(*) as num from flinkx_hive_test where p_day=20220119'
      );

```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zoudaokoulife** [comment]
@libailin hive jdbc 的方式对计算来说相对比较，而且flink 本身能读取hdfs，可以考虑在flink 里面对hdfs 进行scan + filter 操作。

**Comment by 715484127** [comment]
您好：请问本地LocalTest测试hivereader是报错Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.conf.Configuration，如何处理？
但是相关的jar包maven已经导入，并且maven打包是不报错的

**Comment by 715484127** [comment]
已解决，本地测试需要注释掉一些pom中的<scope>provided</scope>
