### ISSUE TITLE
[Bug] [chunjun-core]  脏数据管理应该判断总体脏数据 而不是单个slot 

### ISSUE THREAD

**Issue by david-gao1** [DTStack/chunjun#1718]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

最近在使用chunjun的脏数据管理模块 出现了和预想不同的情况

比如消费一个上百亿的数据，设置并发为300，设置脏数据量不超过50万，运行了多次之后，flink任务报错出现了大于设定值的脏数据报错，导致任务挂掉的情况。
<img width="364" alt="image" src="https://github.com/DTStack/chunjun/assets/49160235/39ce14d6-fb5d-498d-bd77-e2380dd162e4">

我查看了chunjun的代码，看到脏数据报错是每个运行的slot代码中报错的，即脏数据积累不是所有slot积累之后报错，而是单个slot积累脏数据报错，
对于总体metric的累加会触发一个定时任务每tm心跳+1s，去聚合这些所有slot的运行结果，但是没找到和单个slot同步的逻辑。

<img width="940" alt="image" src="https://github.com/DTStack/chunjun/assets/49160235/f481a65d-e0cf-42c1-bdea-000ead27891e">

脏数据触发的异常导致flink任务挂掉 不适合多线程的情况。

### What you expected to happen

比如消费一个上百亿的数据，设置并发为300，设置脏数据量不超过50万，运行了多次之后，flink任务报错出现了大于设定值的脏数据报错，导致任务挂掉的情况。
<img width="364" alt="image" src="https://github.com/DTStack/chunjun/assets/49160235/39ce14d6-fb5d-498d-bd77-e2380dd162e4">

我查看了chunjun的代码，看到脏数据报错是每个运行的slot代码中报错的，即脏数据积累不是所有slot积累之后报错，而是单个slot积累脏数据报错，
对于总体metric的累加会触发一个定时任务每tm心跳+1s，去聚合这些所有slot的运行结果，但是没找到和单个slot同步的逻辑。

<img width="940" alt="image" src="https://github.com/DTStack/chunjun/assets/49160235/f481a65d-e0cf-42c1-bdea-000ead27891e">

脏数据触发的异常导致flink任务挂掉 不适合多线程的情况。

### How to reproduce

如上述情况：一个hdfs同步任务中输入源有多个文件待消费，假设每个文件都有些许脏数据，设置并发等于文件数，启动任务。

设置脏数据等于n，当任务运行完成时、或因为脏数据超出设定值n，而导致任务挂掉，都会出现消费的脏数据大于设置的n。

### Anything else

已在钉钉群中同步相关开发人员，并且我这里已经有解决方案，司内已经修改使用。
![image](https://github.com/DTStack/chunjun/assets/49160235/aaba7103-9c96-4189-8da1-aac0acceca04)
![image](https://github.com/DTStack/chunjun/assets/49160235/d008f6d3-efca-489d-b2e1-f4a1539819f8)

修改地方包括 chunjun-core模块 kafka-connector模块

### Version

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ll076110** [comment]
对的，确实有这个问题，多并发运行时，每个source/sink都是单独的脏数据管理，我认为可以在聚合所有tm指标时将此值设置到globalValue中，请问你的解决方案是怎样的？
