### ISSUE TITLE
nameMapping 配置了不生效

### ISSUE THREAD

**Issue by yinshaohua77** [DTStack/chunjun#1733]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

在logminer 到oracle的json样例中，使用logminer_oracle_to_oracle.json文件，修改了里面连接信息，还有namemaping信息，然后运行，发现nameMapping配置的不生效，sink还是和原表一样的表名和字段，导致sink失败。

Source: oraclelogminersourcefactory -> Sink: oraclesinkfactory (1/1)#0]

中间没有flatmap进行处理，所以怀疑是nameMapping不生效
而且在修改nameMaping 变成mapping，也不报错，估计是直接过滤掉了这段解析

### What you expected to happen

希望能按照配置生效

### How to reproduce

使用1.12.8版本，修改logminer_oracle_to_oracle.json
使用local模式运行

### Version

1.12_release

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ll076110** [comment]
![image](https://github.com/DTStack/chunjun/assets/43375919/22eb3cb8-0033-495a-8b62-2ac06e3e8928)
