### ISSUE TITLE
分库问题

### ISSUE THREAD

**Issue by wangyanqun321** [DTStack/chunjun#178]
请问关系型数据库到hive支持分库吗(多个数据库的多张表同步到同一个hive表)？

**Comment by liumengkai** [comment]
> 请问关系型数据库到hive支持分库吗(多个数据库的多张表同步到同一个hive表)？

您好,请问您现在知道这个问题答案了吗?我也有相同的疑惑🤔

**Comment by wangyanqun321** [comment]
json格式是支持的，但是代码有bug，我们内部修复了这个bug



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月17日(星期四) 下午5:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DTStack/flinkx] 分库问题 (#178)





  
请问关系型数据库到hive支持分库吗(多个数据库的多张表同步到同一个hive表)？
  
您好,请问您现在知道这个问题答案了吗?我也有相同的疑惑🤔
