### ISSUE TITLE
错误: 找不到或无法加载主类 .opt.soft.chunjun.lib.log4j-1.2-api-2.16.0.jar

### ISSUE THREAD

**Issue by zhangbaipeng** [DTStack/chunjun#1789]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

chunjun安装版本 [chunjun-dist-1.12-SNAPSHOT.tar.gz]   1.12.8 最新版本
{CHUNJUN_HOME}/bin/start-chunjun -mode local -jobType sync -job ${CHUNJUN_HOME}/json/mysql-to-kafka.json 
发现启动报错  错误: 找不到或无法加载主类 .opt.soft.chunjun.lib.log4j-1.2-api-2.16.0.jar，删除掉lib下的 log* jar包 就可以了。
但是会有
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
	SLF4J: Defaulting to no-operation (NOP) logger implementation
	SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

### What you expected to happen

client 的启动代码在加载 log* jar包的时候是不是有问题

### How to reproduce

日志问题

### Version

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hhoao** [comment]
在./bin/start-chunjun里面加上
![image](https://github.com/DTStack/chunjun/assets/64757882/8504d941-5346-4609-859d-24421e45a063)
