### ISSUE TITLE
[Bug] [connector][jdbc] 当写入模式是replace/update时相关问题

### ISSUE THREAD

**Issue by libailin** [DTStack/chunjun#1799]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

sql模式，测试向mysql写入时，当配置写入模式时，出现相关问题：
1、没有相关参数可以配置写入模式，
2、当在sql create table sink里，配置了主键 PRIMARY KEY (xxx) NOT ENFORCED 不生效问题，原因是获取到错误的主键列名
3、当在 sql create table sink里，不配置主键 PRIMARY KEY 时，setKeyRowType、setKeyRowConverter 未正确执行，导致空指针。
4、另一个小问题，也可能是我测试用例不太好。比如一张表有两个唯一索引 username 、email , 现在两条记录，如图， 
![image](https://github.com/DTStack/chunjun/assets/3014381/6445bfc2-bed8-4151-a18a-7c913e2af3f7)

但是通过chunjun sql 再向表里插入一条 username 在id=1里，email在id=2里重复数据 在chunjun里就会报错 脏数据，

![image](https://github.com/DTStack/chunjun/assets/3014381/7a6d5b62-8fad-474e-8f04-a8be3cc60f74)

![image](https://github.com/DTStack/chunjun/assets/3014381/dd7a56a4-2674-43fd-aceb-941a3a243668)

如果是使用 mysql sql（REPLACE INTO flinkx_write_mode(id,username,email)
VALUES(1,'aa-replace-11', 'bb@126.com'); ）语法插入的话，虽然能插入成功，但是数据会容易混乱。两条数据就剩下一条了。以下是插入后结果

![image](https://github.com/DTStack/chunjun/assets/3014381/be715069-366b-415b-8f5f-68724283ae9d)

对只有一列是主键（唯一索引）开发测试没啥问题，但是当有两个唯一索引的时候，插入的新数据涉及到两行时就会报脏数据错误

### What you expected to happen

--

### How to reproduce

创建 mysql 表
```
CREATE TABLE flinkx_test.flinkx_write_mode (
  id int(11) NOT NULL,
  username varchar(255) NOT NULL DEFAULT '',
  email varchar(50) NOT NULL DEFAULT ''
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

ALTER TABLE flinkx_test.flinkx_write_mode
ADD UNIQUE INDEX UK_flinkx_write_mode_email (email);

ALTER TABLE flinkx_test.flinkx_write_mode
ADD UNIQUE INDEX UK_flinkx_write_mode_username (username);

```

插入数据：

```
INSERT INTO flinkx_write_mode (id, username, email) VALUES
(1, 'aa-replace-11', 'aa@163.com'),
(2, 'bb', 'bb@126.com');
```

```

CREATE TABLE source
(
    `username` varchar,
    `email` varchar
) WITH (
      'connector' = 'stream-x',
      'number-of-rows' = '1' 
      );
CREATE TABLE sink
(
    id int,
    `username` varchar,
    `email` varchar
    ,PRIMARY KEY (id) NOT ENFORCED
--     ,PRIMARY KEY (username, email) NOT ENFORCED
) WITH (
      'password' = 'xxx',
      'connector' = 'mysql-x',
      'sink.buffer-flush.interval' = '1000',
      'sink.buffer-flush.max-rows' = '1024',
      'sink.all-replace' = 'false',
      'write-mode' = 'replace',
      'table-name' = 'flinkx_write_mode',
      'url' = 'jdbc:mysql://xxxx:3306/flinkx_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&connectTimeout=3000&zeroDateTimeBehavior=convertToNull&useunicode=true&characterEncoding=utf8&useSSL=false&useCursorFetch=true&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull',
      'username' = 'xxx'
      );

CREATE TEMPORARY VIEW source_1 AS
select * FROM (VALUES (1,'aa', 'bb@126.com'))  AS t (id, username, email)
;

insert into sink select * from source_1;



```

### Version

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 413622944** [comment]
这里改下就能正确获取主键了
<img width="879" alt="image" src="https://github.com/DTStack/chunjun/assets/3888668/8a06e452-9f30-4e4b-b7a2-d60f0bc06f62">

**Comment by libailin** [comment]
> 

多谢提醒，己提交相关pr，等待合并修复
