### ISSUE TITLE
[Bug] [jdbc base] 使用Collections.singletonList返回不可修改list，但代码中进行了修改

### ISSUE THREAD

**Issue by david-gao1** [DTStack/chunjun#1869]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/chunjun/issues) and found no similar issues.

### What happened

[Bug] [jdbc base] 使用Collections.singletonList返回不可修改list，但代码中进行了修改

### What you expected to happen

[Bug] [jdbc base] 使用Collections.singletonList返回不可修改list，不修改list或者不返回不可修改list

### How to reproduce

表名中有点.

### Version

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zoudaokoulife** [comment]
关联的pr 已经合并
