### ISSUE TITLE
内存释放问题

### ISSUE THREAD

**Issue by RunningXuan** [DTStack/chunjun#210]
flinkx的任务完成后，内存无法释放，时间久了会有内存溢出问题
![image](https://user-images.githubusercontent.com/47099551/82294827-528ec100-99e1-11ea-85a1-164e488313e2.png)

**Comment by kanata163** [comment]
flink-conf.yaml中把`classloader.resolve-order`设置成`parent-first`试试，我standalone不断提交任务并没有出现你这种情况。

**Comment by RunningXuan** [comment]
能发下您的配置文件吗？我用的是1.10版本，加上了classloader.resolve-order：parent-first 还是有问题，
![image](https://user-images.githubusercontent.com/47099551/83705137-ae468480-a646-11ea-8980-fac2a3bdfe3b.png)

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
