### ISSUE TITLE
Metaspace内存释放问题

### ISSUE THREAD

**Issue by RunningXuan** [DTStack/chunjun#215]
任务结束后Metaspace所占用的内存不会释放，任务一直累加最终导致oom;
![image](https://user-images.githubusercontent.com/47099551/82515019-c21fc000-9b49-11ea-816d-971064c27cc1.png)

**Comment by kanata163** [comment]
flink-conf.yaml中把classloader.resolve-order设置成parent-first试试，我standalone不断提交任务并没有出现你这种情况。

**Comment by RunningXuan** [comment]
能发下您的配置文件吗？我用的是1.10版本，加上了classloader.resolve-order：parent-first 还是有问题，
![image](https://user-images.githubusercontent.com/47099551/83704932-1ba5e580-a646-11ea-88b3-0f0e1608b07e.png)

**Comment by kanata163** [comment]
flink1.10内存策略有所变更，我是用flink1.8测试的，你1.8版本也存在这种情况吗？

**Comment by RunningXuan** [comment]
发下1.8的配置文件吧，我试了1.8，还是有问题，感觉哪里配置出问题了

**Comment by kanata163** [comment]
jobmanager.rpc.address: flinkx1
jobmanager.rpc.port: 6123
jobmanager.heap.mb: 1024
taskmanager.heap.mb: 1024
taskmanager.numberOfTaskSlots: 1
parallelism.default: 1
rest.port: 8081
classloader.resolve-order: parent-first

state.backend.fs.checkpointdir: hdfs://ns/flink180/checkpoints/backend
state.checkpoints.dir: hdfs://ns/flink180/checkpoints/metadata
state.savepoints.dir: hdfs://ns/flink180/savepoints
state.checkpoints.num-retained: 10

akka.ask.timeout: 60 s
taskmanager.max-registration-pause: 30 s
yarn.maximum-failed-containers: 100 
yarn.application-attempts: 100

metrics.reporter.promgateway.class: org.apache.flink.metrics.prometheus.PrometheusPushGatewayReporter
metrics.reporter.promgateway.host: 你的IP 
metrics.reporter.promgateway.port: 9091
metrics.reporter.promgateway.jobName: 108job
metrics.reporter.promgateway.randomJobNameSuffix: true
metrics.reporter.promgateway.deleteOnShutdown: false

historyserver.web.address: 你的IP
historyserver.web.port: 8082
historyserver.archive.fs.dir: hdfs://ns/flink180/completed-jobs
historyserver.archive.fs.refresh-interval: 3000
jobmanager.web.history: 200
blob.service.cleanup.interval: 900
jobstore.expiration-time: 900
high-availability.job.delay: 525600 min
mode: legacy

env.java.opts.taskmanager: -XX:CompressedClassSpaceSize=2G
env.java.opts.jobmanager: -Xss6m

**Comment by RunningXuan** [comment]
jobmanager.heap.mb: 1024
taskmanager.heap.mb: 1024   
这两个参数1.8中就不支持了，您是用的flink1.8吗？

**Comment by RunningXuan** [comment]
我把这两个参数调整了下，还是有内存问题，您是怎么部署的？flinkx的插件放到flink目录下吗？

**Comment by kanata163** [comment]
1.8官方文档虽然删掉了这两个参数，但是flink源码里面还是会去读这个参数的。

**Comment by kanata163** [comment]
你把flinkx的插件包放到flink的lib目录下，然后把classloader.resolve-order设置成parent-first再试试

**Comment by RunningXuan** [comment]
在1.8 上试了下，问题仍旧存在，把您的任务文件发下吧，我看看是不是任务文件哪里配置有问题

**Comment by kanata163** [comment]
把flinkx的插件包放到flink的lib目录下，Job Manager启动时会打印出jar包信息
![image](https://user-images.githubusercontent.com/35188210/84023645-0b319a00-a9bb-11ea-9a2a-680a3b2833af.png)
刚启动时Task Manager内存信息：
![image](https://user-images.githubusercontent.com/35188210/84023681-1d133d00-a9bb-11ea-951b-3ebd6a6d38af.png)
提交一次MySQL->MySQL任务时Task Manager内存信息：
![image](https://user-images.githubusercontent.com/35188210/84023960-9ad74880-a9bb-11ea-9b30-6965f6c04610.png)
提交五次MySQL->MySQL任务时Task Manager内存信息：
![image](https://user-images.githubusercontent.com/35188210/84024348-4ed8d380-a9bc-11ea-861d-6420218d9300.png)
提交十次MySQL->MySQL任务时Task Manager内存信息：
![image](https://user-images.githubusercontent.com/35188210/84024816-1e456980-a9bd-11ea-9fb7-4171ffd8c158.png)
可以看出，第五次到第十次任务之间触发GC，堆内存被清理了一次；而非堆内存去除第一次外每次增长不到1MB，基本可以忽略。
flink配置就是上面的配置。
```json
{
  "job": {
    "content": [
      {
        "reader": {
          "name": "mysqlreader",
          "parameter": {
            "column": [
              {
                "name": "id",
                "type": "BIGINT",
                "key": "id"
              },
              {
                "name": "user_id",
                "type": "BIGINT",
                "key": "user_id"
              },
              {
                "name": "name",
                "type": "VARCHAR",
                "key": "name"
              }
            ],
            "username": "username",
            "password": "password",
            "connection": [
              {
                "jdbcUrl": [
                  "jdbc:mysql://ip:3306/test"
                ],
                "table": [
                  "test"
                ]
              }
            ]
          }
        },
        "writer": {
          "name": "mysqlwriter",
          "parameter": {
            "username": "username",
            "password": "password",
            "connection": [
              {
                "jdbcUrl": "jdbc:mysql://ip:3306/test",
                "table": [
                  "test_data"
                ]
              }
            ],
            "writeMode": "insert",
            "column": [
              {
                "name": "id",
                "type": "BIGINT",
                "key": "id"
              },
              {
                "name": "user_id",
                "type": "BIGINT",
                "key": "user_id"
              },
              {
                "name": "name",
                "type": "varchar",
                "key": "name"
              }
            ]
          }
        }
      }
    ],
    "setting": {
      "speed": {
        "channel": 1,
        "bytes": 0
      }
    }
  }
}
```

**Comment by RunningXuan** [comment]
就是这个会一直增加，我的任务比较多，上百个任务循环跑，最终metaspace被占完!
![image](https://user-images.githubusercontent.com/47099551/84122368-ea288200-aa6a-11ea-8a68-afa860be1641.png)

**Comment by kanata163** [comment]
那建议你最好使用yarn session模式，我们生产上都是部署yarn session模式的。

**Comment by libinjale2008** [comment]
遇到同样的问题，问题解决了吗，可否分享下经验

**Comment by YouweiZhang** [comment]
遇到同样的问题

**Comment by YouweiZhang** [comment]
flinkx是1.11. flink是1.11.3，standalone模式，用example里面的stream_stream任务测试，也存在metaspace一直增长的问题

**Comment by RunningXuan** [comment]
问题以已解决，动了源码
