### ISSUE TITLE
断点续传问题

### ISSUE THREAD

**Issue by RunningXuan** [DTStack/chunjun#217]
问题：断电续传不生效，检查点文件中没有生成检查点数据，导致出现故障时也无从恢复
作业设置参数如下：
![image](https://user-images.githubusercontent.com/47099551/82548003-33349700-9b8d-11ea-9fe1-79cf597007bc.png)
batchsize 如下：
![image](https://user-images.githubusercontent.com/47099551/82548089-56f7dd00-9b8d-11ea-94ef-d743e76c2abf.png)

**Comment by kanata163** [comment]
有生成checkpoint吗？有的话在日志里面搜一下`format state:`，看一下记录的id的值

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
