### ISSUE TITLE
HIVE是否支持自定义分区

### ISSUE THREAD

**Issue by hzhili** [DTStack/chunjun#219]
hive是否支持自定义分区名称和分区值,或者指定导入路径?

**Comment by kanata163** [comment]
你要读写hive表数据的话其实是可以使用hdfs插件的，hdfs插件这些都是支持的。

**Comment by geosmart** [comment]
@kanata163 借楼问个分区问题
flinkx如何支持动态分区，如spark中df.partitionBy("pt_d").write(hdfsPath)会自动按照pt_d字段生成分区

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
