### ISSUE TITLE
perjob模式下,配置flink-conf.yaml文件中的taskmanager.heap.size参数和taskmanager.numberOfTaskSlots参数无效,配置jobmanager.heap.size有效

### ISSUE THREAD

**Issue by fanliunian** [DTStack/chunjun#222]
![图片](https://user-images.githubusercontent.com/20262192/83004716-95384500-a042-11ea-84d2-dc6772f5382a.png)

**Comment by kanata163** [comment]
感谢反馈，下次更新时修复。
目前你可以在-confProp中设置taskmanager.slots:3来临时解决
`-confProp "{\"taskmanager.slots\":3}"`

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
