### ISSUE TITLE
在perjob模式下,并行度超过5的时候, 部分线程结束会先close connect, 从而导致后面的线程无法进行写入操作, 最终导致部分数据写入成功,部分写入失败

### ISSUE THREAD

**Issue by fanliunian** [DTStack/chunjun#223]
![图片](https://user-images.githubusercontent.com/20262192/83230944-3ba85580-a1bd-11ea-9728-ebfc0b9a8982.png)

**Comment by kanata163** [comment]
我分别使用5并行度和10并行度以perjob模式同步千万级的MySQL表，共跑了6次，均成功执行了。针对你这种情况，我们打算在这块添加数据源连通性的检测来规避，这将在下一次的发布中修复。
![image](https://user-images.githubusercontent.com/35188210/83721775-59b6ff80-a66e-11ea-8058-17cb13ba08fb.png)
![image](https://user-images.githubusercontent.com/35188210/83721810-6b98a280-a66e-11ea-87ac-31cf104abc77.png)

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
