### ISSUE TITLE
运行mysqlreader报错

### ISSUE THREAD

**Issue by lijianfeng6666526** [DTStack/chunjun#230]
![image](https://user-images.githubusercontent.com/60570042/84472966-d5422d80-acba-11ea-837d-8cb64a2d08be.png)

提交命令如下:
./bin/flinkx -mode local \
-job /home/flinkx-1.8_release/mysql_read.json \
-pluginRoot /home/flinkx-1.8_release/plugins \
-confProp "{\"flink.checkpoint.interval\":60000}"

json文件格式如下:
{
  "job": {
    "content": [
      {
        "reader": {
          "parameter": {
            "username": "root",
            "password": "root@123",
            "connection": [{
              "jdbcUrl": ["jdbc:mysql://vb01:3306/test?useUnicode=true&characterEncoding=utf8"],
              "table": ["t1"]
            }],
            "column": ["*"],
            "customSql": "select * from t1 where id >= 1",
            "where": "id < 100",
            "splitPk": "",
            "queryTimeOut": 1000,
            "requestAccumulatorInterval": 2
          },
          "name": "mysqlreader"
        },
        "writer": {
          "name": "streamwriter",
          "parameter": {
            "print": true
          }
        }
      }
    ],
    "setting": {
      "speed": {
        "channel": 1,
        "bytes": 0
      },
      "errorLimit": {
        "record": 100
      },
      "restore": {
        "maxRowNumForCheckpoint": 0,
        "isRestore": false,
        "restoreColumnName": "",
        "restoreColumnIndex": 0
      },
      "log" : {
        "isLogger": false,
        "level" : "debug",
        "path" : "",
        "pattern":""
      }
    }
  }
}

**请问什么原因？**

**Comment by kanata163** [comment]
首先检查`/home/flinkx-1.8_release/plugins`目录下是否包含common、flinkx-release_1.8.6.jar、mysqlreader、mysqlwriter文件及文件夹，若问题仍存在，则建议下载重新安装最新版本flinkx。

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
