### ISSUE TITLE
kafka认证问题

### ISSUE THREAD

**Issue by momisabuilder** [DTStack/chunjun#237]
你好，今天在测试kafka2mysql的时候发现一个影响程序执行的问题
当没有开启kerberos认证的时候，数据可以正常消费，程序也正确，当开启的时候，则数据不能正常消费，程序也抛出异常，我修改了源码后问题便得到解决，类 com.dtstack.flinkx.kafka11.reader.KafkaConsumer， 方法 public Client(Properties clientProps, List<String> topics, long pollTimeout, Kafka11InputFormat format) ，加入代码片段，System.setProperty("java.security.krb5.conf", "C:\\Users\\liuwenjie\\Desktop\\krb5.conf");System.setProperty("java.security.auth.login.config", "C:\\Users\\liuwenjie\\Desktop\\kafka_client_jaas.conf");System.setProperty("javax.security.auth.useSubjectCredsOnly", "false");

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
