### ISSUE TITLE
mysql同一个服务器不同的数据库相同的表同步的时候有问题

### ISSUE THREAD

**Issue by momisabuilder** [DTStack/chunjun#238]
你好，在大量的测试过程中我们发现，同一个关系型数据库服务器，不同的数据库，相同的表，同步的时候有个很大的bug，需要修改源码来解决

**Comment by lvyanquan** [comment]
需要给出更详细的说明，希望能把一些bug截图或者你认为要修改的源码放上来，我们可以更进一步地讨论。

**Comment by kanata163** [comment]
@momisabuilder 
啥BUG你倒是说一下啊

**Comment by momisabuilder** [comment]
异常信息：java.lang.IndexOutOfBoundsException: Index: 8, Size: 5，经分析调试：同一个数据库服务器不同的数据库下面存在相同的表引起的，程序在运算过程中会去元数据表-information_schema.`COLUMNS`中去查询字段信，源码中的查询条件没有数据库名字导致，把库名字也作为查询条件，问题便能得到解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kanata163"<notifications@github.com&gt;; 
发送时间: 2020年7月10日(星期五) 下午2:06
收件人: "DTStack/flinkx"<flinkx@noreply.github.com&gt;; 
抄送: "烦不烦 "<1518386192@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [DTStack/flinkx] mysql同一个服务器不同的数据库相同的表同步的时候有问题 (#238)





 
@momisabuilder
 啥BUG你倒是说一下啊

**Comment by lvyanquan** [comment]
程序里使用 "SELECT * FROM " + tableName + " LIMIT 0"获取待写入表的一条记录，然后根据ResultSetMetaData的getColumnTypeName()、getColumnName()获取元数据信息，这个查询不会读取到其他库的记录。如果你要读取和写入的表是在不同数据库下的同名表，请将use database 设置成写入的表所在的数据库。具体可以查看jdbcOutputFormat.analyzeTable()方法。
如果继续有问题，把你调试信息截图放上来。

**Comment by momisabuilder** [comment]
嗯嗯，好的&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lvyanquan"<notifications@github.com&gt;; 
发送时间: 2020年7月10日(星期五) 下午3:29
收件人: "DTStack/flinkx"<flinkx@noreply.github.com&gt;; 
抄送: "烦不烦 "<1518386192@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [DTStack/flinkx] mysql同一个服务器不同的数据库相同的表同步的时候有问题 (#238)





 
程序里使用 "SELECT * FROM " + tableName + " LIMIT 0"获取待写入表的一条记录，然后根据ResultSetMetaData的getColumnTypeName()、getColumnName()获取元数据信息，这个查询不会读取到其他库的记录。如果你要读取和写入的表是在不同数据库下的同名表，请将use database 设置成写入的表所在的数据库。具体可以查看jdbcOutputFormat.analyzeTable()方法。
 如果继续有问题，把你调试信息截图放上来。

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
