### ISSUE TITLE
gbase writer插件，update模式对于目标表为空表时数据写入异常！

### ISSUE THREAD

**Issue by meetexception** [DTStack/chunjun#240]
gbase writer插件
1. 目标表是空表的情况，使用update模式，运行后日志指标显示读写都正常。但数据并没有真正写入数据库。
2. 如果目标表不为空，使用update模式，是可以正常实现插入/更新操作。

updateKey已设置为gbase表的分布列。

**Comment by kanata163** [comment]
@meetexception 
是的，原因是在update模式中使用的是merge into语法，如：
```sql
MERGE INTO `kudu` T1 
USING 
	(
		select 1 `id`,1 `user_id`,1 `name` 
		from `kudu`  
		limit 1
	) T2 
ON 
	(T1.`id`=T2.`id`) 
WHEN MATCHED 
THEN 
	UPDATE SET `T1`.user_id=`T2`.user_id,`T1`.name=`T2`.name 
WHEN NOT MATCHED 
THEN 
	INSERT (`id`,`user_id`,`name`) VALUES (`T2`.`id`,`T2`.`user_id`,`T2`.`name`);
```
如果目标表为空，则在执行下面的SQL时，gbase数据库是不会返回任何值的。此时T2表为空，因此无任何数据写入。
```sql
select 1 id,1 user_id,1 name from kudu limit 1
```

如果你的目标表为空表，请不要使用update模式。

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
