### ISSUE TITLE
oracle 开启间隔轮询，不会把时间戳转换为时间格式， 导致出错

### ISSUE THREAD

**Issue by wgf515** [DTStack/chunjun#242]
/**
     * 构建时间边界字符串
     * @param location          边界位置(起始/结束)
     * @param incrementColType  增量字段类型
     * @return
     */
    @Override
    protected String getTimeStr(Long location, String incrementColType){
        String timeStr;
        Timestamp ts = new Timestamp(DbUtil.getMillis(location));
        ts.setNanos(DbUtil.getNanos(location));
        timeStr = DbUtil.getNanosTimeStr(ts.toString());

        if(ColumnType.TIMESTAMP.name().equals(incrementColType)){
            timeStr = String.format("TO_TIMESTAMP('%s','YYYY-MM-DD HH24:MI:SS:FF6')",timeStr);
        } else {
            timeStr = timeStr.substring(0, 19);
            timeStr = String.format("TO_DATE('%s','YYYY-MM-DD HH24:MI:SS')", timeStr);
        }

        return timeStr;
    }

polling 为true是， 没有执行上面代码，不会把long 类型时间戳， 转换为时间类型字符串

**Comment by kanata163** [comment]
@wgf515 
错误日志发一下

**Comment by wgf515** [comment]
时间太久了， 日志找不到了。您可以看一下OracleInputFormat.java 下面的getTimeStr方法只在非轮询情况下调用。

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
