### ISSUE TITLE
Es Writer能不能增加 开始前、后 执行curl命令，如开始前先 删除索引，完成后删除N天前的索引

### ISSUE THREAD

**Issue by javalover123** [DTStack/chunjun#250]

**Comment by kanata163** [comment]
你可以在`com.dtstack.flinkx.es.writer.EsOutputFormat`的`openInternal()`方法中增加开始前逻辑，`closeInternal()`方法中ES client关闭前增加结束逻辑，然后通过参数将你需要执行的逻辑传递进来。

**Comment by javalover123** [comment]
这是一个比较通用的需求吧，MySQL、clickhouse的output 现在都支持 开始前、成功后 执行的sql

**Comment by kanata163** [comment]
我们在下一版中增加这个功能

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
