### ISSUE TITLE
关于实时从oracle同步数据的问题

### ISSUE THREAD

**Issue by wangdabin1216** [DTStack/chunjun#252]
您好：
    想了解下目前实时从oracle同步的方案什么时候能开源，是否是ogg的数据进行同步？

**Comment by kanata163** [comment]
通过LogMiner进行的日志挖掘，不借助Ogg，目前遇到一些问题，开源时间不确定。

**Comment by yansheng105** [comment]
> 通过LogMiner进行的日志挖掘，不借助Ogg，目前遇到一些问题，开源时间不确定。

能否指教一下怎么在java中使用 logminer

**Comment by snycc15** [comment]
建议基于OGG来做实时同步或者基于ogg-kafka-flinkx，如此flinkx仅需要对kafka接收到的OGG格式进行解析，可最大化适配。

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
