### ISSUE TITLE
Hbase无法写入的问题

### ISSUE THREAD

**Issue by chenaiyuan** [DTStack/chunjun#256]
您好，在本地尝试写入hbase时会报错org.apache.hadoop.hbase.client.ZooKeeperRegistry - Can't retrieve clusterId from Zookeeper
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/hbaseid
我的json文件writer是：
"writer": {
        "name": "hbasewriter",
        "parameter": {
          "hbaseConfig": {
       "hbase.master.info.bindAddress": "",
       "hbase.client.rpc.codec": "",
       "hbase.zookeeper.property.clientPort": "",
       "hbase.rootdir": "",
       "hbase.cluster.distributed": "true",
       "hbase.zookeeper.quorum": "",
       "zookeeper.znode.parent": "/hbase",
       "hbase.security.authentication":"Kerberos",
       "hbase.security.authorization":true,
       "hbase.master.kerberos.principal":"",
       "useLocalFile": true,
       "hbase.rpc.protection":"authentication",
       "dfs.client.use.datanode.hostname":"true",
       "hbase.master.keytab.file":"D:\\tmp\\flinkx\\keytab\\user.keytab",
       "hbase.regionserver.keytab.file":"D:\\tmp\\flinkx\\keytab\\user.keytab",
       "principalFile": "D:\\tmp\\flinkx\\keytab\\user.keytab",
       "hbase.regionserver.kerberos.principal":"",
       "java.security.krb5.conf":"D:\\tmp\\flinkx\\keytab\\krb5.conf"
      },
      "rowkeyColumn": "$(base_info:id)",
          "table": "user",
      "column": [
        {
          "name": "base_info:id",
          "type": "bigint"
        },
        {
          "name": "base_info:name",
          "type": "string"
        },
        {
          "name": "base_info:location",
          "type": "string"
        },
        {
          "name": "base_info:duration",
          "type": "int"
        },
        {
          "name": "base_info:time",
          "type": "timestamp"
        }
      ]
        }
      }
然后线上不会报这个错，但是结果和本地一样，就说有两条写入不了——都是没写入：
numWrite                  |  2
last_write_num_0          |  0
conversionErrors          |  0
writeDuration             |  22813
duplicateErrors           |  0
numRead                   |  2
snapshotWrite             |  2
otherErrors               |  0
readDuration              |  2800
byteRead                  |  74
last_write_location_0     |  0
byteWrite                 |  74
nullErrors                |  0
nErrors                   |  2

数据不会有什么问题，因为这个从mysql读出来写入hdfs和hive都成功了已经，网上尝试的方法大多数都试过了，只剩一个让配GC的没有尝试，但是感觉应该不是GC的原因，您看是我config少配参数了，还是怎么？

**Comment by kanata163** [comment]
nErrors | 2，报脏数据了，关闭脏数据配置，看下具体报什么错

**Comment by chenaiyuan** [comment]
就还是报Unable to reconnect to ZooKeeper service, session **** has expired, closing socket connection。是不是哪点儿还需要一个什么关键的zk配置啊，现在hbaseConfig里我关于zk的配置有：zookeeper.session.timeout，hbase.zookeeper.property.clientPort，hbase.zookeeper.quorum，zookeeper.znode.parent
。

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
