### ISSUE TITLE
hbase无法写入的问题

### ISSUE THREAD

**Issue by chenaiyuan** [DTStack/chunjun#257]
就还是报Unable to reconnect to ZooKeeper service, session **** has expired, closing socket connection。是不是哪点儿还需要一个什么关键的zk配置啊，现在hbaseConfig里我关于zk的配置有：zookeeper.session.timeout，hbase.zookeeper.property.clientPort，hbase.zookeeper.quorum，zookeeper.znode.parent 

网上有的说是要修改hbase-env.sh中的HBASE_OPTS参数（网上说这个报错和GC有关）。我感觉关系不大，您感觉呢？

最主要的还是org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired这个原因吧

在解决的同时，您能否给一个跑通过的json的domo。

**Comment by chenaiyuan** [comment]
@kanata163

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
