### ISSUE TITLE
binlog->mysql单表无法同步

### ISSUE THREAD

**Issue by fanliunian** [DTStack/chunjun#261]
binlog-kafka可以成功, binlog->mysql中binlog会读取到数据,可是mysql没有数据同步,binlog读取的数据会增加before,after字段,导致写入失败
![图片](https://user-images.githubusercontent.com/20262192/89758800-3fd8e380-db1b-11ea-86de-89100b96c476.png)

![图片](https://user-images.githubusercontent.com/20262192/89748563-65072b00-daf6-11ea-9bb4-815f07a641dc.png)

![图片](https://user-images.githubusercontent.com/20262192/89746394-fcb34c00-daeb-11ea-800e-da457e0fc2e6.png)

**Comment by kanata163** [comment]
@fanliunian 
确实目前是这样的，binlog采集到的是日志数据，并不是数据库的真实数据。如果你需要的是日志数据，那么需要在数据库中创建对应字段的表

**Comment by zhaoysg** [comment]
@fanliunian  您经过修改是否可以使用

**Comment by lugela** [comment]
在使用idea测试binglog同步到mysql过程中，我这边是数据不会调用mysql write相关的方法，不知道你这边是否有相关问题

**Comment by james9203** [comment]
@fanliunian   这个问题你解决了吗

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
