### ISSUE TITLE
kafka写入数据到hive，为什么kafka的消费监控是平缓的，如果是checkpoint提交，监控应该是锯齿形的，齐平的监控是不是提交的作业中间发生重启，就会丢失数据

### ISSUE THREAD

**Issue by MKdarren** [DTStack/chunjun#285]
当前我们live环境使用flinkx的kafka->hive的功能，发现消费kafka的监控是平缓的，而写hive的机制不应该是checkpoint提交这段期间的数据吗，这是不是代表重启job，这部分数据没有写文件，这期间的kafka数据就会丢失数据了？

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
