### ISSUE TITLE
restapireader像是一个半成品，有能跑通的demo吗？

### ISSUE THREAD

**Issue by archichen** [DTStack/chunjun#288]

**Comment by yanghuaiGit** [comment]
https://github.com/DTStack/flinkx/blob/1.10_release/docs/realTime/reader/restapireader.md

**Comment by yanghuaiGit** [comment]
可以拉下最新代码 更新了一版

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
