### ISSUE TITLE
pgwal的local模式运行存在bug

### ISSUE THREAD

**Issue by atguigu-yrw** [DTStack/chunjun#289]
使用local模式运行的时候，启动不了。
![4177983435_26325749126_1606276116438_855AEE5F-4E46-4bbd-93E3-F20BEA0B8488](https://user-images.githubusercontent.com/70558842/100235676-addcd580-2f67-11eb-9428-dd811fe3690a.png)

**Comment by liuxx532** [comment]
排查了一天 原来是个 bug，看前面已经提过这个 issue， 目前还没修复

https://github.com/DTStack/flinkx/issues/244

**Comment by shejiewei** [comment]
我已经提出修改意见了,你照着改就可以了

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
