### ISSUE TITLE
OdpsInputFormat的nextRecordInternal方法，类型转换的问题

### ISSUE THREAD

**Issue by xwuyuan521** [DTStack/chunjun#295]
通过odps的sdk获取的数据，
                Object val = record.get(i);
这个放回的值有很多中可能，而我们只处理了String类型的。比如，如果返回的是Date类型的话，
                if (val instanceof String) {
                    val = StringUtil.string2col(String.valueOf(val), metaColumn.getType(), metaColumn.getTimeFormat());
                }
这个地方是不可能会执行的。当遇到这种情况的额话，就没法做时间的format了。
所以应当加上：
                if (val instanceof Date && metaColumn.getTimeFormat() != null) {
                    SimpleDateFormat timeFormat = metaColumn.getTimeFormat();
                    val = timeFormat.format(val);
                }

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
