### ISSUE TITLE
除了数据同步功能外，是否可以支持插件方式的Transform功能，即ETL

### ISSUE THREAD

**Issue by xunchangguo** [DTStack/chunjun#298]
现有实现只有 source->skin，是否可以支持 source->  Transform（map+fliter）-> skin 这种模式。从而满足大部分的ETL场景。

**Comment by zhiyuan192shine** [comment]
同问，需要做一些处理，比如数据脱敏之类的

**Comment by michielzh** [comment]
同问，后续是否有这方面的规划

**Comment by cjjxfli** [comment]
我们在干这个事，拉了一个分支。不过transform对性能有影响，主要还是看场景

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
