### ISSUE TITLE
mysql数据源采用mod方式读取，其实并没有利用索引机制

### ISSUE THREAD

**Issue by coolsummery** [DTStack/chunjun#304]
https://github.com/DTStack/flinkx/issues/143#issue-540697296

**Comment by kanata163** [comment]
是的，函数运算其实没法走索引的，后面我打算将这个优化掉

**Comment by coolsummery** [comment]
请问你们已经具备具体的优化思路了吗？

**Comment by coolsummery** [comment]
> 是的，函数运算其实没法走索引的，后面我们打算将这个优化掉

请问你们已经有具体的优化思路了吗？

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
