### ISSUE TITLE
DistributedJdbcInputFormatBuilder中对channel数量的限制其实没有意义了？

### ISSUE THREAD

**Issue by coolsummery** [DTStack/chunjun#306]
DistributedJdbcInputFormat在没有设置splitKey的情况下，会实行单表单线程读取模式，个人理解这里是可以进行并行读取的。
所以DistributedJdbcInputFormatBuilder在splitKey没有设置的判断中，应该去掉对numPartitions数量的限制，代码如下：

if (StringUtils.isEmpty(format.splitKey) && format.numPartitions > 1){
    throw new IllegalArgumentException("Must specify the split column when the channel is greater than 1");
}

不知理解是否正确。

**Comment by kanata163** [comment]
@coolsummery 
根据com.dtstack.flinkx.rdb.inputformat.DistributedJdbcInputFormat#createInputSplitsInternal()方法中的逻辑，其实上面的判断是有问题的，应该删掉。

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
