### ISSUE TITLE
当column为*号时,MysqlInputFormat（65行）报IndexOutOfBoundsException异常

### ISSUE THREAD

**Issue by GdCwh** [DTStack/chunjun#311]
经过排查发现，当column为*号时，DbUtil的analyzeColumnType方法，columnTypeList存储了null的列表，会导致读取数据异常
![image](https://user-images.githubusercontent.com/49760358/104687020-583bd280-5739-11eb-8678-b0ed5f8a868f.png)

**Comment by kanata163** [comment]
@GdCwh 
拉一下最新代码

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
