### ISSUE TITLE
源代码下载下来编译不通过

### ISSUE THREAD

**Issue by carvinhappy** [DTStack/chunjun#318]
将源代码下载到本地，执行mvn clean package -Dmaven.test.skip=true， 编译不通过，发现缺少zookeeper，commons-net，jsch，hadoop-auth四个包，增加后可以编译通过。1.10_release,1.11_release都是一样的。

**Comment by kanata163** [comment]
编译不通过可能是你maven有什么问题，检查一下是不是缺这几个相应版本的包

**Comment by carvinhappy** [comment]
我用的maven信息如下：
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/xxxxxx/maven/apache-maven-3.6.3
Java version: 1.8.0_272, vendor: GraalVM Community, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java8-20.3.0/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"

我看flinkx-core的pom文件中，并未有zookeeper、commons-net、jsch、hadoop-auth的依赖，有curator的依赖，不过是test scope，在编译过程中，ZkHelper、TelnetUtil、SftpHandler、KerberosUtil四个类会报错。

**Comment by kanata163** [comment]
![image](https://user-images.githubusercontent.com/35188210/105936822-548c4200-608f-11eb-896a-ae74746d010e.png)

maven有依赖传递，你maven仓库估计是没有这些个版本的包

**Comment by carvinhappy** [comment]
嗯嗯，好的， 谢谢！我又重新下载了1.10_release的代码，可以编译通过了；我前面是用1.11_release的代码编译的，还是不行，我看把shaded那个包exclusion了。

**Comment by carvinhappy** [comment]
不好意思， 再补一个，1.10_release在命令行执行mvn clean package -Dmaven.test.skip=true, 可以编译成功。 但是在idea中 ZkHelperTest还是编译不过去，缺少CuratorFramework，我看了本地是有curator-framework这个包的。

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
