### ISSUE TITLE
binlog是否支持断点续传

### ISSUE THREAD

**Issue by PONYLEE** [DTStack/chunjun#320]
目前MySQL binlog是否支持断点续传，如果支持烦请提供一下示例

**Comment by zoudaokoulife** [comment]
支持的，实时采集都是基于flink state 来保存offset信息的。恢复的时候基于指定的checkpoint 的位置来恢复。具体的例子我们整理好文档会挂在这个问题下的。

**Comment by yanghuaiGit** [comment]
https://www.yuque.com/alipaypokwr69ggn/czbhl8/rnrhgg
这个文档说明了断点续传的使用步骤以及如何模拟测试，另外可以进入flinkx的交流群，群里有直播回放专门有一节说明了断点续传的原理和使用，群号是30537511

**Comment by luobo-te** [comment]
> https://www.yuque.com/alipaypokwr69ggn/czbhl8/rnrhgg
> 这个文档说明了断点续传的使用步骤以及如何模拟测试，另外可以进入flinkx的交流群，群里有直播回放专门有一节说明了断点续传的原理和使用，群号是30537511

checkpoint 必须配置在flink-conf.xml中吗？  能配置在-confProp里面吗  ？

**Comment by geosmart** [comment]
flinkx-1.12没有-s参数指定checkpoint的恢复路径，现在是如何恢复chekpoint？
