### ISSUE TITLE
binlog ts是什么时间戳

### ISSUE THREAD

**Issue by PONYLEE** [DTStack/chunjun#321]
{schema=db01, after_name=aa, after_age=15, after_id=1, type=INSERT, table=t3, ts=6759757251344470016}
怎么还有减小呢，这个应该是bug吧
![image](https://user-images.githubusercontent.com/15049354/105989576-4a446500-60dc-11eb-9a7f-56cfece15930.png)

**Comment by yanghuaiGit** [comment]
![image](https://user-images.githubusercontent.com/38883656/109638856-78104400-7b89-11eb-8b28-169b7327f8ec.png)
https://github.com/DTStack/flinkx/blob/1.10_release/docs/realTime/reader/binlogreader.md

**Comment by yanghuaiGit** [comment]
可以看下对应文档，你可以按照上面代码将你的ts解析出来看下时间是不是变小了

**Comment by geosmart** [comment]
看代码里面是snowflake随机生成的id

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
