### ISSUE TITLE
MySQLreader全量同步表时支持全表扫描只更新有更新的记录吗

### ISSUE THREAD

**Issue by cjjxfli** [DTStack/chunjun#322]
定时全量同步，会遇到主键冲突或者不冲突导致数据重复采集

**Comment by lvyanquan** [comment]
表数据更新是指更新了之前存在过的主键对应的数据吗，这个不支持。只支持主键递增的更新。

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
