### ISSUE TITLE
希望支持TDengine

### ISSUE THREAD

**Issue by cmdares** [DTStack/chunjun#331]
根据个人目前考察来看，TDengine会成为物联网数据库的领先厂商。希望FlinkX能够优先考虑支持，这个数据库的对接。

**Comment by kanata163** [comment]
我们后续会考虑支持该数据库类型的，不过需要一定时间，你也可以参照[开发文档](https://github.com/DTStack/flinkx/blob/1.10_release/docs/contribution.md)自己开发一个这样的插件

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
