### ISSUE TITLE
批量场景同步

### ISSUE THREAD

**Issue by cmdares** [DTStack/chunjun#332]
一个简单的实时ETL同步场景：
将mysql A库中的 T 开头、F开头的所有表（约几百个），同步到 postgresql B库中，同时在B库的每个表增加一个入库时间戳字段（insert或Update时候填写pg的当前系统时间）
首先需要开启并发，做所有表的全量同步，之后使用binlog实时同步，任何一张表全量同步完成后，即刻消费binglog同步增量。
请教，在FlinkX平台上该如何简洁、合理的完成这个批量同步的需求。
建议官方给出一个有代表性的实操文章，以便在自己的环境下快速实践。
注：以往使用datax完成，可以简单实现高并发的全量导入，增量通过主键和时间戳配合的upsert方式进行同步，每次完成自行记录时间戳，分配很多任务单独进行管理，较为繁琐，性能和时效性也不好。现在考虑使用flinkx升级已有系统架构。
感谢！

**Comment by cjjxfli** [comment]
这种场景需要增加数据处理步骤。目前在框架只支持reader和writer情况下，个人感觉有点复杂。可以自定义一个reader去实现。

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
