### ISSUE TITLE
pgwal实时同步设置日志读取位点无效

### ISSUE THREAD

**Issue by jiangyifu** [DTStack/chunjun#347]
在job中设置LSN，代码中赋值
![image](https://user-images.githubusercontent.com/40878518/110312457-1005a600-8040-11eb-91c6-98acdde8c85c.png)
但是拉取日志没有从此位置开始，每次都是最新位置读取

**Comment by tonybobam** [comment]
这边的确有bug, 如果指定lsn开始采集的话，必须自己手动配置已有的logic slot，且slot的restart_lsn必须早于配置的lsn

**Comment by kanata163** [comment]
大白话：你要使用指定起点开始采集，就不能使用临时创建的复制槽，而是使用已经创建好的复制槽(脚本里面设置slotName参数)，然后你指定的采集起点要比这个已经创建的复制槽的开始起点要大，不然的话是采集不到这个复制槽开始起点之前的数据。

**Comment by kanata163** [comment]
一般是开发测试阶段使用临时复制槽比较多，任务结束，临时复制槽就自动删除了，不会占用资源。和数据库中存储的复制槽的区别主要就是临时复制槽任务结束会自动删除，其他的区别可能不大，详细情况还是询问这方面的DBA比较好。

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
