### ISSUE TITLE
flinkx 编译失败了,有人有编译好的 tar包吗??

### ISSUE THREAD

**Issue by ithjz** [DTStack/chunjun#355]
flinkx 编译失败了,有人有编译好的 tar包吗??

Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project flinkx-core: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]

**Comment by yugang1987** [comment]
这个问题我也碰到了,这个问题是maven版本冲突导致的,需要重新设置idea里的maven,然后reimport

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
