### ISSUE TITLE
支持一个表同步到分表吗

### ISSUE THREAD

**Issue by sdcuike** [DTStack/chunjun#371]
支持一个表同步到分表吗

**Comment by zoudaokoulife** [comment]
@sdcuike 现在不支持。可以一起来开发。

**Comment by cjjxfli** [comment]
这种同步到分表，需要指定分表逻辑

**Comment by sdcuike** [comment]
> 这种同步到分表，需要指定分表逻辑

是的，根据哪个字段，分表算法，得配置

**Comment by sdcuike** [comment]
@cjjxfli  是的，根据哪个字段，分表算法，得配置

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
