### ISSUE TITLE
flinkx 1.11 windows情况下idea远程提交job会出错，插件找不到类（内附解决方法）

### ISSUE THREAD

**Issue by 343701675** [DTStack/chunjun#386]
### **原代码：**
![image](https://user-images.githubusercontent.com/11263024/114121678-5c832080-9921-11eb-85d3-19bf323fd3d1.png)

### **会导致插件上传文件类型为application/octet-stream，截图如下：**
![image](https://user-images.githubusercontent.com/11263024/114121910-d4e9e180-9921-11eb-80da-c0134c4ada15.png)

### **正确的jar类型应该为application/java-archive，所以我们将代码改为**
![image](https://user-images.githubusercontent.com/11263024/114121650-4f663180-9921-11eb-8f5b-2fe49c6773de.png)

### **这样我们.bin类型还是application/octet-stream，jar类型就都为application/java-archive了，在windows情况下idea远程提交job就正常了，截图如下：**
![image](https://user-images.githubusercontent.com/11263024/114121563-26de3780-9921-11eb-9526-a5ed1fd7c89a.png)

**Comment by 343701675** [comment]
此问题，文件路径都正确，且PackagedProgramBuilder没有对应的方法，会比较难找

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
