### ISSUE TITLE
install_jars.sh 在 bin目录之外不能正确解析 jars路径

### ISSUE THREAD

**Issue by Eli-Young** [DTStack/chunjun#391]
您好,我在第一次使用flinkx 时需要安装 jars/*.jar 当我在flinkx 目录下执行 bin/install_jars.sh 时 路径被错误解析到 flinkx/../jars

**Comment by TyrealBM** [comment]
希望能在脚本开头添加
SCRIPT_BIN_DIR=$(dirname ${BASH_SOURCE-$0})
cd "${SCRIPT_BIN_DIR}" || exit

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
