### ISSUE TITLE
JdbcOutputFormat的checkpoint问题

### ISSUE THREAD

**Issue by Altman-yao** [DTStack/chunjun#393]
目前JdbcOuputFormat的状态保存是每个批次（batchSize）才更新一次，而Source端是每有一条新数据就能更新原来的状态，如果读取的数据量没有达到batchSiz而checkpoint时间已经到了，此时Source记录的状态位置会后移，而Sink端的数据还没有写出去，如果此时宕机，重启任务，原来的内存没有写出去的数据会丢失。

**Comment by yanghuaiGit** [comment]
jdbcoutputformat在checkpoint时，会判断batchsize是否为空，如果不为空 会先将batchsize里数据写入 再更新状态

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
