### ISSUE TITLE
kafkareader设置mode为earliest-offset无效

### ISSUE THREAD

**Issue by tracy100** [DTStack/chunjun#394]
**KafkaUtil类中设置枚举EARLIEST时没有break，导致auto.offset.reset一直为latest模式**
       switch (mode){
            case EARLIEST:
                props.put("auto.offset.reset", "earliest");
            case LATEST:
                props.put("auto.offset.reset", "latest");
        }

**Comment by FlechazoW** [comment]
PR merged.
