### ISSUE TITLE
GreenPlum  copy 模式怎麽查看流速？

### ISSUE THREAD

**Issue by jinguangyang** [DTStack/chunjun#400]
GreenPlum  copy 模式怎麽查看流速？怎麽可以把數據抄寫速度打到日志上

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.

**Comment by jinguangyang** [comment]
您发给我的信件已经收到。This is an automatic reply, confirming that your e-mail was received.Thank you！
