### ISSUE TITLE
关于自定义入参

### ISSUE THREAD

**Issue by ghost** [DTStack/chunjun#404]
![image](https://user-images.githubusercontent.com/49225384/119432429-ea3a9400-bd46-11eb-8ef9-c2aff27fec24.png)

请问这里的自定义入参作用是什么? 是以占位符替换脚本中的变量, 还是可以将自定义的入参向后面流程进行传递, 从输出源获取到?

**Comment by kanata163** [comment]
以占位符替换脚本中的变量，详见[能否加一个 json 文件中支持变量的功能](https://github.com/DTStack/flinkx/issues/149)

**Comment by yanfei815** [comment]
![image](https://user-images.githubusercontent.com/49225384/119588049-8e354580-be02-11eb-8537-c6dc14a844b9.png)
豆哥，我想通过执行脚本或者JSON配置文件定义一个变量，writer数据之后接收到这个变量做后续业务上的处理，请问目前flinkx能否支持这个功能？

**Comment by kanata163** [comment]
![Uploading image.png…]()

**Comment by kanata163** [comment]
![image](https://user-images.githubusercontent.com/35188210/119590330-23d2d400-be07-11eb-8611-afc4e8cbc9b2.png)

**Comment by yanfei815** [comment]
![image](https://user-images.githubusercontent.com/49225384/119592385-f851e880-be0a-11eb-9ee6-85d8ff3aaf74.png)

豆哥，按照你的提示添加了column并设了value值，但是采集到的数据并没有看到我定义的这个字段，请问是在reader配置定义这个参数还是在writer配置中定义？

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
