### ISSUE TITLE
flink任务执行完成后，flink web界面上的日志消失了，如何能在任务执行完成后任然能看日志？

### ISSUE THREAD

**Issue by xingdong123** [DTStack/chunjun#407]
history servers上的指标在，但是详细输出日志也会消失，看不了
Task Managers列表里面是空能

**Comment by kanata163** [comment]
resourcemanager.taskmanager-timeout 参数设置成一天，每天把session重启一下，由yarn把日志归档，然后通过yarn log收集日志

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
