### ISSUE TITLE
如何与调度器集成，任务执行完 命令行不不退出

### ISSUE THREAD

**Issue by lordk911** [DTStack/chunjun#414]
版本flinkx-1.11_release，yarn 或 yarnPer 模式，通过flinkx提交任务后，命令行不会退出，那么要如何与调度程序去集成呢？

**Comment by qq712679031** [comment]
在脚本文件最后 加入 exit;

**Comment by qq712679031** [comment]
在脚本文件最后 加入 exit;

**Comment by wushuoyouting** [comment]
或者设置调度任务的超时时间

**Comment by qq712679031** [comment]
修改一下 bin目录下的flinkx 的脚本  把nohup 去掉 然后自己监控日志状态就行了

**Comment by lordk911** [comment]
jobType sync/sql 可以解决这个问题吗？sql 类型的执行完会自动退出？新版还没测

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
