### ISSUE TITLE
Error:(28, 26) java: 程序包com.kingbase8.copy不存在

### ISSUE THREAD

**Issue by wuyascnu** [DTStack/chunjun#417]
这个包要怎么导入啊

**Comment by lordk911** [comment]
https://github.com/DTStack/flinkx/blob/1.10_release/docs/quickstart.md

![image](https://user-images.githubusercontent.com/19989300/121317087-8adea580-c93c-11eb-954c-841cf53fc8b2.png)

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
