### ISSUE TITLE
在同步sqlserver到kafka，启动项目没有办法拉取存量，只能拉取实时增量，要拉取存量（全量）+实时增量怎么解决

### ISSUE THREAD

**Issue by wuyascnu** [DTStack/chunjun#422]
在同步sqlserver到kafka，启动项目没有办法拉取存量，只能拉取实时增量，要拉取存量（全量）+实时增量怎么解决
比如：我的sqlserver表存量数据sqlserverCDC：{id:1, name: tom, age:20 }，此时启动项目，kafka中不会同步此条数据，如果新增提交实时数据{id:2, name: mike, age:28}，则会实时同步此条数据到kafka，如果我要同步原来的存量{id:1, name: tom, age:20 } 该怎么做？

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
