### ISSUE TITLE
编译时候出错，总是卡在这步[INFO] FlinkX : Connectors : SqlServer CDC ................ FAILURE [  0.441 s]

### ISSUE THREAD

**Issue by jinyan2049** [DTStack/chunjun#438]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project flinkx-connector-sqlserve                      rcdc: Compilation failure: Compilation failure:

求解决方案

**Comment by jinyan2049** [comment]
解决了，pom.xml文件下，注释掉这行

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
