### ISSUE TITLE
有计划什么时候支持数据湖组件吗？

### ISSUE THREAD

**Issue by dataHunterAssassi** [DTStack/chunjun#440]
请问下有计划什么时候支持数据湖组件吗？例如Apache Hudi、Apache Iceberg和Delta Lake。

**Comment by etcxy** [comment]
iceberg已经支持了，hudi据说在路上了，Delta Lake还没消息

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
