### ISSUE TITLE
from Kafka to Hive

### ISSUE THREAD

**Issue by besturn20at** [DTStack/chunjun#441]
我尝试用flinx 1.10 读kafka数据到hive，看日志没数据已经从kafka读出，并且写入了hive， 但是在hive中却查不到数据，以下是我的配置文件

15:50:05.011 [Sink: hivewriter (1/1)] DEBUG org.apache.thrift.transport.TSaslTransport - writing data length: 71
15:50:05.187 [Sink: hivewriter (1/1)] DEBUG org.apache.thrift.transport.TSaslTransport - writing data length: 128
15:50:05.219 [Sink: hivewriter (1/1)] DEBUG org.apache.thrift.transport.TSaslTransport - writing data length: 100
15:50:05.226 [Sink: hivewriter (1/1)] DEBUG org.apache.thrift.transport.TSaslTransport - writing data length: 96
15:50:05.230 [Sink: hivewriter (1/1)] DEBUG org.apache.thrift.transport.TSaslTransport - writing data length: 283
15:50:05.244 [Sink: hivewriter (1/1)] DEBUG org.apache.thrift.transport.TSaslTransport - writing data length: 100
15:50:05.254 [Sink: hivewriter (1/1)] DEBUG org.apache.thrift.transport.TSaslTransport - writing data length: 96
15:50:05.255 [Sink: hivewriter (1/1)] DEBUG org.apache.thrift.transport.TSaslTransport - writing data length: 134
15:50:05.306 [Sink: hivewriter (1/1)] DEBUG org.apache.thrift.transport.TSaslTransport - writing data length: 100

{
  "job": {
    "content": [
      {
        "reader" : {
          "parameter" : {
            "topic" : "flinkx",
            "mode": "specific-offsets",
            "offset": "partition:0,offset:0",
            "codec": "text",
            "consumerSettings" : {
              "bootstrap.servers" : "localhost:19092",
              "client.id" : "consumer-19"
            },
            "column": ["message"]
          },
          "name" : "kafkareader"
        },
        "writer": {
          "parameter" : {
            "jdbcUrl" : "jdbc:hive2://localhost:10000/flinkx",
            "username" : "root",
            "password" : "xxx",
            "fileType" : "text",
            "fieldDelimiter" : "\u0001",
            "writeMode" : "overwrite",
            "compress" : "",
            "charsetName" : "UTF-8",
            "maxFileSize" : 1073741824,
            "tablesColumn" : "{\"kafka_table\":[{\"part\":false,\"comment\":\"\",\"type\":\"string\",\"key\":\"message\"}]}",
            "defaultFS" : "hdfs://xxxx:9000"
          },
          "name" : "hivewriter"
        }
      }
    ],
    "setting": {
      "restore": {
        "isRestore": true,
        "isStream": true
      },
      "speed": {
        "readerChannel": 3,
        "writerChannel": 1
      }
    }
  }
}

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
