### ISSUE TITLE
flinkx-1.12-beta 抛出 ClassNotFoundException: com.dtstack.flinkx.connector.elasticsearch6.table.Elasticsearch6DynamicTableFactory

### ISSUE THREAD

**Issue by JavaPentesters** [DTStack/chunjun#449]
`CREATE TABLE es6_source
(
   fpbz varchar
  , fpdm varchar
  , fphm varchar
  , fplb varchar
  , fpztdm varchar
  ) WITH (
    'connector' ='elasticsearch6-x',
    'hosts' ='10.3.3.3:9200',
    'index' ='sss',
    'document-type' ='_doc',
    'username' ='xx',
    'password' ='xx');

CREATE TABLE es6_sink
(
   fpbz varchar
  , fpdm varchar
  , fphm varchar
  , fplb varchar
  , fpztdm varchar
  ) WITH (
    'connector' ='elasticsearch6-x',
    'hosts' ='10.2.2.2:9200',
    'index' ='end',
    'document-type' = '_doc',
    'username' ='xx',
    'password' ='xx');

INSERT INTO es6_sink
SELECT *
FROM es6_source;`

前面两条创建表的SQL语句执行成功，执行到第三条INSERT 语句时抛出ClassNotFoundException: com.dtstack.flinkx.connector.elasticsearch6.table.Elasticsearch6DynamicTableFactory
代码中也未搜索到到该类，该类是更具一定条件动态生成？比如 根据connector' ='elasticsearch6-x 生成对接的类型？

![0F0507B6-C57D-4189-931A-2C50F597A19B](https://user-images.githubusercontent.com/25720065/125094509-e780dc00-e105-11eb-9104-9d217db4791e.png)
![71B6EA35-F30C-4A23-9DA2-036294CA2FBF](https://user-images.githubusercontent.com/25720065/125094541-ed76bd00-e105-11eb-8b12-492bf5da3a2c.png)

**Comment by HiLany** [comment]
https://github.com/DTStack/flinkx/pull/452

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
