### ISSUE TITLE
SQL方式从 es 读取记录 GenericRowData#genericRowData没有判空

### ISSUE THREAD

**Issue by JavaPentesters** [DTStack/chunjun#451]
![image](https://user-images.githubusercontent.com/25720065/125224871-ed8edc80-e300-11eb-9776-18e4c497c8bf.png)

ES 定义的mapping 索引字段多于 table source 定义的字段

`CREATE TABLE es6_source
(
   fpbz varchar
  , fpdm varchar
  , fphm varchar
  , fplb varchar
  , fpztdm varchar
  ) WITH (
    'connector' ='elasticsearch6-x',
    'hosts' ='10.22.22.14:9200',
    'index' ='start',
    'document-type' ='_doc',
    'username' ='xxxx',
    'password' ='xxx');

CREATE TABLE es6_sink
(
   fpbz varchar
  , fpdm varchar
  , fphm varchar
  , fplb varchar
  , fpztdm varchar
  ) WITH (
    'connector' ='elasticsearch6-x',
    'hosts' ='10.22.22.14:9200',
    'index' ='end',
    'document-type' = '_doc',
    'username' ='xxx',
    'password' ='xxx');

INSERT INTO es6_sink SELECT * FROM es6_source;`

**Comment by cjjxfli** [comment]
最后的处理方式是把入参的null移除解决的？

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
