### ISSUE TITLE
mysql jdbcUrl如果参数中带/，会导致数据不同步

### ISSUE THREAD

**Issue by 1069355234** [DTStack/chunjun#459]
看源码发现，会根据/去截取jdbcUrl以获取数据库名，这种方式遇到参数带/的时候会出问题
`public static String getDataBaseByUrl(String jdbcUrl) {`
       ` int idx = jdbcUrl.lastIndexOf('?');`
        `if (idx != -1) {`
           ` return StringUtils.substring(jdbcUrl, jdbcUrl.lastIndexOf('/') + 1, idx);`
        `} else {`
            `return StringUtils.substring(jdbcUrl, jdbcUrl.lastIndexOf('/') + 1);`
        `}`
    `}`

**Comment by simenliuxing** [comment]
能提供下脚本吗？不同步是会抱错吗？

**Comment by 1069355234** [comment]
> 能提供下脚本吗？不同步是会抱错吗？
不同步不会报错，只是sink中无消息，出问题的jdbcUrl如下：因为url参数中有/字符
jdbcUrl:mysql://xxx.xxx.xxx.xxx:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
