### ISSUE TITLE
请问如果是阿里云这种全托管的flink环境，我怎么使用FLinkX

### ISSUE THREAD

**Issue by vleyong** [DTStack/chunjun#462]
是直接导入这次依赖的jar包，然后直接些flinksql。还是支持在idea上开发，然后条件上传jar包，跑作业？

**Comment by wuyascnu** [comment]
上传到同一个环境啊

**Comment by vleyong** [comment]
> 上传到同一个环境啊

这个环境我是不能够安装任何东西的，也不能配置任何东西

**Comment by wuyascnu** [comment]
有权限访问这个环境的flink目录吗？可以把flinkx部署到另外一个环境，指向flink conf目录和lib目录试试

**Comment by cjjxfli** [comment]
把jar包丢到挂载盘里去，配置下加载路径

**Comment by vleyong** [comment]
> 有权限访问这个环境的flink目录吗？可以把flinkx部署到另外一个环境，指向flink conf目录和lib目录试试

就是不能，我只有一个控制台

**Comment by vleyong** [comment]
> 把jar包丢到挂载盘里去，配置下加载路径

你说的挂载盘是指全托管的环境把

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
