### ISSUE TITLE
local模式下的savepoint

### ISSUE THREAD

**Issue by 1069355234** [DTStack/chunjun#465]
local模式，可以通过-s参数指定savepoint或checkpoint路径，是不是不好在程序停止的时候生成savepoint？

**Comment by cjjxfli** [comment]
savepoint

**Comment by cjjxfli** [comment]
savepoint是手动触发的，什么场景需要用到savepoint呢？

**Comment by geosmart** [comment]
同问！
这个｀-s｀参数如果指定了，是会去读取指定的flink的savePoint元数据恢复任务，

任务异常中断，然后重启的时候不是应该自动读取最后一个savePoint继续执行的吗？
什么情况需要要手动指定？

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
