### ISSUE TITLE
1.12_beta版 hive sql sink的with配置部分 示例并没有配置parallelism导致异常

### ISSUE THREAD

**Issue by huanzui** [DTStack/chunjun#466]
**Describe the bug**
1.12_beta版 hive sql sink的with配置部分 示例并没有配置parallelism，导致启动后报HiveOutputFormatBuilder checkFormat 获取不到parallelism的null异常 format.getConfig().getParallelism()

在里面配置个 'sink.parallelism' = '1'就可 以，示例并不完整

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
