### ISSUE TITLE
示例1.12_beta版 mode yarn-session模式下提交jobType sync，若不是默认队列，则需要指定-queue

### ISSUE THREAD

**Issue by huanzui** [DTStack/chunjun#467]
1.12_beta版 mode yarn-session模式下提交jobType sync，若不是默认队列，则需要指定-queue ，示例中未给出，导致YarnSessionClusterClientHelper中 if(!report.getQueue().equals(launcherOptions.getQueue())) {} 这段 直接跳出，找不到yarn集群，默认queue为default

**Comment by kanata163** [comment]
queue不是default需要自行修改

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
