### ISSUE TITLE
oracle logminer Rollback 

### ISSUE THREAD

**Issue by houxi1234** [DTStack/chunjun#468]
1.10版本对delete的事务回滚进行了处理，在1.11中取消了事务回滚处理逻辑，请问是基于什么样的考虑？
1.10版本update和insert事务回滚之后，查询出的sqlLog如下图所示，导致下游处理数据后，更新所有字段
![image](https://user-images.githubusercontent.com/35021350/127301777-c909a8a3-3829-49d5-80f7-b8f78b7ef766.png)

**Comment by kanata163** [comment]
1.10和1.12是主要更新的分支，1.11没怎么更新了。1.12里也没有这部分的代码，后续会从1.10合进去。

**Comment by houxi1234** [comment]
1.10版本也只处理了delete，对于update和insert并没有进行处理

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
