### ISSUE TITLE
FlinkX集群模式下达梦数据丢失

### ISSUE THREAD

**Issue by Rx-cloud** [DTStack/chunjun#474]
任务过程:
1. 数据库A -> 达梦数据库临时表 (同步操作)
2. 达梦数据库临时表 -> 正式表 (posSql执行Insert into xxx (Select * From xxx_tmp))
由于同步达梦数据可能是部分线程没有显示调用commit导致临时表数据转移到正式表时数据丢失
临时表数据完整,正表数据丢失

##
同步达梦数据库的写入表配置必须加上库名,否则会导致插入表无效的问题(用户模式有多个数据库,需要同步到其他库时出现的错误)

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
