### ISSUE TITLE
请教flinkx的isRestore和isStream这2个开关的设计思路

### ISSUE THREAD

**Issue by geosmart** [DTStack/chunjun#476]
梳理了下flinkx的代码，发现这２个开关到处都是，关系很难梳理
下面是Flinkx 1.10.2 数据同步断点续传代码阅读笔记，实在绕不清

> 请教下设计思路和总结性的文字指导下

## isRestore逻辑

是否开启断点续传，适用于文件和Jdbc类型的数据源，kafka等流式的不支持

#### BaseRichInputFormat

* BaseRichInputFormat在`open`时：
	* 如果isRestore＝true，初始化formatState的状态数据（numOfSubTask、numberRead、numberWrite、metrics）

#### BaseDataReader

* BaseDataReader构造时，
	* 如果`isRestore＝true`，根据restoreColumnName获得MetaColumn，并设置restoreColumnIndex和restoreColumnType

#### JdbcInputFormat

* JdbcInputFormat.`buildQuerySql`时，
	* 如果`isRestore＝true`，根据`${restoreFilter}`构建恢复sql,或根据`${restoreFilter}`构建增量查询sql

* JdbcInputFormat.`closeInternal`时，
  * 如果isRestore＝true，如果task是非正常结束(state!=running)，设置`commit＝false`不提交事物

#### BaseRichOutputFormat

* BaseRichOutputFormat.`writeSingleRecord()`时，
	* 如果`isRestore＝false || isStreamButNoWriteCheckpoint`，`numWriteCounter`和`snapshotWriteCounter`的状态＋１
* BaseRichOutputFormat.`writeMultipleRecords()`时，
	* 如果isRestore＝false，`numWriteCounter`的状态＋rows.size
* BaseRichOutputFormat.`writeMultipleRecords()`失败时，
	* 如果isRestore＝true，直接抛出异常
	* 如果isRestore＝false，遍历rows执行`writeSingleRecord()`

#### BaseFileOutputFormat

* BaseFileOutputFormat.`actionBeforeWriteData()`时
  * 如果`restoreConfig.isRestore() && formatState != null`，将执行`cleanDirtyData()`清除脏数据文件

* BaseFileOutputFormat.`writeSingleRecordInternal()`时，如果`isRestore＝true,isStream=false`
  * 如果`currentRow[restoreColumnIndex]==lastRow[restoreColumnIndex]`，则`readyCheckpoint＝true`
* BaseFileOutputFormat.`getFormatState()`获取当前通道的`recover point`时，
  * 如果`isRestore＝false || lastRow＝＝null`时直接返回
  * 如果`isRestore＝true || !lastRow`时，如果`isStream=true||readyCheckpoint=true`时，执行`flushData()`持久化数据，并更新状态数据
  * `flushData`时，如果`isRestore＝true`，执行`moveTemporaryDataBlockFileToDirectory()`移动临时数据文件
* BaseFileOutputFormat.`nextBlock()`时，如果`isRestore＝true`，
  * currentBlockFileName前缀附加`.`号
* BaseFileOutputFormat.`closeInternal()`时，
	1. 如果task是非正常结束(state!=running)，如果`isRestore＝false`，执行`clearTemporaryDataFiles`清除临时数据文件；
	2. 如果task是正常结束(state==running)，执行`flushData()`，如果`isRestore＝false`，主动执行执行`moveTemporaryDataBlockFileToDirectory()`移动临时数据
* BaseFileOutputFormat.`tryCleanupOnError()`时，
	* 如果`isRestore＝false`，执行`clearTemporaryDataFiles`清除临时数据文件；

####  BaseHdfsOutputFormat子类

* orc/parquetOutputFormat.`writeSingleRecordToFile()`时，
  * 如果如果isRestore＝true，设置lastRow＝row

####  JdbcOutputFormat

* JdbcOutputFormat.`writeMultipleRecordsInternal()`时，
  * 如果如果isRestore＝true，如果`lastRow!=null`,设置`readyCheckpoint`，设置lastRow＝row

## isStream逻辑

是否开启适时传输：用于控制写入数据的时机

`bool isStream= (isRestore＝true && isStream=true)`

#### BaseDataReader

BaseDataReader构造时，

* 如果`isStream＝true`，直接返回，否则判断如果`isRestore＝true`则根据restoreColumnName获得MetaColumn，并设置restoreColumnIndex和restoreColumnType

#### BaseFileOutputFormat

* BaseFileOutputFormat.`writeSingleRecordInternal()`时，如果`isRestore＝true,isStream=false`
  * 如果`currentRow[restoreColumnIndex]==lastRow[restoreColumnIndex]`，则`readyCheckpoint＝true`

* BaseFileOutputFormat.`getFormatState()`获取当前通道的`recover point`时，
  * 如果`isStream=true||readyCheckpoint`时，执行`flushData()`持久化数据，并更新状态数据

* BaseFileOutputFormat.`afterCloseInternal`时
  * 如果`isStream＝true`，直接关闭数据源；
  * 如果`isStream＝false`，`waitForAllTasksToFinish()`等待所有通道操作完成，`moveAllTemporaryDataFileToDirectory`移动临时数据文件,关闭数据源，执行`clearTemporaryDataFiles`清除临时数据文件；

**Comment by FlechazoW** [comment]
https://github.com/DTStack/chunjun/issues/476

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.

**Comment by FlechazoW** [comment]
感谢你的总结，我在考虑将这些内容结合最新的代码整合到官方文档里，请问你有兴趣贡献下PR吗？

**Comment by geosmart** [comment]
这个是1.10的版本逻辑，1.12逻辑都不太一样了。

**Comment by FlechazoW** [comment]
嗯嗯，是有一些不同，但是整体设计逻辑是类似的，不知道是否可以结合最新的代码梳理一份呢？
