### ISSUE TITLE
维表关联 lookup

### ISSUE THREAD

**Issue by dangerousfeng** [DTStack/chunjun#487]
使用elasticsearch7-x 作为原表A
使用elasticsearch7-x 作为维表B，'lookup.cache-type' = 'all'
使用elasticsearch7-x 作为目标表C 

INSERT INTO C
SELECT A.* ,B.name
FROM  A
LEFT JOIN B  ON  A.id=B.id ;

发现一开始的A数据好像都没有做关联，或者说这时候B还没有完全缓存完成，
没有完成关联回填的A数据就直接入C表了

请问维表lookup有没有办法设置缓存完成，再开始跑 JOIN ?

**Comment by baisui1981** [comment]
这种实现方式 有待商榷

**Comment by deadwind4** [comment]
SQL写的有问题 要用如下SQL，源表用Kafka，要设置PROCTIME字段

`INSERT INTO sink_s
    SELECT lookup_m.id, lookup_m.name
    FROM ods_k
    LEFT JOIN lookup_m FOR SYSTEM_TIME AS OF ods_k.proc_time
    ON ods_k.id = lookup_m.id;`
