### ISSUE TITLE
sql server cdc 删除数据不会同步？

### ISSUE THREAD

**Issue by CHENJKNB** [DTStack/chunjun#491]
大佬 帮忙看看 sql server cdc  新增和修改数据 都会同步，但是做删除操作 数据不会同步。
CREATE TABLE source
(
    Id int,
    Name varchar(50)
) WITH (
      'connector' = 'sqlservercdc-x'
      ,'username' = 'sa'
      ,'password' = '1'
      ,'cat' = 'insert,delete,update'
      ,'url' = 'jdbc:sqlserver://x.x.x.x:1433;databaseName=SqlSugar4XTest'
      ,'table' = 'dbo.Test'
      ,'timestamp-format.standard' = 'SQL'
      ,'database' = 'SqlSugar4XTest'
      ,'poll-interval' = '1000'
      );

CREATE TABLE sink
(
    Id int,
    Name varchar(50),
    PRIMARY KEY(Id) NOT ENFORCED
) WITH (
      'connector'='sqlserver-x',
      'username'='sa',
      'password'='1',
      'url' = 'jdbc:jtds:sqlserver://x.x.x.x:1433;databaseName=SqlSugar4XTest;useLOBs=true',
      'schema'='dbo',
      'table-name'='Test1'
      );

insert into sink
select *
from source u;

**Comment by littlezhaozhaozhao** [comment]
您好,您的邮箱能给我下吗?我这是  能删除,插入但是不能更新

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
