### ISSUE TITLE
flinkx1.12 yarn per-job 模式下yarn任务不结束

### ISSUE THREAD

**Issue by fsj-228** [DTStack/chunjun#494]
您好，如题，flinkx1.12 yarn per-job 模式下的flink任务正常结束，但是yarn任务未结束，导致获取状态一直为RUNNING，请问有什么解决办法嘛？

**Comment by deadwind4** [comment]
你跑实时任务就是一直RUNNING

**Comment by fsj-228** [comment]
实际情况是，
flink任务已经finish了：
![image](https://user-images.githubusercontent.com/52200739/133395897-ade57ebc-699c-4cd5-85b6-1d045befc263.png)
但是 yarn的任务状态为RUNNING：
![image](https://user-images.githubusercontent.com/52200739/133395762-67051e67-25bb-4764-b413-f254d6133add.png)

我在钉钉群里看见也有人遇到这个问题，但是他的解决方法我这里未生效。

**Comment by deadwind4** [comment]
你写的JSON配置或SQL是啥

**Comment by hjfrank1991** [comment]
直接获取flink任务状态 finished 直接rest api kill yarn不行么

**Comment by fsj-228** [comment]
sql模式，任务是mysql到mysql，全量同步的任务，  直接通过api删除也不行，因为flinkjob 已经停止了，会报错Could not find Flink job 
![image](https://user-images.githubusercontent.com/52200739/133870481-c1d111b6-3d6a-4fc6-8953-aa537538e60c.png)

**Comment by hjfrank1991** [comment]
> sql模式，任务是mysql到mysql，全量同步的任务， 直接通过api删除也不行，因为flinkjob 已经停止了，会报错Could not find Flink job
> ![image](https://user-images.githubusercontent.com/52200739/133870481-c1d111b6-3d6a-4fc6-8953-aa537538e60c.png)

你的描述是flink task已经finished, yarn还是一直running对吧
可以使用yarn的api kill yarn的进程
`    val url = yarnURL.toString + appID + "/state"
    val client = HttpClients.createDefault()
    val put: HttpPut = new HttpPut(url)
    val body = "{\"state\":\"KILLED\"}"
    put.addHeader("Content-Type", "application/json")
    put.setEntity(new StringEntity(body))
    val response: CloseableHttpResponse = client.execute(put)
    val entity = response.getEntity
    val str = EntityUtils.toString(entity, "UTF-8")`

**Comment by deadwind4** [comment]
你是怎么启动的per-job模式，感觉像是走了Session模式

**Comment by fsj-228** [comment]
这个任务启动的，
bin/flinkx 
-mode  yarn-per-job  
-jobType sql 
-job sql/.sql 
-flinkxDistDir flinkx-dist
-flinkConfDir /Users/Documents/flink/conf 
-hadoopConfDir /Users/Documents/develops/conf 
-flinkLibDir /Users/Documents/flink/lib  
-confProp "{\"flink.checkpoint.interval\":\"60000\"}"

**Comment by fsj-228** [comment]
> > sql模式，任务是mysql到mysql，全量同步的任务， 直接通过api删除也不行，因为flinkjob 已经停止了，会报错Could not find Flink job
> > ![image](https://user-images.githubusercontent.com/52200739/133870481-c1d111b6-3d6a-4fc6-8953-aa537538e60c.png)
> 
> 你的描述是flink task已经finished, yarn还是一直running对吧
> 可以使用yarn的api kill yarn的进程
> ` val url = yarnURL.toString + appID + "/state" val client = HttpClients.createDefault() val put: HttpPut = new HttpPut(url) val body = "{\"state\":\"KILLED\"}" put.addHeader("Content-Type", "application/json") put.setEntity(new StringEntity(body)) val response: CloseableHttpResponse = client.execute(put) val entity = response.getEntity val str = EntityUtils.toString(entity, "UTF-8")`

好的，我试下

**Comment by liukunyuan** [comment]
TableResult execute = statementSet.execute();
   Optional<JobClient> jobClient =  execute.getJobClient();
   jobClient.ifPresent(v->{
   // 死循环，每隔N秒，去拿取这个jobid的flink的最终状态
   ApplicationStatus applicationStatus = ApplicationStatus.fromJobStatus(v.getJobStatus().get());
   jobExecutionResult = v.getJobExecutionResult();

   // 判断flink的最终状态
   // 结束yarn任务
   jobExecutionResult.complete(new JobExecutionResult(v.getJobID(),0,null));
   }

**Comment by liukunyuan** [comment]
这样执行flinkx的sql任务，flink运行完成后，yarn会退出了，已经验证
bin/flink run -d -m yarn-cluster  xx.flinkx-core.jar xx 
详情请见：https://issues.apache.org/jira/browse/FLINK-21264

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
