### ISSUE TITLE
1.10版本的clickhouse writer中presql没有作用

### ISSUE THREAD

**Issue by liumengkai** [DTStack/chunjun#501]
1.10版本中clickhouse writer中的presql没有作用，请问这个在新版本中解决了吗？

我的presql是“ALTER TABLE adtiming.network_event_tmp ON CLUSTER adt_5s_0r DROP PARTITION '2021-09-04 00:00:00'”
删除分区表数据，但是没有起到作用，旧数据依然还在。

请问这个在新版中进行改正了嘛？

因为一些线上的原先没有办法重新编译一个新的flinkx测试。

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
