### ISSUE TITLE
写入失败，异常被吞，导致任务的最终状态是完成，而不是失败

### ISSUE THREAD

**Issue by liukunyuan** [DTStack/chunjun#506]
mysql2mysql，共有3条数据。如果这3条数据都写入失败了。程序的退出状态还是FINISHED，而不是Failed

如何复现此bug：
mysql table1 name字段长度为20
mysql table2 name字段长度为10.
将table1的3条20长度的数据写入table2时，会发生异常。由于只有3条数据，走BaseRichOutputFormat.initTimingSubmitTask
这个定时任务写库。而定时任务写库，异常被吞，导致flink获取不到异常，而认为程序执行成功。

解决思路:
BaseRichOutputFormat.initTimingSubmitTask中发生的异常，放入全局变量
 exception.set(e);
在BaseRichOutputFormat.close()时，判断这个类的全局变量exception是否为空，不为空则抛出异常。

**Comment by deadwind4** [comment]
@yanghuaiGit @kanata163

**Comment by deadwind4** [comment]
定时线程会吞掉脏数据异常。

**Comment by deadwind4** [comment]
已经安排开发，下月发布

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
