### ISSUE TITLE
FlinkX on K8s时flink classloader找不到plugin中的类

### ISSUE THREAD

**Issue by geosmart** [DTStack/chunjun#510]
版本：flinkx　1.12.2
环境：flinkx/connector下面的jar都打包到docker image

问题描述：

flinkx的plugin是正常加载的
```
09:31:00.579 [flink-akka.actor.default-dispatcher-3] INFO com.dtstack.flinkx.util.DataSyncFactoryUtil - load flinkx plugin mysqlwriter:com.dtstack.flinkx.connector.mysql.sink.MysqlSinkFactory from /opt/flinkx
09:31:00.580 [flink-akka.actor.default-dispatcher-3] INFO com.dtstack.flinkx.util.DataSyncFactoryUtil - load plugin by jars: ["file:/opt/flinkx/connector/mysql/flinkx-connector-mysql-v1.12.jar"]
09:31:00.583 [flink-akka.actor.default-dispatcher-3] INFO com.dtstack.flinkx.classloader.ClassLoaderManager - jarUrl:file:/opt/flinkx/connector/mysql/flinkx-connector-mysql-v1.12.jar create ClassLoad successful...
```

但是flink的jobmaster初始化时抛出错误
```
Caused by: java.lang.ClassNotFoundException: com.dtstack.flinkx.connector.jdbc.sink.JdbcOutputFormat
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:64)
        at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:74)
        at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:48)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
```

－－－

Flinkx.Main线程和StreamExecutionEnvironment的executeAsync的线程不是同一个线程，
Flink的ClassLoader要怎么加载flinkx的plugin？
通过blobserver上传？还是自己在FLINK_CLASSPATH里面动态添加上source和sink的jar
有大佬知道这个机制吗？求教

**Comment by geosmart** [comment]
## 尝试１
在docker entrypoint中将connector加到FLINK_CLASSPATH中，可以了
>但是存在和flink代码冲突的风险，没有使用classloader解决潜在的冲突问题

## 尝试２
放到pipeline.classpaths中，只能识别１个jar！
>discoverSource时覆盖pipeline.jars和pipeline.classpath为source的jar导致的

## 尝试３
discoverSource时将source和sink的jar都设置到pipeline.jars/pipeline.classpath，然后万事大吉了!

理论上pipeline.jars设置为core,pipeline.classpath设置为source和plugin的jar就行的,
不知道为什么flinkx要将pipeline.jars/pipeline.classpath设置为一样的？  @deadwind4 知道不

**Comment by kanata163** [comment]
之前on k8s application模式是有点问题，类找不到的问题我们刚修复了，大致思路是将任务所需的jar包在构建jobgraph的时候注册进PipelineOptions.JARS、PipelineOptions.CLASSPATHS中，下次更新应该能推到社区。

**Comment by shaolei7788** [comment]
> 之前on k8s application模式是有点问题，类找不到的问题我们刚修复了，大致思路是将任务所需的jar包在构建jobgraph的时候注册进PipelineOptions.JARS、PipelineOptions.CLASSPATHS中，下次更新应该能推到社区。
我现在也遇到了这个问题，请问下，修复的代码你们提交了吗？

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
