### ISSUE TITLE
[flinkx-core]sql模式下插件加载机制优化

### ISSUE THREAD

**Issue by liukunyuan** [DTStack/chunjun#511]
目前加载flinkx的connector插件方式不够完善，在很多情况下会加载不进去
https://github.com/DTStack/flinkx/issues/510

目前，我们自己的优化方式如下
1.通过解析sql得到connector的name，根据name和插件path拼接jar路径
2.将jar路径加入到pipeline.classpaths（local模式）或者pipeline.jars（yarn模式）中，这2个路径类似classpath，flink会自动读取的

好处有2个：
1.我们成功通过这种方式去除了自定义FactoryUtil类，代码侵入性更少
2.我们公司的flink和hadoop不是apache原生版本，我们最终目标是去除flinkx打包携带的flink依赖，这样子，flinkx能非常方便地和非开源的flink和hadoop结合，所以在尽力去除flinkx自定义FactoryUtil等类。

**Comment by geosmart** [comment]
我现在也是这么做的，
１.注入环境变量FLINKX_SOURCE_PLUGIN和FLINKX_SINK_PLUGIN
2. 在docker image的entrypoint里面把plugin jar附加到FLINKX_CLASSPATH
```

set_flinkx_classpath() {
    # flinkx classpath:flinkx-core
    plugin_jars=$(find $FLINKX_HOME -maxdepth 2 -type f -name "flinkx-*.jar")
    FLINKX_CLASSPATH=${plugin_jars//[[:space:]]/\:}

    # need set env : $FLINKX_SOURCE_PLUGIN , $FLINKX_SINK_PLUGIN
    if [[ ${FLINKX_SOURCE_PLUGIN} != "" && ${FLINKX_SINK_PLUGIN} != "" ]]; then
        # flinkx classpath:flinkx-connector
        connector_jars=$(find $FLINKX_HOME/connector/$FLINKX_SOURCE_PLUGIN $FLINKX_HOME/connector/$FLINKX_SINK_PLUGIN -type f -name "flinkx-connector-*.jar")
        FLINKX_CLASSPATH=$FLINKX_CLASSPATH:${connector_jars//[[:space:]]/\:}
    fi
}
```

但是看到Flinkx代码里面有这么一段、
```java

/**
 * Utility for working with {@link Factory}s. 改动内容：增加方法loadFactories，增加变量pluginPath、env、classPathSet
 * 改动原因：flink原生加载插件的方式是使用spi，不符合我们需求。在原来基础上增加通过classloader指定jar加载插件
 */
@PublicEvolving
public final class FactoryUtil 

```
但是不知道flink　jobmanager初始化时就是报找不到flinkx connector的类

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
