### ISSUE TITLE
flinkx编译Kafka源码部分抛错

### ISSUE THREAD

**Issue by yesinamose** [DTStack/chunjun#516]
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/opt/software/flinkx-1.12_release/flinkx-connectors/flinkx-connector-kafka/src/main/java/com/dtstack/flinkx/connector/kafka/source/KafkaDynamicSource.java:[359,61] unreported exception X; must be caught or declared to be thrown

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary.
