### ISSUE TITLE
flinkx1.10 -confProp taskmanager.memory.mb，taskmanager.slots不生效

### ISSUE THREAD

**Issue by wushuoyouting** [DTStack/chunjun#518]
使用flinkx1.10 测试

flink-conf.yaml的参数中 taskmanager.memory.process.size: 2048m ， taskmanager.numberOfTaskSlots: 1，parallelism.default: 2 这三个参数都没生效，只有jobmanager.heap.size: 1024m正常，
flinkx不设置-confProp参数的情况下，只能读到jobmanager.heap.size参数，其他三个参数不生效。
flinkx设置-confProp "{\"parallelism.default\":6,\"taskmanager.memory.mb\":3072,\"taskmanager.slots\":2}" 参数后，还是同样的情况，jobmanager.heap.size生效，这三个配置不生效

请问有什么临时解决的办法，或者哪个版本是生效的

**Comment by wushuoyouting** [comment]
这是我测试的结果
yarn配置
```
yarn.scheduler.minimum-allocation-mb=2G
yarn.scheduler.minimum-allocation-vcores=2

yarn.scheduler.maximum-allocation-mb=12G
yarn.scheduler.maximum-allocation-vcores=12
```
Flink配置
```
jobmanager.rpc.address: server001
jobmanager.rpc.port: 6123
jobmanager.heap.size: 1024m
taskmanager.memory.process.size: 3072m
taskmanager.numberOfTaskSlots: 1
parallelism.default: 2
```
============================================
flink任务验证参数是否正常
```
flink run -m yarn-cluster -ynm perjobtest \
$FLINK_HOME/examples/batch/WordCount.jar \
--input hdfs://server001:8020/wc.txt \
--output hdfs://server001:8020/output/wcresult1.txt
```
yarn情况
![asdfasdfrd](https://user-images.githubusercontent.com/34428872/137573974-8ad02279-138b-44d8-b348-d251285734fd.png)

=======================================================
flinkx 任务执行脚本，默认参数
```
/usr/local/src/flinkx-1.10/bin/flinkx \
    -mode yarnPer \
    -job /usr/local/src/flinkx-1.10/docs/example/stream_stream.json \
    -pluginRoot $FLINKX_HOME/syncplugins \
    -flinkconf $FLINK_HOME/conf \
    -flinkLibJar $FLINK_HOME/lib \
    -yarnconf $HADOOP_HOME/etc/hadoop \
    -queue root.default
```
yarn情况
看资源分布情况，taskmanager只启动了一个，并非parallelism/slot =2个 ，所以flinkx对flink默认配置的这两个参数未生效
但是设置的taskmanager.memory.process.size居然生效了！！难道是我重启了hadoop？
![asdfasdfrd](https://user-images.githubusercontent.com/34428872/137573926-2eec0385-8f0a-4f4e-9583-e75eaffb6e04.png)

======================================================
flinkx 任务执行脚本呢，添加-confProp配置
```
/usr/local/src/flinkx-1.10/bin/flinkx \
      -mode yarnPer \
      -job /usr/local/src/flinkx-1.10/docs/example/stream_stream.json \
      -pluginRoot $FLINKX_HOME/syncplugins \
      -flinkconf $FLINK_HOME/conf \
      -flinkLibJar $FLINK_HOME/lib \
      -yarnconf $HADOOP_HOME/etc/hadoop \
      -queue root.default \
      -confProp "{\"parallelism.default\":4,\"taskmanager.memory.mb\":3072,\"taskmanager.slots\":2}"
```
yarn情况
设置了confProp之后，应该是3个container，6核cpu，2024+4/2*3072=8G的内存才对，看来在confProp设置的这三个参数没有生效
![asdfasdfrd](https://user-images.githubusercontent.com/34428872/137574157-9ee2a63c-8a43-4dfa-b6f7-01daf230eb9f.png)

**Comment by FlechazoW** [comment]
This issue has been open too long for us to help, if you still have the same problem, please re-open an issue.
