### ISSUE TITLE
Flinkx统计指标（numErrors）优化，包括read的时候转换异常统计

### ISSUE THREAD

**Issue by liukunyuan** [DTStack/chunjun#519]
目前Errors相关指标统计了总错误数、空指针异常数等错误。没有统计reader的时候转换错误条数。
作为一个用户关注的指标，其实并不关注什么异常，而是关心哪个阶段发生了异常。
具体指标是
reader转换错误条数
writer转换错误条数
writer输出错误条数

发生了什么异常，比如空指针，是从log中发现的，而不是从指标中查看。

**Comment by FlechazoW** [comment]
This issue has been open too long for us to help, if you still have the same problem, please re-open an issue.
