### ISSUE TITLE
解决oracle logminer 采集到kafka问题

### ISSUE THREAD

**Issue by wangys08** [DTStack/chunjun#523]
**Describe the bug**
通过flinkx采集oracle数据（logminer方式）会存在一个序列化的问题

我们做了如下修改，验证后问题解决：
LogMinerColumnConverter类的parseColumnList方法：
 AbstractBaseColumn column =
                (AbstractBaseColumn) converters.get(index).deserialize(entryColumn.getData());
//在此处需做判断
            if (Objects.nonNull(column)) {
                columnList.add(column);
                headerList.add(prefix + entryColumn.getName());
            }
![image](https://user-images.githubusercontent.com/35442118/137881763-c25db554-da31-4e4d-bd8f-251234860e05.png)

**Comment by mingweiqiu** [comment]
问一下大佬，我按照你这个改了也还是获取不到变化的数据，你的json文件能贴出来看看吗

**Comment by wangys08** [comment]
> 

用的官方提供的用例，只是将数据源相关信息改成自己的，我等下找下邮件发你

**Comment by mingweiqiu** [comment]
好的，谢谢

**Comment by mingweiqiu** [comment]
有空帮忙发一下，谢谢

**Comment by FlechazoW** [comment]
This issue has been open too long for us to help, if you still have the same problem, please re-open an issue.
