### ISSUE TITLE
优化flinkx提交逻辑，方便用户提交flinkx代码到yarn per job

### ISSUE THREAD

**Issue by liukunyuan** [DTStack/chunjun#524]
目前很多用户反馈，flinkx提交yarn perjob有问题

使用如下提交方式可以解决问题
1.安裝好flink，以下命令去验证是否安装成功（提交到yarn的perjob）
/bin/bash  ./bin/flink run -m yarn-cluster -p 2 -yjm 700m -ytm 1024m ./examples/batch/DistCp.jar  --input  hdfs://namespace:9000/tmp/tmp/20210804/2021-08-05   --output hdfs://namespace:9000/tmp/20210805

2.修改flinkx的maven pom.xml,去除flinkx-client模块。

3.将flinkx中hadoop、yarn、flink相关依赖(最好是去除掉，避免冲突），和集群相关依赖版本统一.将flinkx-core和flinkx-connector相关jar包放入flink的lib目录

4.将flinkx中的FactoryUtil修改为FlinkxFactoryUtil

5.使用flink命令提交flinkx任务,提交命令是:
xxxx/flink-1.12.2/bin/flink run -m yarn-cluster -yjm 1024 -ytm 1024 -ynm jobname  -p 1   -j xxxxx/flink-1.12.2/lib/flinkx-core-1.12-SNAPSHOT.jar   -c com.dtstack.flinkx.Main  -jobName "Flink Job" -jobType "sql" -connectorLoadMode CLASSLOADER  -pluginLoadMode shipfile -mode yarn-per-job -priority 1 -job   flinkx-examples/sql/stream/stream2.sql

**Comment by jon-qj** [comment]
👍

**Comment by FlechazoW** [comment]
This issue has been open too long for us to help, if you still have the same problem, please re-open an issue.
