### ISSUE TITLE
MySqllWriter的写入replace模式存在异常SQL statement must not contain ? character.

### ISSUE THREAD

**Issue by geosmart** [DTStack/chunjun#529]
![image](https://user-images.githubusercontent.com/3156608/138662456-eb77bfe5-c10e-4bf2-82ee-fdfb5401f78e.png)

![image](https://user-images.githubusercontent.com/3156608/138662522-ad5dfc4e-65cc-4351-bdc0-e19fbe450408.png)

![image](https://user-images.githubusercontent.com/3156608/138662568-073615a4-ef8a-406e-87be-30d00930317b.png)

替换参数时写死了: 导致参数替换失败,校验不通过

**Comment by FlechazoW** [comment]
This issue has been open too long for us to help, if you still have the same problem, please re-open an issue.
