### ISSUE TITLE
binlog数据同步如何恢复上次同步的position？

### ISSUE THREAD

**Issue by geosmart** [DTStack/chunjun#532]
版本：1.12-release
环境：flinkx在yarn中运行，checkpoint中存储了canal的position信息，canal启用了gtid

1. binlogreader的event数据有什么办法可以按照事物聚合成有序的row数组？
2. 当flink程序异常终止的时候，如何回复上次中断的gtid继续。

没有看到读取checkpoint来设置FormatState的代码，目前每次都是重新初始化formatState
```java

    /** 从checkpoint状态缓存map中恢复上次任务的指标信息 */
    private void initRestoreInfo() {
        if (formatState == null) {
            formatState = new FormatState(indexOfSubTask, null);
        } else {
            numReadCounter.add(formatState.getMetricValue(Metrics.NUM_READS));
            bytesReadCounter.add(formatState.getMetricValue(Metrics.READ_BYTES));
            durationCounter.add(formatState.getMetricValue(Metrics.READ_DURATION));
        }
    }
```

**Comment by geosmart** [comment]
按照事物聚合输出我自己实现了，加一个converter，聚合rows输出成１个row，里面是json数组；

但是任务恢复还是没看到，
@deadwind4 有空帮瞧一下？

**Comment by geosmart** [comment]
local模式配置`execution.savepoint.path`，然后设置下面的代码可以从savepoint恢复
```
            if (StringUtils.isNotBlank(restorePath)) {
                ((MyLocalStreamEnvironment) env)
                        .setSettings(SavepointRestoreSettings.forPath(restorePath));
            }
```

yarnPerJob模式`execution.savepoint.path`不生效，看web-ui界面配置是存在的
![image](https://user-images.githubusercontent.com/3156608/143428459-a2162ef3-cdf8-46c1-86ec-85a3945f95ff.png)

**Comment by FlechazoW** [comment]
This issue has been open too long for us to help, if you still have the same problem, please re-open an issue.
