### ISSUE TITLE
编译报错 A compiler error            

### ISSUE THREAD

**Issue by magic20191** [DTStack/chunjun#534]
env:
idea2019
jdk8
flinkx1.12

[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.4.2:check (spotless-check) on project flinkx-core: Execution spotless-check of goal com.diffplug.spotless:spotless-maven-plugin:2.4.2:check failed: Unable to resolve dependencies: Failed t
o collect dependencies at com.google.googlejavaformat:google-java-format:jar:1.7 -> com.google.errorprone:javac-shaded:jar:9+181-r4173-1: Failed to read artifact descriptor for com.google.errorprone:javac-shaded:jar:9+181-r4173-1: Could not transfer artifact com.go
ogle.errorprone:javac-shaded:pom:9+181-r4173-1 from/to alimaven (http://maven.aliyun.com/nexus/content/repositories/central/): authorization failed for http://maven.aliyun.com/nexus/content/repositories/central/com/google/errorprone/javac-shaded/9+181-r4173-1/javac
-shaded-9+181-r4173-1.pom, status: 403 Forbidden -> [Help 1]

flinkx1.12编译报这个错，这个咋解决啊    Compiling this error， How to solve

**Comment by nuclearwu** [comment]
同问+1

**Comment by mlin4020** [comment]
+1

**Comment by libailin** [comment]
请参考我的这个回答，己解决！

https://github.com/DTStack/chunjun/issues/609#issuecomment-1082786557
