### ISSUE TITLE
flinkx-pulsar插件升级客户端版本支持Multiple advertised listeners

### ISSUE THREAD

**Issue by renxiaoyao** [DTStack/chunjun#535]
当在生产环境中部署 Pulsar 集群时，broker 可能需要针对不同网络环境提供多个可访问的地址。客户端就可以通过listener获取服务的 URL，用于连接到对应的 broker地址。 [参考：Multiple advertised listeners](https://pulsar.apache.org/docs/en/concepts-multiple-advertised-listeners/)。升级到较新的客户端版本，可以向前兼容。

**Comment by FlechazoW** [comment]
This issue has been open too long for us to help, if you still have the same problem, please re-open an issue.
