### ISSUE TITLE
关于flinkx读取es问题

### ISSUE THREAD

**Issue by zzzzzzzs** [DTStack/chunjun#537]
使用flinkx读取es数据，报Caused by: java.lang.ClassNotFoundException:com.dtstack.flinkx.elasticsearch7.reader.Elasticsearch7Reader。这要怎么解决呢？

**Comment by meng1222** [comment]
你看一下es7模块是不是注释掉了

**Comment by FlechazoW** [comment]
This issue has been open too long for us to help, if you still have the same problem, please re-open an issue.
