### ISSUE TITLE
列转换, 在使用core模块DateUtil工具类时, 遇到LocalDateTime和LocalDate类型任务会运行失败

### ISSUE THREAD

**Issue by lkjhchen2** [DTStack/chunjun#539]
列转换, 在使用core模块DateUtil工具类时, 遇到LocalDateTime和LocalDate类型任务会运行失败

**Comment by Su1024** [comment]
有具体异常日志吗

**Comment by FlechazoW** [comment]
This issue has been open too long for us to help, if you still have the same problem, please re-open an issue.
