### ISSUE TITLE
standalone模式上无法使用savepoint功能

### ISSUE THREAD

**Issue by rayRose1** [DTStack/chunjun#550]
提交命令如下：
bin/flinkx \
  -mode standalone \
  -jobType sync \
  -jobName mysql_mysql \
  -job /opt/flinkx/cestc_flinkx/flinkx-examples/json/mysql/mysql_mysql.json \
  -flinkxDistDir flinkx-dist \
  -flinkConfDir $FLINK_HOME/conf \
 -confProp "{\"execution.savepoint.path\":\"file:/opt/flink-1.12/checkpoints/f163b13028288e397c5f7661428469a8/chk-3\"}"

发现任务启动时候无法基于savepoint来继续运行任务

**Comment by wangys08** [comment]
我提了个issue，解决了这个问题，本地已经验证

**Comment by FlechazoW** [comment]
This issue has been open too long for us to help, if you still have the same problem, please re-open an issue.
