### ISSUE TITLE
TimeStamp转化为字符类型字段为null

### ISSUE THREAD

**Issue by hitits** [DTStack/chunjun#552]
源表是mysql 字段类型为TimeStamp 目标表是sap hana 字段类型为varchar ，通过transformSql 转化 ,目标表对应字段均为null。
尝试过多种方式DATE_FORMAT(cast(UPDATE_TIME as TIMESTAMP) ,'yyyy-MM-dd')   UPDATE_TIME，TO_DATE(),TO_CHAR()......
均不行。
bin/flinkx  -mode standalone  -jobType sync  -flinkxDistDir flinkx-dist

**Comment by FlechazoW** [comment]
This issue has been open too long for us to help, if you still have the same problem, please re-open an issue.
