### ISSUE TITLE
flinkx-connector-elasticsearch7 not support map datatype.

### ISSUE THREAD

**Issue by xiaoxiaopan118** [DTStack/chunjun#572]
flinkx-connector-elasticsearch7 not support map datatype.

**Comment by xiaoxiaopan118** [comment]
Version: flinkx-1.12
scenes: es7 to es 7
Data:
"files": {
"module": "elasticsearch",
"name": "server"
},
Error:
com.dtstack.flinkx.throwable.ReadRecordException: 
java.lang.ClassCastException: java.util.HashMap cannot be cast to java.lang.String

**Comment by deadwind4** [comment]
coming soon

**Comment by silentxingtian** [comment]
自己改源码啊

**Comment by fangxy-7010** [comment]
{
                "files": {
                  "module": "elasticsearch",
                  "name": "server"
                },
                "type": "object"
              }
