### ISSUE TITLE
升级master分支依赖的flink版本到1.13.1

### ISSUE THREAD

**Issue by yiduwangkai** [DTStack/chunjun#573]
现在flink 1.14已经发布，master分支依赖的flink还是1.12.5， 有必要升级master分支依赖的flink版本到1.13.1

**Comment by deadwind4** [comment]
未来会直接升级 1.14，并且重写所有connector

**Comment by FlechazoW** [comment]
下个迭代升级到1.16.

**Comment by zengqinchris** [comment]
支持flink版本升级，1.13现在都无法正常运行任务，扩展性不够
