### ISSUE TITLE
oracle 向hdfs中写number类型的时候会 fixed binary size16 does not match field type length 5 的错误，这是因为什么问题呢

### ISSUE THREAD

**Issue by yikadaluosi** [DTStack/chunjun#640]
oracle 向hdfs中写number类型的时候会 fixed binary size16 does not match field type length 5 的错误，这是因为什么问题呢
oracle字段类型是number(14,6), hive中精度也是这样，不知道是哪里出了问题

**Comment by yikadaluosi** [comment]
当hdfs writer中字段设置为decimal（10，6）的时候显示错误为 空指针

**Comment by yikadaluosi** [comment]
parquet snappy时出现，text格式下没有问题

**Comment by yikadaluosi** [comment]
![Uploading image.png…]()

**Comment by yikadaluosi** [comment]
![image](https://user-images.githubusercontent.com/38837577/158511656-40617dbf-8dc0-45a9-a3f5-7f4205b016dd.png)

**Comment by yikadaluosi** [comment]
![image](https://user-images.githubusercontent.com/38837577/158511753-28ec0f1b-7de4-44a8-a728-eacd3984709f.png)这个错误是空指针

**Comment by WTZ468071157** [comment]
能否提供下具体的脚本内容，以及oracle，hive的建表语句，我想在本地复现下这个问题。

**Comment by libailin** [comment]
这个问题是由于 hdfs parquet 在使用 decimal 类型丢失了精度，使用了默认的 decimal（10, 0）, 导致小于源始数据精度。
此问题己在最新的master代码修复。老版本的话，可以按照下图修改
![image](https://user-images.githubusercontent.com/3014381/221773510-d7f92cb7-5a28-4b1c-9631-ce2eabfd5571.png)
