### ISSUE TITLE
doris binlog全量或者增量同步

### ISSUE THREAD

**Issue by cpla13** [DTStack/chunjun#671]
这个是增量数据同步得调试截图和提交到doris的截图，在第一次提交任务或者更新数据增量同步的时候不起效，只会删除原来的数据，原因是因为插入的值拼错了，然后流程是插入再删除就出问题了

![1648796100039_4048B8AF-6B5E-4e31-86D6-22CC305AD302](https://user-images.githubusercontent.com/37918873/161238737-3f667af1-a577-4453-8fbe-2e13a050aeb3.png)
![1648795114044_1AA9C99A-CFD6-4533-A971-50F9FF98CE20](https://user-images.githubusercontent.com/37918873/161238834-291e1bc7-d575-455f-be84-fb2ab853703b.png)

**Comment by FlechazoW** [comment]
This issue has been open too long for us to help, if you still have the same problem, please re-open an issue.
