### ISSUE TITLE
mvn 编译

### ISSUE THREAD

**Issue by fangjie-luoxi** [DTStack/chunjun#697]
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.pivotal:greenplum-jdbc:jar:5.1.4 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for flinkx-all 1.6:
[INFO]
[INFO] flinkx-all ......................................... SUCCESS [  0.719 s]
[INFO] flinkx-core ........................................ SUCCESS [  4.276 s]
[INFO] flinkx-launcher .................................... SUCCESS [ 13.022 s]
[INFO] flinkx-stream ...................................... SUCCESS [  0.031 s]
[INFO] flinkx-stream-reader ............................... SUCCESS [ 25.160 s]
[INFO] flinkx-stream-writer ............................... SUCCESS [  0.297 s]
[INFO] flinkx-carbondata .................................. SUCCESS [  0.015 s]
[INFO] flinkx-carbondata-core ............................. SUCCESS [  0.229 s]
[INFO] flinkx-carbondata-reader ........................... SUCCESS [  1.947 s]
[INFO] flinkx-carbondata-writer ........................... SUCCESS [  2.096 s]
[INFO] flinkx-rdb ......................................... SUCCESS [  0.025 s]
[INFO] flinkx-rdb-core .................................... SUCCESS [  0.268 s]
[INFO] flinkx-db2 ......................................... SUCCESS [  0.019 s]
[INFO] flinkx-db2-core .................................... SUCCESS [  0.172 s]
[INFO] flinkx-rdb-reader .................................. SUCCESS [  0.415 s]
[INFO] flinkx-db2-reader .................................. SUCCESS [  0.827 s]
[INFO] flinkx-rdb-writer .................................. SUCCESS [  0.307 s]
[INFO] flinkx-db2-writer .................................. SUCCESS [  0.894 s]
[INFO] flinkx-es .......................................... SUCCESS [  0.021 s]
[INFO] flinkx-es-core ..................................... SUCCESS [  0.365 s]
[INFO] flinkx-es-reader ................................... SUCCESS [  4.108 s]
[INFO] flinkx-es-writer ................................... SUCCESS [  3.821 s]
[INFO] flinkx-ftp ......................................... SUCCESS [  0.032 s]
[INFO] flinkx-ftp-core .................................... SUCCESS [  0.230 s]
[INFO] flinkx-ftp-reader .................................. SUCCESS [  0.369 s]
[INFO] flinkx-ftp-writer .................................. SUCCESS [  0.337 s]
[INFO] flinkx-hbase ....................................... SUCCESS [  0.027 s]
[INFO] flinkx-hbase-core .................................. SUCCESS [  0.265 s]
[INFO] flinkx-hbase-reader ................................ SUCCESS [  3.227 s]
[INFO] flinkx-hbase-writer ................................ SUCCESS [  3.171 s]
[INFO] flinkx-hdfs ........................................ SUCCESS [  0.016 s]
[INFO] flinkx-hdfs-core ................................... SUCCESS [  0.358 s]
[INFO] flinkx-hdfs-reader ................................. SUCCESS [  9.179 s]
[INFO] flinkx-hdfs-writer ................................. SUCCESS [  8.973 s]
[INFO] flinkx-mongodb ..................................... SUCCESS [  0.012 s]
[INFO] flinkx-mongodb-core ................................ SUCCESS [  0.190 s]
[INFO] flinkx-mongodb-reader .............................. SUCCESS [  0.618 s]
[INFO] flinkx-mongodb-writer .............................. SUCCESS [  0.533 s]
[INFO] flinkx-mysql ....................................... SUCCESS [  0.000 s]
[INFO] flinkx-mysql-core .................................. SUCCESS [  0.164 s]
[INFO] flinkx-mysql-reader ................................ SUCCESS [  0.445 s]
[INFO] flinkx-mysql-dreader ............................... SUCCESS [  0.410 s]
[INFO] flinkx-mysql-writer ................................ SUCCESS [  0.368 s]
[INFO] flinkx-odps ........................................ SUCCESS [  0.014 s]
[INFO] flinkx-odps-core ................................... SUCCESS [  0.223 s]
[INFO] flinkx-odps-reader ................................. SUCCESS [  0.967 s]
[INFO] flinkx-odps-writer ................................. SUCCESS [  0.809 s]
[INFO] flinkx-oracle ...................................... SUCCESS [  0.015 s]
[INFO] flinkx-oracle-core ................................. SUCCESS [  0.158 s]
[INFO] flinkx-oracle-reader ............................... SUCCESS [  0.950 s]
[INFO] flinkx-oracle-writer ............................... SUCCESS [  0.997 s]
[INFO] flinkx-postgresql .................................. SUCCESS [  0.018 s]
[INFO] flinkx-postgresql-core ............................. SUCCESS [  0.148 s]
[INFO] flinkx-postgresql-reader ........................... SUCCESS [  0.366 s]
[INFO] flinkx-postgresql-writer ........................... SUCCESS [  0.317 s]
[INFO] flinkx-sqlserver ................................... SUCCESS [  0.000 s]
[INFO] flinkx-sqlserver-core .............................. SUCCESS [  0.166 s]
[INFO] flinkx-sqlserver-reader ............................ SUCCESS [  0.305 s]
[INFO] flinkx-sqlserver-writer ............................ SUCCESS [  0.264 s]
[INFO] flinkx-redis ....................................... SUCCESS [  0.011 s]
[INFO] flinkx-redis-core .................................. SUCCESS [  0.165 s]
[INFO] flinkx-redis-writer ................................ SUCCESS [  0.335 s]
[INFO] flinkx-gbase ....................................... SUCCESS [  0.017 s]
[INFO] flinkx-gbase-core .................................. SUCCESS [  0.151 s]
[INFO] flinkx-gbase-reader ................................ SUCCESS [  0.319 s]
[INFO] flinkx-gbase-writer ................................ SUCCESS [  0.314 s]
[INFO] flinkx-binlog ...................................... SUCCESS [  0.014 s]
[INFO] flinkx-binlog-core ................................. SUCCESS [  0.231 s]
[INFO] flinkx-binlog-reader ............................... SUCCESS [  2.569 s]
[INFO] flinkx-hive ........................................ SUCCESS [  0.010 s]
[INFO] flinkx-hive-core ................................... SUCCESS [  0.500 s]
[INFO] flinkx-hive-writer ................................. SUCCESS [ 13.659 s]
[INFO] flinkx-kb .......................................... SUCCESS [  0.001 s]
[INFO] flinkx-kb-core ..................................... SUCCESS [  0.182 s]
[INFO] flinkx-kb-reader ................................... SUCCESS [  0.221 s]
[INFO] flinkx-kafka11 ..................................... SUCCESS [  0.000 s]
[INFO] flinkx-kafka11-reader .............................. SUCCESS [  0.582 s]
[INFO] flinkx-kb-writer ................................... SUCCESS [  0.182 s]
[INFO] flinkx-kafka11-writer .............................. SUCCESS [  0.538 s]
[INFO] flinkx-kafka10 ..................................... SUCCESS [  0.012 s]
[INFO] flinkx-kafka10-reader .............................. SUCCESS [  0.698 s]
[INFO] flinkx-kafka10-writer .............................. SUCCESS [  0.498 s]
[INFO] flinkx-kafka09 ..................................... SUCCESS [  0.018 s]
[INFO] flinkx-kafka09-reader .............................. SUCCESS [  1.394 s]
[INFO] flinkx-kafka09-writer .............................. SUCCESS [  1.273 s]
[INFO] flinkx-kudu ........................................ SUCCESS [  0.016 s]
[INFO] flinkx-kudu-core ................................... SUCCESS [  0.302 s]
[INFO] flinkx-kudu-reader ................................. SUCCESS [  2.014 s]
[INFO] flinkx-kudu-writer ................................. SUCCESS [  1.710 s]
[INFO] flinkx-kafka ....................................... SUCCESS [  0.008 s]
[INFO] flinkx-kafka-reader ................................ SUCCESS [  0.599 s]
[INFO] flinkx-kafka-writer ................................ SUCCESS [  0.554 s]
[INFO] flinkx-clickhouse .................................. SUCCESS [  0.013 s]
[INFO] flinkx-clickhouse-core ............................. SUCCESS [  0.168 s]
[INFO] flinkx-clickhouse-reader ........................... SUCCESS [  1.132 s]
[INFO] flinkx-clickhouse-writer ........................... SUCCESS [  1.153 s]
[INFO] flinkx-polardb ..................................... SUCCESS [  0.012 s]
[INFO] flinkx-polardb-core ................................ SUCCESS [  0.151 s]
[INFO] flinkx-polardb-reader .............................. SUCCESS [  0.996 s]
[INFO] flinkx-polardb-writer .............................. SUCCESS [  0.961 s]
[INFO] flinkx-phoenix ..................................... SUCCESS [  0.009 s]
[INFO] flinkx-phoenix-core ................................ SUCCESS [  0.325 s]
[INFO] flinkx-phoenix-reader .............................. SUCCESS [  8.623 s]
[INFO] flinkx-phoenix-writer .............................. SUCCESS [  8.869 s]
[INFO] flinkx-emqx ........................................ SUCCESS [  0.016 s]
[INFO] flinkx-emqx-core ................................... SUCCESS [  0.134 s]
[INFO] flinkx-emqx-reader ................................. SUCCESS [  0.287 s]
[INFO] flinkx-emqx-writer ................................. SUCCESS [  0.274 s]
[INFO] flinkx-restapi ..................................... SUCCESS [  0.000 s]
[INFO] flinkx-restapi-core ................................ SUCCESS [  0.173 s]
[INFO] flinkx-restapi-writer .............................. SUCCESS [  0.436 s]
[INFO] flinkx-dm .......................................... SUCCESS [  0.011 s]
[INFO] flinkx-dm-core ..................................... SUCCESS [  0.132 s]
[INFO] flinkx-dm-reader ................................... SUCCESS [  0.432 s]
[INFO] flinkx-dm-writer ................................... SUCCESS [  0.402 s]
[INFO] flinkx-greenplum ................................... SUCCESS [  0.011 s]
[INFO] flinkx-greenplum-core .............................. FAILURE [  0.020 s]
[INFO] flinkx-greenplum-reader ............................ SKIPPED
[INFO] flinkx-greenplum-writer ............................ SKIPPED
[INFO] flinkx-kingbase .................................... SKIPPED
[INFO] flinkx-kingbase-core ............................... SKIPPED
[INFO] flinkx-kingbase-reader ............................. SKIPPED
[INFO] flinkx-kingbase-writer ............................. SKIPPED
[INFO] flinkx-test ........................................ SKIPPED
[INFO] flinkx-polardb-dreader ............................. SKIPPED
[INFO] flinkx-saphana ..................................... SKIPPED
[INFO] flinkx-saphana-core ................................ SKIPPED
[INFO] flinkx-saphana-reader .............................. SKIPPED
[INFO] flinkx-saphana-writer .............................. SKIPPED
[INFO] flinkx-teradata .................................... SKIPPED
[INFO] flinkx-teradata-core ............................... SKIPPED
[INFO] flinkx-teradata-reader ............................. SKIPPED
[INFO] flinkx-teradata-writer ............................. SKIPPED
[INFO] flinkx-cassandra ................................... SKIPPED
[INFO] flinkx-cassandra-core .............................. SKIPPED
[INFO] flinkx-cassandra-reader ............................ SKIPPED
[INFO] flinkx-cassandra-writer ............................ SKIPPED
[INFO] flinkx-mongodboplog-reader ......................... SKIPPED
[INFO] flinkx-pgwal ....................................... SKIPPED
[INFO] flinkx-pgwal-core .................................. SKIPPED
[INFO] flinkx-pgwal-reader ................................ SKIPPED
[INFO] flinkx-pulsar ...................................... SKIPPED
[INFO] flinkx-pulsar-writer ............................... SKIPPED
[INFO] flinkx-restapi-reader .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:28 min
[INFO] Finished at: 2022-04-11T16:37:22+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project flinkx-greenplum-core: Could not resolve dependencies for project com.dtstack.flinkx:flinkx-greenplum-core:jar:1.6: com.pivotal:greenplum-jdbc:jar:5.1.4 was not found in https://maven.aliyun.com/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of aliyunmaven has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :flinkx-greenplum-core

版本：1.8.9
问题：编译的时候出现找不到包的问题，试了好几个版本，基本都会遇到包找不到，问题大概是mvn镜像仓库里没有，但是我又懂怎么自定义安装，不是java开发人员用这个工具挺难受的，各种编译失败，太难了，从clone到放弃
建议：可以跳过部分插件吗，其实大部分插件是用不到的

**Comment by WTZ468071157** [comment]
可以跳过插件的，只需要在项目根目录下的maven pom 文件里，注释掉不需要的组件即可。至于找不到包的问题，可以看下quick start 文档，我们在bin 目录下提供了安装jar包的脚本，以及在jars 目录下，提供了部分插件的jar包。
如果是使用1.12 版本的话，我们还提供了完整的插件包。

**Comment by fangjie-luoxi** [comment]
> 可以跳过项目根目录下的 maven pom 文件里的插件，注释我们不需要的组件可以。至于找不到包只需要的问题，可以看下快速启动文档，在 bin 目录下提供了安装jar包的脚本，以及在jars目录下，提供了部分的插件包。 如果是使用1.12版本的话，我们还提供了完整的插件包。

好的，谢谢

**Comment by zengqinchris** [comment]
支持flink1.13的版本吗？

**Comment by FlechazoW** [comment]
> 支持flink1.13的版本吗？

不支持，后续会直接支持 1.16 版本。
