### ISSUE TITLE
本地断点续传失败问题没有save checkpoint mysql_mysql

### ISSUE THREAD

**Issue by baoziaichiyu** [DTStack/chunjun#736]
**启动命令**
![1650526732730_3A313EB9-50A4-44f0-B93B-B182CA4550D1](https://user-images.githubusercontent.com/39789485/164405223-54a44bef-ff07-463a-ad8f-4d55807b4131.png)

![image](https://user-images.githubusercontent.com/39789485/164405881-6e552afe-1b76-458a-abb8-a09322a5edf4.png)

**成功日志**

![image](https://user-images.githubusercontent.com/39789485/164405300-307ccebf-42c1-4cbd-b55d-eb430747d79d.png)
**flink-conf配置**
  rest.bind-port: 8888
  state.checkpoints.dir: file:///E://flinkx-dev/checkpoints/metadata
  state.checkpoints.num-retained: 10

但是checkpoint没有存入
![1650526702771_85D3946B-19D9-4a77-A73F-4CD55B43D28C](https://user-images.githubusercontent.com/39789485/164405408-3242d366-5019-421e-bb4c-772f9b581d22.png)

![image](https://user-images.githubusercontent.com/39789485/164405719-f71cb000-cd43-41d3-b405-fbc2d2539cab.png)

**Comment by yanghuaiGit** [comment]
1.12 checkpoint启动参数需要在-confProp里配置execution.checkpointing.interval

flink.checkpoint.interval参数是1.10开启checkpoint的参数
