### ISSUE TITLE
sqlserver cdc 希望增加对数据类型smallint的支持

### ISSUE THREAD

**Issue by codingxmh** [DTStack/chunjun#739]
sqlservercdc/src/main/java/com/dtstack/flinkx/connector/sqlservercdc/convert/SqlServerCdcColumnConverter.java  

第272行，这里没有对smallint的支持

            case "INT":
            case "INTEGER":
                return (IDeserializationConverter<Integer, AbstractBaseColumn>)
                        BigDecimalColumn::new;

**Comment by WTZ468071157** [comment]
这个增加不难的，可以仿照其他类型的写法，写一个。如果有想法的话，可以贡献下这个小功能嘛？

**Comment by codingxmh** [comment]
pr 已提交

**Comment by WTZ468071157** [comment]
pr merged.
