### ISSUE TITLE
怎么让一个产品经理看懂这个并且融入到产品设计中去呢？

### ISSUE THREAD

**Issue by yaoleifly** [DTStack/chunjun#754]
如题，对 chunjun 很感兴趣，但太懂代码，希望手上的产品数据采集可以用上 chunjun ，我该怎么做呢？

**Comment by zoudaokoulife** [comment]
1:你先了解chunjun 是什么，能干啥，边界在哪里:https://github.com/DTStack/chunjun/blob/master/README_CH.md
2:了解下chunjun的使用。把demo 跑起来，这样才能知道你的产品里面该如何对接和接入；https://dtstack.github.io/chunjun-web/docs/chunjunDocs/quickstart

**Comment by zoudaokoulife** [comment]
@yaoleifly

**Comment by FlechazoW** [comment]
This issue has been open too long for us to help, if you still have the same problem, please re-open an issue.
