### ISSUE TITLE
有没有详细的文档

### ISSUE THREAD

**Issue by star10k** [DTStack/chunjun#762]
有没有详细的文档呢。
环境准备，依赖准备，配置准备，启动命令。

**Comment by WTZ468071157** [comment]
https://dtstack.github.io/chunjun-web/docs/chunjunDocs/quickstart

**Comment by star10k** [comment]
谢谢。

**Comment by star10k** [comment]
hi , 刚才通过mysql成功了。谢谢大哥。  
1. 现在有点下次是mysql库里编码有乱码  ，请问如何操作  。
2. 这个json或者sql的 语法文档有吗?谢谢

{
    "job": {
      "content": [
        {
          "reader": {
            "name": "mysqlreader",
            "parameter": {
              "column": [
                {
                  "name": "id",
                  "type": "int"
                },
                {
                  "name": "name",
                  "type": "string"
                },
                {
                  "name": "remark",
                  "type": "string"
                },
                {
                  "name": "create_time",
                  "type": "date"
                },
                {
                  "name": "update_time",
                  "type": "date"
                }
              ],
              "username": "root",
              "password": "123456",
              "connection": [
                {
                  "jdbcUrl": [
                    "jdbc:mysql://192.168.1.250:3306/chunjun?useSSL=false"
                  ],
                  "table": [
                    "simple"
                  ]
                }
              ]
            }
          },
          "writer": {
            "name": "mysqlwriter",
            "parameter": {
              "username": "root",
              "password": "123456",
              "connection": [
                {
                  "jdbcUrl": "jdbc:mysql://192.168.1.250:3306/chunjun?useSSL=false",
                  "table": [
                    "simple_sync"
                  ]
                }
              ],
              "writeMode": "insert",
              "column": [
                {
                  "name": "id",
                  "type": "int"
                },
                {
                  "name": "name",
                  "type": "string"
                },
                {
                  "name": "remark",
                  "type": "string"
                },
                {
                  "name": "create_time",
                  "type": "date"
                },
                {
                  "name": "update_time",
                  "type": "date"
                }
              ]
            }
          }
        }
      ],
      "setting": {
        "speed": {
          "channel": 1,
          "bytes": 0
        }
      }
    }
  }
