### ISSUE TITLE
mysql_mysql 上千万上亿大表同步支持故障恢复点吗

### ISSUE THREAD

**Issue by star10k** [DTStack/chunjun#770]
您好。目前我们想应用chunjun到数据同步环节  场景可能是mysql_mysql。有如下环节的考虑咨询
1.故障恢复的要求。  我看支持checkpointing。但是文档没有表示怎么配置。chunjun该如何配置呢
2.本地上千万的数据（正式运用时会上亿）  本地大概花了45分钟  如何调参提高同步速度呢？ 有这方面的文档吗。我测试在 flink standalone 本地。谢谢

**Comment by PaddyMelody** [comment]
可以在启动命令中配置confProp参数，在confProp中配置ck相关配置，比如以下命令 设置了ck的间隔是3000ms，目录是/ck
sh ./bin/flinkx -mode standalone -jobType sync -job $CHUNJUN_DIST/flinkx-examples/json/stream/stream.json -flinkxDistDir $CHUNJUN_DIST/flinkx-dist -flinkConfDir $FLINK_HOME/conf -confProp{"execution.checkpointing.interval":"3000","state.checkpoints.dir", "file:///ck/"}

调优这块可以调整一下reader插件的fetchSize，Writer插件的BatchSize，以及作业的并行度
