### ISSUE TITLE
请问 chunjun对 flink 1.14.4 的支持 有具体的release时间计划吗

### ISSUE THREAD

**Issue by VinsonWood** [DTStack/chunjun#771]
如题,麻烦大佬告知一声,谢谢!

**Comment by zoudaokoulife** [comment]
@VinsonWood  当前没有直接对flink1.14.4的支持，1.14_beta 当前是有的，开源的同学进行验证和测试过，你可以尝试下，https://github.com/DTStack/chunjun/tree/1.14_beta
