### ISSUE TITLE
JSON文件中自定义参数使用方式

### ISSUE THREAD

**Issue by aokunsang** [DTStack/chunjun#778]
在[#149 ]中提出的 json 文件中支持变量的功能，已经支持了功能。   但是我在master分支中，测试不行。
测试方式如下：
`bin/flinkx -mode local -pluginRoot /data/flinkx/plugins -job job_flinkx.json -p "date=20191122"`
JSON文件关键部分如下：
`"customSql": "select * from table where d_date = ${date}"`

请问是我的使用方式不正确么？

**Comment by aokunsang** [comment]
@[kanata163](https://github.com/kanata163) 求帮忙解答下，谢谢

**Comment by FlechazoW** [comment]
Same issue #779
