### ISSUE TITLE
sql 模式下占位符不支持吗？

### ISSUE THREAD

**Issue by jfld** [DTStack/chunjun#779]
![image](https://user-images.githubusercontent.com/21107515/167350097-11cc5b68-f134-444f-b25c-ada69d07c8b4.png)
![image](https://user-images.githubusercontent.com/21107515/167350735-57d474f2-b47f-456b-ad1a-822e1e397a5d.png)

![image](https://user-images.githubusercontent.com/21107515/167350157-a31138f3-f028-4327-93c6-221daf6bee52.png)

**Comment by aokunsang** [comment]
JSON文件貌似也不行

**Comment by FlechazoW** [comment]
Fixed with the merged pr #782
