### ISSUE TITLE
chunjun 同步 starrocks 类型转换异常

### ISSUE THREAD

**Issue by KinoMin** [DTStack/chunjun#793]
# 一、问题描述
因 chunjun 暂时没有 starrocks source plugin，对 starrocks 的数据用 mysql-x plugin 同步，starrocks 表有 DECIMAL128 类型的字段没导致转换异常。

# 问题截图
异常截图

<img width="899" alt="image" src="https://user-images.githubusercontent.com/56473938/168021170-0e210213-bcec-466b-80de-e28369281509.png">

表结构截图
<img width="256" alt="image" src="https://user-images.githubusercontent.com/56473938/168021298-d6ef8e33-8057-4408-89da-ee1d21ef11fd.png">

**Comment by FlechazoW** [comment]
Fix with pr #795
