### ISSUE TITLE
在编译过程中出现错误  flinkx-connector-kafka

### ISSUE THREAD

**Issue by 2417380371** [DTStack/chunjun#803]
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  31.553 s
[INFO] Finished at: 2022-05-13T15:07:15+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project flinkx-connector-kafka: Could not resolve dependencies for project com.dtstack.flinkx:flinkx-connector-kafka:jar:1.12-SNAPSHOT: Failure to find io.confluent:kafka-schema-registry-client:jar:5.5.2 in http://nexus.dev.dtstack.cn/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of dtstack has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :flinkx-connector-kafka

**Comment by 2417380371** [comment]
请问这个要这么解决

**Comment by FlechazoW** [comment]
重新拉去master 分支，在bin 目录下执行install_jars.sh 或者install_jars.bat 脚本
