### ISSUE TITLE
Oracle RAW Type Apply To Flink Type is TimeStamp

### ISSUE THREAD

**Issue by huyongze** [DTStack/chunjun#816]
**Describe the bug**
Oracle RAW Type Apply To Flink Type is TimeStamp，I think is Wrong

**To Reproduce**
1.Oracle hive a Raw Type Data
2.FlinkX config type raw to transfer this data
3.data trans wrong

**Expected behavior**
raw type data apply to bytes such as long raw Type
![image](https://user-images.githubusercontent.com/41050123/168987373-b3bb777a-253c-4229-a547-a463ca4a6607.png)

**Comment by FlechazoW** [comment]
Sorry for taking so long to reply to you. I think it's a bug, and could offer a pr to fix it please?
