### ISSUE TITLE
[feat][stream] Add Stream Connector, print rowData RowKind in first Column.

### ISSUE THREAD

**Issue by chaozwn** [DTStack/chunjun#822]
**Is your feature request related to a problem? Please describe.**
When I want to test the flink retract flow, I can't get the rowKind of each data, which is very troublesome in development.

**Describe the solution you'd like**
 add RowKind in print data. and we can get result like below picture.

**Describe alternatives you've considered**

**Additional context**

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/51357674/169024217-5859da7d-61fc-4694-a0f6-c7e3978709f4.png">

**Comment by FlechazoW** [comment]
PR merged.
