### ISSUE TITLE
想问一下standalone模式无法创建Job怎么处理

### ISSUE THREAD

**Issue by ty930801** [DTStack/chunjun#842]
master分支，flink版本是1.12.7  按文档上的命令去创建Job报错Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -chunjunDistDir
且flinkweb端界面没有job
去掉chunjunDistDir参数，还是会报错，flinkweb端报找不到一些类的错误。

**Comment by zoudaokoulife** [comment]
@ty930801 
1:chunjunDistDir 是新调整的参数（兼容-flinkxDistDir）。你确定下你当前的master分支是否包含对应的参数解析；
2:去掉该参数后的报错信息发下

**Comment by ty930801** [comment]
那个参数我已经改过了，开始报log4j的版本依赖那个问题，然后我也尝试了文档里将flink里的log4j依赖加了a但也没有用。然后我最后想的是把最新的源码拉下来将依赖更改为和flink一致应该就没有这个问题了，结果我发现最新拉下来的依赖已经改为跟flink一致了，然后我将dist目录复制到flink的lib下之后再启动，会报这个Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
我查了这个说是Java版本和Javac版本不一致，我之前自己服务器装的是1.8.0_333这个版本，然后本地是1.8.0_202，我最后换为一致还是不行。
搞不太清楚是什么问题了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DTStack/chunjun"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月23日(星期一) 晚上6:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DTStack/chunjun] 想问一下standalone模式无法创建Job怎么处理 (Issue #842)





 
@ty930801
 1:chunjunDistDir 是新调整的参数（兼容-flinkxDistDir）。你确定下你当前的master分支是否包含对应的参数解析；
 2:去掉该参数后的报错信息发下

**Comment by zoudaokoulife** [comment]
@ty930801 错误是在本地提交的时候抛出的“Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes”？还是远程服务器上。

**Comment by FlechazoW** [comment]
远程服务器是什么系统呢？centos 7 还是其他的呢？对应JDK 是 open jdk还是其他的呢？能否提供详细的环境信息？

**Comment by lvyanquan** [comment]
reason of this problem is that MANIFEST.MF wasn't excluded in jar of chunjun-ddl-mysql-master 
<img width="1206" alt="Screen Shot 2022-06-01 at 10 27 01 AM" src="https://user-images.githubusercontent.com/38547014/171315765-9fbfb4de-81f5-4252-a1f9-f5759f042165.png">
