### ISSUE TITLE
编译通过之后没有tar生成？

### ISSUE THREAD

**Issue by caosuwenwu** [DTStack/chunjun#850]
### 编译环境liunx centos7

INFO] Executed tasks
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ChunJun 1.12-SNAPSHOT:
[INFO] 
[INFO] ChunJun ............................................ SUCCESS [  1.035 s]
[INFO] ChunJun : Core ..................................... SUCCESS [ 21.139 s]
[INFO] ChunJun : Connectors ............................... SUCCESS [  0.315 s]
[INFO] ChunJun : Connectors : Stream ...................... SUCCESS [  3.278 s]
[INFO] ChunJun : Connectors : Kafka ....................... SUCCESS [  9.959 s]
[INFO] ChunJun : Connectors : EMQX ........................ SUCCESS [  3.502 s]
[INFO] ChunJun : Connectors : JDBC ........................ SUCCESS [  5.123 s]
[INFO] ChunJun : Connectors : MySQL ....................... SUCCESS [  4.238 s]
[INFO] ChunJun : Connectors : Oracle ...................... SUCCESS [  4.736 s]
[INFO] ChunJun : Connectors : SqlServer ................... SUCCESS [  6.983 s]
[INFO] ChunJun : Connectors : DB2 ......................... SUCCESS [  4.845 s]
[INFO] ChunJun : Connectors : Postgresql .................. SUCCESS [  4.564 s]
[INFO] ChunJun : Connectors : GBase ....................... SUCCESS [  4.349 s]
[INFO] ChunJun : Connectors : Kingbase .................... SUCCESS [  4.012 s]
[INFO] ChunJun : Connectors : Greenplum ................... SUCCESS [  3.979 s]
[INFO] ChunJun : Connectors : Dm .......................... SUCCESS [  4.032 s]
[INFO] ChunJun : Connectors : ClickHouse .................. SUCCESS [  4.069 s]
[INFO] ChunJun : Connectors : SAP HANA .................... SUCCESS [  3.785 s]
[INFO] ChunJun : Connectors : Doris ....................... SUCCESS [  4.969 s]
[INFO] ChunJun : Connectors : InfluxDB .................... SUCCESS [  3.235 s]
[INFO] ChunJun : Connectors : StarRocks ................... SUCCESS [  2.392 s]
[INFO] ChunJun : Connectors : OceanBase ................... SUCCESS [  4.096 s]
[INFO] ChunJun : Connectors : Cassandra ................... SUCCESS [  4.432 s]
[INFO] ChunJun : Connectors : File ........................ SUCCESS [  3.149 s]
[INFO] ChunJun : Connectors : Filesystem .................. SUCCESS [  3.492 s]
[INFO] ChunJun : Connectors : Ftp ......................... SUCCESS [ 10.726 s]
[INFO] ChunJun : Connectors : HDFS ........................ SUCCESS [ 10.385 s]
[INFO] ChunJun : Connectors : Hive ........................ SUCCESS [ 15.029 s]
[INFO] ChunJun : Connectors : Inceptor .................... SUCCESS [ 17.421 s]
[INFO] ChunJun : Connectors : HBase base .................. SUCCESS [  3.344 s]
[INFO] ChunJun : Connectors : ElasticSearch base .......... SUCCESS [  2.570 s]
[INFO] ChunJun : Connectors : ElasticSearch7 .............. SUCCESS [ 11.214 s]
[INFO] ChunJun : Connectors : Redis ....................... SUCCESS [  4.571 s]
[INFO] ChunJun : Connectors : MongoDB ..................... SUCCESS [  3.483 s]
[INFO] ChunJun : Connectors : Solr ........................ SUCCESS [  3.780 s]
[INFO] ChunJun : Connectors : Kudu ........................ SUCCESS [  7.043 s]
[INFO] ChunJun : Connectors : Binlog ...................... SUCCESS [  6.138 s]
[INFO] ChunJun : Connectors : Oracle LogMiner ............. SUCCESS [  8.010 s]
[INFO] ChunJun : Connectors : SqlServer CDC ............... SUCCESS [  3.111 s]
[INFO] ChunJun : Connectors : PGWal ....................... SUCCESS [  5.523 s]
[INFO] ChunJun : Connectors : Http ........................ SUCCESS [  3.884 s]
[INFO] ChunJun : Connectors : Socket ...................... SUCCESS [  3.638 s]
[INFO] ChunJun : Connectors : MySQL Distribute ............ SUCCESS [  4.683 s]
[INFO] ChunJun : Clients .................................. SUCCESS [ 30.829 s]
[INFO] ChunJun : Formats .................................. SUCCESS [  0.162 s]
[INFO] ChunJun : Docker ................................... SUCCESS [  3.328 s]
[INFO] ChunJun : Metrics .................................. SUCCESS [  0.076 s]
[INFO] ChunJun : Metrics : Rdb ............................ SUCCESS [  3.282 s]
[INFO] ChunJun : Metrics : Prometheus ..................... SUCCESS [  3.783 s]
[INFO] ChunJun : Metrics : MYSQL .......................... SUCCESS [  2.484 s]
[INFO] ChunJun : Dirty .................................... SUCCESS [  0.052 s]
[INFO] ChunJun : Dirty : Log .............................. SUCCESS [  3.039 s]
[INFO] ChunJun : Dirty : Mysql ............................ SUCCESS [  2.733 s]
[INFO] ChunJun : Restore .................................. SUCCESS [  0.070 s]
[INFO] ChunJun : Restore : Common ......................... SUCCESS [  2.715 s]
[INFO] ChunJun : Restore : MySQL .......................... SUCCESS [ 20.782 s]
[INFO] ChunJun : SQL ...................................... SUCCESS [  0.030 s]
[INFO] ChunJun : DDL : SQL ................................ SUCCESS [ 23.436 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:45 min (Wall Clock)
[INFO] Finished at: 2022-05-21T09:49:44+08:00
[INFO] ------------------------------------------------------------------------

### 也没有生成统一一个部署包的文件夹，像下图这样的
![1653099927(1)](https://user-images.githubusercontent.com/31889672/169630805-dff2a41c-957f-496c-87e7-404022efcf91.png)

**Comment by FlechazoW** [comment]
纯钧没有部署包，可以看下这份文档 https://dtstack.github.io/chunjun-web/docs/chunjunDocs/quickstart

**Comment by 20100507** [comment]
新版的是不是把人大金仓删除了?因为侵权么？
