### ISSUE TITLE
ColumnType TimestampZ is missing

### ISSUE THREAD

**Issue by PaddyMelody** [DTStack/chunjun#853]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/46181516/169736467-6aeafcc9-61cd-409c-bb24-2c1bfb17c73d.png">
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/46181516/169736513-779cc445-c39d-4c45-99f4-4a5990a61d61.png">

**Comment by FlechazoW** [comment]
PR. merged.
