### ISSUE TITLE
Doris writer get error code -235

### ISSUE THREAD

**Issue by meng1222** [DTStack/chunjun#870]
**Describe the bug**

DirtyDataEntry[jobId='5e607b3c4075a66d746699cf3294ca64', jobName='P_doris_sales_test_2022_05_17_26_18-doris_sales_test-20220517000000', operatorName='Sink: dorissinkfactory', dirtyContent='null', errorMessage='com.dtstack.flinkx.throwable.WriteRecordException:
com.dtstack.flinkx.throwable.WriteRecordException: write record failed.
java.io.IOException: stream load error: {"errorURL":null,"message":"wait close failed. NodeChannel[1539524-10008], load_id=d4499d49e7d24cc1-fcb8d9a2fe618b89, txn_id=38873401, node=10008:8060, add batch req success but status isn't ok, err: tablet writer write failed, tablet_id=1539539, txn_id=38873401, err=-235","status":"Fail","TxnId":38873401,"Label":"flinkx_connector_20220517_163131_3b8ea8d6fe324ca8aaff048e48649efe","Status":"Fail","ExistingJobStatus":null,"Message":"wait close failed. NodeChannel[1539524-10008], load_id=d4499d49e7d24cc1-fcb8d9a2fe618b89, txn_id=38873401, node=10008:8060, add batch req success but status isn't ok, err: tablet writer write failed, tablet_id=1539539, txn_id=38873401, err=-235","NumberTotalRows":0,"NumberLoadedRows":0,"NumberFilteredRows":0,"NumberUnselectedRows":0,"LoadBytes":130,"LoadTimeMs":13,"BeginTxnTimeMs":0,"StreamLoadPutTimeMs":0,"ReadDataTimeMs":0,"WriteDataTimeMs":12,"CommitAndPublishTimeMs":0,"ErrorURL":null}
	at com.dtstack.flinkx.connector.doris.sink.DorisHttpOutputFormat.writeSingleRecordInternal(DorisHttpOutputFormat.java:90)
	at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:456)
	at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.writeRecord(BaseRichOutputFormat.java:252)
	at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.writeRecord(BaseRichOutputFormat.java:86)
	at com.dtstack.flinkx.sink.DtOutputFormatSinkFunction.invoke(DtOutputFormatSinkFunction.java:117)

**Comment by meng1222** [comment]
In the scenario of multi-threading or a large number of write requests in a short time, doris will cause the backend to reach the maximum number of tablet versions (controlled by the max_tablet_version_num configuration) when the backend is compressed, triggering an error of -235.

**Comment by FlechazoW** [comment]
PR merged.
