### ISSUE TITLE
failed to submit job in standalone mode

### ISSUE THREAD

**Issue by lvyanquan** [DTStack/chunjun#897]
**Describe the bug**
I followed the steps as https://dtstack.github.io/chunjun-web/docs/chunjunDocs/quickstart had showed,  but failed to submit job in standalone mode.

**To Reproduce**
Some problems:
1. no file named flinkx but a file named start-chunjun under the directory of bin.
2. no jars that included class of com.dtstack.chunjun.client.Launcher, I guess that some jars were missed.
3. I put chunjun-dist to lib of Flink, howerver, the flink standalone cluster failed to start.

**Comment by FlechazoW** [comment]
What problem are you having? Can you describe more detail?

**Comment by lvyanquan** [comment]
Using the jar of  https://github.com/DTStack/chunjun/releases/tag/v1.12.3, 
following the document of https://dtstack.github.io/chunjun-web/docs/chunjunDocs/quickstart#standalone, 
I found that 
1. no file named flinkx, as the start command is 
``` 
sh ./bin/flinkx -mode standalone -jobType sync -job $CHUNJUN_DIST/flinkx-examples/json/stream/stream.json -flinkxDistDir $CHUNJUN_DIST/flinkx-dist -flinkConfDir $FLINK_HOME/conf
```
2. using ./bin/start-chunjun, got error message 
```
Error: Could not find or load main class com.dtstack.chunjun.client.Launcher
```
3. same as https://github.com/DTStack/chunjun/issues/842

**Comment by FlechazoW** [comment]
Use the latest release.
