### ISSUE TITLE
Verify Job Configuration Parameter error

### ISSUE THREAD

**Issue by huyuanfeng2018** [DTStack/chunjun#899]
**Describe the bug**
An error occurred in the code in the validation check of the writer parameter after submitting the task
code 
```
  Map<String, Object> writerParameter = reader.getParameter();
        Preconditions.checkNotNull(
                writerParameter,
                "[parameter] under [writer] in the task script is empty, please check the configuration of the task script.");
```
This should be to verify the writer parameters but inherit the reader

**Comment by huyuanfeng2018** [comment]
I will file a PR later to fix this bug

**Comment by FlechazoW** [comment]
> I will file a PR later to fix this bug

Thanks a lot.
