### ISSUE TITLE
如何贡献代码

### ISSUE THREAD

**Issue by biandou1313** [DTStack/chunjun#900]
## Development Task
1、chunjun1.12 已经修复hive无法指定分区
2、chunjun1.12已经扩展hive读
3、chunjun1.12已经扩展robbitmq

**Comment by FlechazoW** [comment]
你好，没有太理解这个issue的意思呢。

**Comment by biandou1313** [comment]
如何提交代码



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月31日(星期二) 下午3:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DTStack/chunjun] 如何贡献代码 (Issue #900)





 
你好，没有太理解这个issue的意思呢。

**Comment by FlechazoW** [comment]
可以参考下这个文章～https://dtstack.github.io/chunjun-web/docs/chunjunDocs/contribute-pr

**Comment by biandou1313** [comment]
ok




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月31日(星期二) 下午3:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DTStack/chunjun] 如何贡献代码 (Issue #900)





 
可以参考下这个文章～https://dtstack.github.io/chunjun-web/docs/chunjunDocs/contribute-pr
