### ISSUE TITLE
A spelling mistake ：BigIntegerAccmulator

### ISSUE THREAD

**Issue by PaddyMelody** [DTStack/chunjun#906]
**Is your feature request related to a problem? Please describe.**
A spelling mistake,the correct spelling should be BigIntegerAccumulator
<img width="686" alt="image" src="https://user-images.githubusercontent.com/46181516/171346438-e32750c8-e806-48f7-8765-b2044dbb3f7a.png">

**Comment by FlechazoW** [comment]
PR merged.
