### ISSUE TITLE
where不生效是怎么回事

### ISSUE THREAD

**Issue by star10k** [DTStack/chunjun#916]
where不生效是怎么回事  
                                         大哥们 怎么弄 
Reader：
               ...
              "username": "root",
              "password": "**********",
              "fetchSize": 10,
              "where": " create_time > '2022-05-04 18:35:11' ", // 这句不生效
              "connection": [
                {
                  "jdbcUrl": [
                    "xxxx"
                  ],
                  "table": [
                    "xxxx"
                  ]
                }
              ]

**Comment by lvyanquan** [comment]
你可以先在Flink运行日志中查找当前执行的sql是什么，关键词“Executing sql is:”

**Comment by star10k** [comment]
flink-root-taskexecutor-2-host231.log:2022-06-06 14:24:54,858 INFO  com.dtstack.flinkx.connector.mysql.source.MysqlInputFormat   [] - Executing sql is: 'SELECT `id`, `name`, `remark`, `status`, `create_time`, `update_time` FROM `simple` WHERE `id` >= 48048398 AND `id` < 48049023'
flink-root-taskexecutor-2-host231.log.1:2022-06-06 14:24:30,127 INFO  com.dtstack.flinkx.connector.mysql.source.MysqlInputFormat   [] - Executing sql is: 'SELECT `id`, `name`, `remark`, `status`, `create_time`, `update_time` FROM `simple` WHERE `id` >= 48048398 AND `id` < 48049023'
flink-root-taskexecutor-2-host231.log.1:2022-06-06 14:24:42,081 INFO  com.dtstack.flinkx.connector.mysql.source.MysqlInputFormat   [] - Executing sql is: 'SELECT `id`, `name`, `remark`, `status`, `create_time`, `update_time` FROM `simple` WHERE `id` >= 48047773 AND `id` < 48048398'
flink-root-taskexecutor-2-host231.log.1:2022-06-06 14:24:42,176 INFO  com.dtstack.flinkx.connector.mysql.source.MysqlInputFormat   [] - Executing sql is: 'SELECT `id`, `name`, `remark`, `status`, `create_time`, `update_time` FROM `simple` WHERE `id` >= 48049648 AND `id` < 48050273'
flink-root-taskexecutor-2-host231.log.1:2022-06-06 14:24:42,210 INFO  com.dtstack.flinkx.connector.mysql.source.MysqlInputFormat   [] - Executing sql is: 'SELECT `id`, `name`, `remark`, `status`, `create_time`, `update_time` FROM `simple` WHERE `id` >= 48050273 AND `id` < 48050898'
flink-root-taskexecutor-2-host231.log.1:2022-06-06 14:24:42,506 INFO  com.dtstack.flinkx.connector.mysql.source.MysqlInputFormat   [] - Executing sql is: 'SELECT `id`, `name`, `remark`, `status`, `create_time`, `update_time` FROM `simple` WHERE `id` >= 48047148 AND `id` < 48047773'
flink-root-taskexecutor-2-host231.log.1:2022-06-06 14:24:42,592 INFO  com.dtstack.flinkx.connector.mysql.source.MysqlInputFormat   [] - Executing sql is: 'SELECT `id`, `name`, `remark`, `status`, `create_time`, `update_time` FROM `simple` WHERE `id` >= 48050898 AND `id` < 48051523'
flink-root-taskexecutor-2-host231.log.1:2022-06-06 14:24:42,654 INFO  com.dtstack.flinkx.connector.mysql.source.MysqlInputFormat   [] - Executing sql is: 'SELECT `id`, `name`, `remark`, `status`, `create_time`, `update_time` FROM `simple` WHERE `id` >= 48051523'
flink-root-taskexecutor-2-host231.log.1:2022-06-06 14:24:42,733 INFO  com.dtstack.flinkx.connector.mysql.source.MysqlInputFormat   [] - Executing sql is: 'SELECT `id`, `name`, `remark`, `status`, `create_time`, `update_time` FROM `simple` WHERE `id` >= 48049023 AND `id` < 48049648'
flink-root-taskexecutor-3-host231.log:2022-06-06 16:29:22,937 INFO  com.dtstack.flinkx.connector.mysql.source.MysqlInputFormat   [] - Executing sql is: 'SELECT `id`, `name`, `remark`, `status`, `create_time`, `update_time` FROM `simple` WHERE  create_time > '2022-05-04 18:35:11'  AND `id` >= 48052149'
flink-root-taskexecutor-3-host231.log:2022-06-06 16:29:23,222 INFO  com.dtstack.flinkx.connector.mysql.source.MysqlInputFormat   [] - Executing sql is: 'SELECT `id`, `name`, `remark`, `status`, `create_time`, `update_time` FROM `simple` WHERE  create_time > '2022-05-04 18:35:11'  AND `id` >= 48052148 AND `id` < 48052149'
flink-root-taskexecutor-3-host231.log.1:2022-06-06 14:48:31,545 INFO  com.dtstack.flinkx.connector.mysql.source.MysqlInputFormat   [] - Executing sql is: 'SELECT `id`, `name`, `remark`, `status`, `create_time`, `update_time` FROM `simple` WHERE `id` >= 48051523'
flink-root-taskexecutor-3-host231.log.1:2022-06-06 14:48:31,652 INFO  com.dtstack.flinkx.connector.mysql.source.MysqlInputFormat   [] - Executing sql is: 'SELECT `id`, `name`, `remark`, `status`, `create_time`, `update_time` FROM `simple` WHERE `id` >= 48049648 AND `id` < 48050273'
flink-root-taskexecutor-3-host231.log.1:2022-06-06 14:48:31,706 INFO  com.dtstack.flinkx.connector.mysql.source.MysqlInputFormat   [] - Executing sql is: 'SELECT `id`, `name`, `remark`, `status`, `create_time`, `update_time` FROM `simple` WHERE `id` >= 48048398 AND `id` < 48049023'
flink-root-taskexecutor-3-host231.log.1:2022-06-06 14:48:31,737 INFO  com.dtstack.flinkx.connector.mysql.source.MysqlInputFormat   [] - Executing sql is: 'SELECT `id`, `name`, `remark`, `status`, `create_time`, `update_time` FROM `simple` WHERE `id` >= 48050273 AND `id` < 48050898'
flink-root-taskexecutor-3-host231.log.1:2022-06-06 14:48:31,813 INFO  com.dtstack.flinkx.connector.mysql.source.MysqlInputFormat   [] - Executing sql is: 'SELECT `id`, `name`, `remark`, `status`, `create_time`, `update_time` FROM `simple` WHERE `id` >= 48047773 AND `id` < 48048398'
flink-root-taskexecutor-3-host231.log.1:2022-06-06 14:48:31,966 INFO  com.dtstack.flinkx.connector.mysql.source.MysqlInputFormat   [] - Executing sql is: 'SELECT `id`, `name`, `remark`, `status`, `create_time`, `update_time` FROM `simple` WHERE `id` >= 48050898 AND `id` < 48051523'
flink-root-taskexecutor-3-host231.log.1:2022-06-06 14:48:32,001 INFO  com.dtstack.flinkx.connector.mysql.source.MysqlInputFormat   [] - Executing sql is: 'SELECT `id`, `name`, `remark`, `status`, `create_time`, `update_time` FROM `simple` WHERE `id` >= 48047148 AND `id` < 48047773'
flink-root-taskexecutor-3-host231.log.1:2022-06-06 14:48:32,116 INFO  com.dtstack.flinkx.connector.mysql.source.MysqlInputFormat   [] - Executing sql is: 'SELECT `id`, `name`, `remark`, `status`, `create_time`, `update_time` FROM `simple` WHERE `id` >= 48049023 AND `id` < 48049648'

**Comment by PaddyMelody** [comment]
可以尝试下使用最新的master

**Comment by star10k** [comment]
> 可以尝试下使用最新的master

我试下  谢谢

**Comment by star10k** [comment]
> 

谢谢。最新的master  已解决。
