### ISSUE TITLE
JDBC startLocation/endLocation was mistakenly lost

### ISSUE THREAD

**Issue by PaddyMelody** [DTStack/chunjun#919]
## StartLocation lost
incremental mode,useMaxFunc=true or endLocation is not null, StartLocation has been lost
<img width="954" alt="image" src="https://user-images.githubusercontent.com/46181516/172185952-9ec221de-a950-48f3-a836-a1646d97fced.png">
## EndLocation lost
EndLocation is lost during recovery from checkpoint/ Savepoint
<img width="817" alt="image" src="https://user-images.githubusercontent.com/46181516/172187022-769a3a5a-8195-4050-bf69-14ef58322106.png">

**Comment by FlechazoW** [comment]
PR merged.
