### ISSUE TITLE
I can't execute jobs successfully via Release 1.12.4.Why?

### ISSUE THREAD

**Issue by wzh6666** [DTStack/chunjun#921]
![image](https://user-images.githubusercontent.com/24769990/172290094-ba3592ab-de46-4e94-9831-666d76e7130c.png)

![lQLPJxZhZNCHrSvNAk3NChywRb_tEIa2-fQCoKLlmID7AA_2588_589](https://user-images.githubusercontent.com/24769990/172290158-5f57f036-df9a-46dc-ba40-17a548b2bd51.png)
![lQLPJxZhZNCHrYrNAljNCiSw8oWtnPQQfTcCoKLlmMDhAA_2596_600](https://user-images.githubusercontent.com/24769990/172290187-e0117328-4248-4164-a2a7-7e70866c88d4.png)

**Comment by FlechazoW** [comment]
I executed jobs successfully via release 1.12.4. There is my result.
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/35768015/172309749-0e5b457c-7e56-4fd4-a657-7be5d777dbbc.png">

<img width="1341" alt="image" src="https://user-images.githubusercontent.com/35768015/172310224-708baf5f-34d5-4ff9-b808-8c70a85b5b4c.png">

And this my execute command:  sh bin/start-chunjun -mode local -jobType sync -job /Users/wtz/job_place/json/1.12/stream-stream.json -chunjunDistDir ./
