### ISSUE TITLE
能否增加kudu支持

### ISSUE THREAD

**Issue by tduslost** [DTStack/chunjun#924]
flink是支持kudu的, 能否让纯钧也支持? 非常感谢

**Comment by HiLany** [comment]
是chunjun现有kudu connector不支持某些功能还是说版本太低？

这份文档是否能让你找到想要的？
https://dtstack.github.io/chunjun-web/docs/chunjunDocs/connectors/kudu/kudu-source

**Comment by FlechazoW** [comment]
纯钧已经存在kudu 插件，支持kudu数据源的sql计算及同步。
