### ISSUE TITLE
入门示例Local模式下提交命令执行失败

### ISSUE THREAD

**Issue by njian-github** [DTStack/chunjun#926]
入门案例中示例命令已过时
![image](https://user-images.githubusercontent.com/37692792/172574686-bd2c1e95-3287-4d94-9f28-b90eefb6711a.png)
修改命令后依然执行失败
`sh ./bin/start-chunjun -mode local -jobType sync -job ./chunjun-examples/json/stream/stream.json -chunjunDistDir ./chunjun-dist`

![image](https://user-images.githubusercontent.com/37692792/172575348-72f9431f-53d3-4226-8d3e-71186cdf0090.png)

**Comment by PaddyMelody** [comment]
This is a bug and we will fix it as soon as possible
Thank you for your issue
