### ISSUE TITLE
flink metrics 偶发性写不进prometheus

### ISSUE THREAD

**Issue by KinoMin** [DTStack/chunjun#947]
# 问题说明
在 Taier 中运行数据同步(向导模式), 在 Yarn Session 配置中配置了 Prometheus 相关的配置，在运行时，chunjun 时不时出现不能将 metric 写入到 prometheus 中。

# 环境
- apache hadoop3.1.3
- chunjun master branch
- taier master branch

# 相关截图
taier 控制台输出
<img width="956" alt="image" src="https://user-images.githubusercontent.com/56473938/173550043-e0005887-ff49-4f91-8f37-05a4e636725a.png">

taier debug 参数
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/56473938/173550238-1be91efb-eaf6-4db3-9700-878a820cc361.png">

# 问题
起初怀疑可能是参数没有被传到 chunjun 中，但是在debug的时候发现 prometheus 的参数传递了，请问这种偶发性问题我需要怎么样排查下

**Comment by FlechazoW** [comment]
可以debug看下ChunJun的代码，有问题应该是在查询val的地方

**Comment by KinoMin** [comment]
chunjun代码没问题，换了一套集群重搭了一套监控，就可以了，感谢大佬的帮助。
