### ISSUE TITLE
OracleSink写入多表Column映射出错导致写入失败

### ISSUE THREAD

**Issue by EngonVHKxZ** [DTStack/chunjun#948]
## 数据库表结构

| 表空间 | 表名 | 字段名 | 字段类型 |
| :-: | :-: | :-: | :-: |
| LOGMINER_USER| ZJH_LG_FROM2|        |          |
|  |  | ID | VARCHAR2 |
|  |  | NAME | VARCHAR2 |
| LOGMINER_USER| ZJH_LG_FROM3|        |          |
|  |  | ID | VARCHAR2 |
|  |  | AGE | NUMBER |
| LOGMINER_USER| ZJH_LG_TO2|        |          |
|  |  | TO2_ID| VARCHAR2 |
|  |  | NAME | VARCHAR2 |
| LOGMINER_USER| ZJH_LG_TO3|        |          |
|  |  | TO3_ID| VARCHAR2 |
|  |  | AGE | NUMBER |

## 配置文件

```
{
  "job": {
    "content": [
      {
        "reader": {
          "parameter": {
            "jdbcUrl": "jdbc:oracle:thin:@192.168.4.76:1522:helowin",
            "username": "logminer_user",
            "password": "lg_pwd",
            "supportAutoAddLog": false,
            "table": ["LOGMINER_USER.ZJH_LG_FROM2","LOGMINER_USER.ZJH_LG_FROM3"],
            "cat": "INSERT,UPDATE,DELETE",
            "split" : true,
            "readPosition" : "CURRENT",
            "queryTimeout": 3000
          },
          "name": "oraclelogminerreader"
        },
        "writer": {
          "parameter": {
            "writeMode":"update",
            "updateKey": {
              "key": ["TO2_ID","TO3_ID"]
            },
            "allReplace": true,
            "username": "logminer_user",
            "password": "lg_pwd",
            "connection": [{
              "schema": "LOGMINER_USER",
              "jdbcUrl": "jdbc:oracle:thin:@192.168.4.76:1523:helowin",
              "table": ["ZJH_LG_TO2","ZJH_LG_TO3"]
            }],
            "column": []
          },
          "name": "oraclewriter"
        },
        "nameMapping":{
          "schemaMappings":{
            "LOGMINER_USER":"LOGMINER_USER"
          },
          "tableMappings":{
            "LOGMINER_USER":{
              "ZJH_LG_FROM2": "ZJH_LG_TO2",
              "ZJH_LG_FROM3": "ZJH_LG_TO3"
            }
          },
          "fieldMappings":{
            "LOGMINER_USER":{
              "ZJH_LG_FROM2":{
                "ID": "TO2_ID",
                "NAME": "NAME"
              },
              "ZJH_LG_FROM3":{
                "ID": "TO3_ID",
                "AGE": "AGE"
              }
            }
          }
        }
      }
    ],
    "setting" : {
      "speed" : {
        "bytes" : 0,
        "channel" : 1
      },
      "errorLimit": {
        "record": 1
      },
      "restore": {
        "maxRowNumForCheckpoint": 0,
        "isRestore": false,
        "restoreColumnName": "",
        "restoreColumnIndex": 0
      },
      "log": {
        "isLogger": true,
        "level": "debug",
        "path": "",
        "pattern": ""
      }
    }
  }
}
```

**Comment by EngonVHKxZ** [comment]
updateKey同样也有问题     ZJH_LG_TO2表动态生成的语句中   错误的引用了ZJH_LG_FROM3的TO3_ID属性

**Comment by PaddyMelody** [comment]
You can try this instead
`{
  "job": {
    "content": [
      {
        "reader": {
          "parameter": {
            "jdbcUrl": "jdbc:oracle:thin:@192.168.4.76:1522:helowin",
            "username": "logminer_user",
            "password": "lg_pwd",
            "supportAutoAddLog": false,
            "table": ["LOGMINER_USER.ZJH_LG_FROM2","LOGMINER_USER.ZJH_LG_FROM3"],
            "cat": "INSERT,UPDATE,DELETE",
            "split" : true,
            "readPosition" : "CURRENT",
            "queryTimeout": 3000
          },
          "name": "oraclelogminerreader"
        },
        "writer": {
          "parameter": {
           "writeMode":"insert",
            "updateKey":[],
            "allReplace": true,
            "username": "logminer_user",
            "password": "lg_pwd",
            "connection": [{
              "schema": "LOGMINER_USER",
              "jdbcUrl": "jdbc:oracle:thin:@192.168.4.76:1523:helowin",
              "table": ["ZJH_LG_TO2","ZJH_LG_TO3"]
            }],
            "column": []
          },
          "name": "oraclewriter"
        },
        "nameMapping":{
          "schemaMappings":{
            "LOGMINER_USER":"LOGMINER_USER"
          },
          "tableMappings":{
            "LOGMINER_USER":{
              "ZJH_LG_FROM2": "ZJH_LG_TO2",
              "ZJH_LG_FROM3": "ZJH_LG_TO3"
            }
          },
          "fieldMappings":{
            "LOGMINER_USER":{
              "ZJH_LG_FROM2":{
                "ID": "TO2_ID",
                "NAME": "NAME"
              },
              "ZJH_LG_FROM3":{
                "ID": "TO3_ID",
                "AGE": "AGE"
              }
            }
          }
        }
      }
    ],
    "setting" : {
      "speed" : {
        "bytes" : 0,
        "channel" : 1
      },
      "errorLimit": {
        "record": 1
      },
      "restore": {
        "maxRowNumForCheckpoint": 0,
        "isRestore": false,
        "restoreColumnName": "",
        "restoreColumnIndex": 0
      },
      "log": {
        "isLogger": true,
        "level": "debug",
        "path": "",
        "pattern": ""
      }
    }
  }
}`

**Comment by PaddyMelody** [comment]
@chaozwn 这种多表还原的场景，其实uniqueKey是不需要配置的
下面的这行代码会导致uniqueKey未配时抛出空指针异常
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/46181516/173567454-b6005abe-fce4-4204-bcf0-82d63bb18cbb.png">

**Comment by PaddyMelody** [comment]
`{
  "job": {
    "content": [
      {
        "reader": {
          "parameter": {
            "jdbcUrl": "jdbc:oracle:thin:@192.168.4.76:1522:helowin",
            "username": "logminer_user",
            "password": "lg_pwd",
            "supportAutoAddLog": false,
            "table": [
              "LOGMINER_USER.ZJH_LG_FROM2",
              "LOGMINER_USER.ZJH_LG_FROM3"
            ],
            "cat": "INSERT,UPDATE,DELETE",
            "split": true,
            "readPosition": "CURRENT",
            "queryTimeout": 3000
          },
          "name": "oraclelogminerreader"
        },
        "writer": {
          "parameter": {
            "writeMode": "insert",
            "updateKey": [],
            "allReplace": true,
            "username": "logminer_user",
            "password": "lg_pwd",
            "connection": [
              {
                "schema": "LOGMINER_USER",
                "jdbcUrl": "jdbc:oracle:thin:@192.168.4.76:1523:helowin",
                "table": [
                  "*"
                ]
              }
            ],
            "column": []
          },
          "name": "oraclewriter"
        },
        "nameMapping": {
          "schemaMappings": {
            "LOGMINER_USER": "LOGMINER_USER"
          },
          "tableMappings": {
            "LOGMINER_USER": {
              "ZJH_LG_FROM2": "ZJH_LG_TO2",
              "ZJH_LG_FROM3": "ZJH_LG_TO3"
            }
          },
          "fieldMappings": {
            "LOGMINER_USER": {
              "ZJH_LG_FROM2": {
                "ID": "TO2_ID",
                "NAME": "NAME"
              },
              "ZJH_LG_FROM3": {
                "ID": "TO3_ID",
                "AGE": "AGE"
              }
            }
          }
        }
      }
    ],
    "setting": {
      "speed": {
        "bytes": 0,
        "channel": 1
      },
      "errorLimit": {
        "record": 1
      },
      "restore": {
        "maxRowNumForCheckpoint": 0,
        "isRestore": false,
        "restoreColumnName": "",
        "restoreColumnIndex": 0
      },
      "log": {
        "isLogger": true,
        "level": "debug",
        "path": "",
        "pattern": ""
      }
    }
  }
}`
这样呢？数据还原要还原的表应该是设置在reader插件中的，在writer插件里无需填写table信息。
你的代码应该走到这里，以避免column信息的干扰
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/46181516/173872421-4055120d-9c7e-41c7-ae64-b58f9879109f.png">

**Comment by chaozwn** [comment]
Is the problem solved, if not, let me help.

**Comment by EngonVHKxZ** [comment]
> @chaozwn 这种多表还原的场景，其实uniqueKey是不需要配置的 下面的这行代码会导致uniqueKey未配时抛出空指针异常 <img alt="image" width="1021" src="https://user-images.githubusercontent.com/46181516/173567454-b6005abe-fce4-4204-bcf0-82d63bb18cbb.png">

报空指针的原因是这个
![1655347059(1)](https://user-images.githubusercontent.com/74673814/173979446-4ec4f34e-ddbf-403d-998d-f7bd75252168.png)

**Comment by EngonVHKxZ** [comment]
> Is the problem solved, if not, let me help.

你好   这边遇到的问题还没有解决    请问你是Oraclewriter这边相关代码的贡献者吗？

**Comment by EngonVHKxZ** [comment]
> `{ "job": { "content": [ { "reader": { "parameter": { "jdbcUrl": "jdbc:oracle:thin:@192.168.4.76:1522:helowin", "username": "logminer_user", "password": "lg_pwd", "supportAutoAddLog": false, "table": [ "LOGMINER_USER.ZJH_LG_FROM2", "LOGMINER_USER.ZJH_LG_FROM3" ], "cat": "INSERT,UPDATE,DELETE", "split": true, "readPosition": "CURRENT", "queryTimeout": 3000 }, "name": "oraclelogminerreader" }, "writer": { "parameter": { "writeMode": "insert", "updateKey": [], "allReplace": true, "username": "logminer_user", "password": "lg_pwd", "connection": [ { "schema": "LOGMINER_USER", "jdbcUrl": "jdbc:oracle:thin:@192.168.4.76:1523:helowin", "table": [ "*" ] } ], "column": [] }, "name": "oraclewriter" }, "nameMapping": { "schemaMappings": { "LOGMINER_USER": "LOGMINER_USER" }, "tableMappings": { "LOGMINER_USER": { "ZJH_LG_FROM2": "ZJH_LG_TO2", "ZJH_LG_FROM3": "ZJH_LG_TO3" } }, "fieldMappings": { "LOGMINER_USER": { "ZJH_LG_FROM2": { "ID": "TO2_ID", "NAME": "NAME" }, "ZJH_LG_FROM3": { "ID": "TO3_ID", "AGE": "AGE" } } } } } ], "setting": { "speed": { "bytes": 0, "channel": 1 }, "errorLimit": { "record": 1 }, "restore": { "maxRowNumForCheckpoint": 0, "isRestore": false, "restoreColumnName": "", "restoreColumnIndex": 0 }, "log": { "isLogger": true, "level": "debug", "path": "", "pattern": "" } } } }` 这样呢？数据还原要还原的表应该是设置在reader插件中的，在writer插件里无需填写table信息。 你的代码应该走到这里，以避免column信息的干扰 <img alt="image" width="1115" src="https://user-images.githubusercontent.com/46181516/173872421-4055120d-9c7e-41c7-ae64-b58f9879109f.png">

你好  这个配置文件不行   在运行的时候会复现上面说的updateKey空指针异常     出现的原因就是writer->parameter->connection->table: [ "*" ]          然后关于这个updateKey    你给的数据类型和OracleSink文档中给的例子不合适（代码中要求的格式和文档例子格式一致）

**Comment by PaddyMelody** [comment]
@chaozwn @FlechazoW 
看来有必要修改或者回滚一下这个pr #827 
多表还原场景下的数据还原功能现在不可用了

**Comment by EngonVHKxZ** [comment]
```
{
  "job": {
    "content": [
      {
        "writer": {
          "parameter": {
          	# 当写入模式为insert的时候   
            "writeMode": "insert"
          }
        }
      }
    ]
  }
}

```

```java
package com.dtstack.chunjun.connector.jdbc.sink;

...

public class JdbcOutputFormat extends BaseRichOutputFormat {

    @Override
    protected void openInternal(int taskNumber, int numTasks) {
        try {
            dbConn = getConnection();
            // 默认关闭事务自动提交，手动控制事务
            if (Semantic.EXACTLY_ONCE == semantic) {
                autoCommit = false;
                dbConn.setAutoCommit(autoCommit);
            }
            initColumnList();
            ########################################################
            # 这里会读取到 writeMode 参数 
            # 当writeMode=insert的时候不会执行jdbcConf.setUniqueKey(tableIndex);语句
            # 同样会导致上面提到的jdbcConf.getUniqueKey().toArray(new String[0])抛出空指针的问题
            ########################################################
            if (!EWriteMode.INSERT.name().equalsIgnoreCase(jdbcConf.getMode())) {
                List<String> updateKey = jdbcConf.getUniqueKey();
                if (CollectionUtils.isEmpty(updateKey)) {
                    List<String> tableIndex =
                            JdbcUtil.getTableIndex(
                                    jdbcConf.getSchema(), jdbcConf.getTable(), dbConn);
                    jdbcConf.setUniqueKey(tableIndex);
                    LOG.info("updateKey = {}", JsonUtil.toJson(tableIndex));
                }
            }

            buildStmtProxy();
            LOG.info("subTask[{}}] wait finished", taskNumber);
        } catch (SQLException sqe) {
            throw new IllegalArgumentException("open() failed.", sqe);
        } finally {
            JdbcUtil.commit(dbConn);
        }
    }
}

```

**Comment by chaozwn** [comment]
@EngonVHKxZ hi,我提交了一份代码，你可以打包测试下，你的问题应该解决了

**Comment by chaozwn** [comment]
> > Is the problem solved, if not, let me help.
> 
> 你好 这边遇到的问题还没有解决 请问你是Oraclewriter这边相关代码的贡献者吗？



> > Is the problem solved, if not, let me help.
> 
> 你好 这边遇到的问题还没有解决 请问你是Oraclewriter这边相关代码的贡献者吗？

请参考下这个pr，https://github.com/DTStack/chunjun/pull/958

**Comment by chaozwn** [comment]
> @chaozwn 大佬 出现了新的问题 麻烦请先看看我的配置文件有没有问题
> 
> ## 配置文件
> ```json
> {
>   "job": {
>     "content": [
>       {
>         "reader": {
>           "parameter": {
>             "jdbcUrl": "jdbc:oracle:thin:@192.168.4.76:1522:helowin",
>             "username": "logminer_user",
>             "password": "lg_pwd",
>             "supportAutoAddLog": false,
>             "table": [ "LOGMINER_USER.ZJH_LG_FROM2", "LOGMINER_USER.ZJH_LG_FROM3" ],
>             "cat": "INSERT,UPDATE,DELETE",
>             "split": true,
>             "readPosition": "CURRENT",
>             "queryTimeout": 3000
>           },
>           "name": "oraclelogminerreader"
>         },
>         "writer": {
>           "parameter": {
>             "writeMode": "update",
>             "updateKey": [],
>             "allReplace": true,
>             "username": "logminer_user",
>             "password": "lg_pwd",
>             "connection": [{
>               "schema": "LOGMINER_USER",
>               "jdbcUrl": "jdbc:oracle:thin:@192.168.4.76:1523:helowin",
>               "table": [ "*" ]
>             }],
>             "column": []
>           },
>           "name": "oraclewriter"
>         },
>         "nameMapping": {
>           "schemaMappings": {
>             "LOGMINER_USER": "LOGMINER_USER"
>           },
>           "tableMappings": {
>             "LOGMINER_USER": {
>               "ZJH_LG_FROM2": "ZJH_LG_TO2",
>               "ZJH_LG_FROM3": "ZJH_LG_TO3"
>             }
>           },
>           "fieldMappings": {
>             "LOGMINER_USER": {
>               "ZJH_LG_FROM2": {
>                 "ID": "TO2_ID",
>                 "NAME": "NAME"
>               },
>               "ZJH_LG_FROM3": {
>                 "ID": "TO3_ID",
>                 "AGE": "AGE"
>               }
>             }
>           }
>         }
>       }
>     ],
>     "setting": {
>       "speed": {
>         "bytes": 0,
>         "channel": 1
>       },
>       "errorLimit": {
>         "record": 1
>       },
>       "restore": {
>         "maxRowNumForCheckpoint": 0,
>         "isRestore": false,
>         "restoreColumnName": "",
>         "restoreColumnIndex": 0
>       },
>       "log": {
>         "isLogger": true,
>         "level": "debug",
>         "path": "",
>         "pattern": ""
>       }
>     }
>   }
> }
> ```
> 
> ## Writer的writeMode为"insert"
> ![1655347059(1)](https://user-images.githubusercontent.com/74673814/173979446-4ec4f34e-ddbf-403d-998d-f7bd75252168.png)
> 
> ## Writer的writeMode为"update"且parameter->connection->table为["*"]
> ![108@CA9I44XO%JA$2Y~N6PP](https://user-images.githubusercontent.com/74673814/174063382-3831401b-8663-44ac-b7b9-4cfae97cc690.png)

wechat私聊下

**Comment by chaozwn** [comment]
> wxid_nbv6af03966p22

我改完了，简单测试了下，应该没问题了

**Comment by FlechazoW** [comment]
不要在issue 里暴露自己的私人联系方式。谢谢
