### ISSUE TITLE
doris sink数据解析错误,订单号对应的状态字段解析成订单号了,另一条数据订单号解析成状态值

### ISSUE THREAD

**Issue by Xff686542** [DTStack/chunjun#949]
![image](https://user-images.githubusercontent.com/49389493/173815489-2cc08632-4030-41b0-8dfd-26fb433e67c3.png)

**Comment by FlechazoW** [comment]
能否提供下任务执行脚本呢？

**Comment by Xff686542** [comment]
{
  "job" : {
    "content" : [ {
      "reader" : {
        "parameter" : {
          "username" : "fle_development",
          "password" : "xxx",
          "cat" : "insert,delete,update",
          "jdbcUrl" : "jdbc:mysql://192.168.0.229:3306/xxx?useSSL=false",
          "host" : "192.168.0.229",
          "port" : 3306,
          "start" : {
          },
          "table" : [ "fle_development.xxx" ],
          "splitUpdate" : true,
          "pavingData" : true,
          "column": [
            {
              "name": "pno",
              "type": "varchar"
            },
            {
              "name": "state",
              "type": "int"
            }
          ]
        },
        "table": {
          "tableName": "sourceTable"
        },
        "name" : "binlogreader"
      },
      "writer": {
        "parameter": {
          "batchSize": 10000,
          "maxRetries": 3,
          "feNodes": ["192.168.6.69:8030"],
          "column": [
            {
              "name": "pno",
              "type": "varchar"
            },
            {
              "name": "state",
              "type": "int"
            }
          ],
          "username": "root",
          "password": "xxx",
          "database": "test",
          "table": "xxx",
          "fieldDelimiter": "\t"
        },
        "name": "dorisbatchwriter"
      }
    } ],
    "setting" : {
      "speed" : {
        "bytes" : 0,
        "channel" : 1
      }
    }
  }
}

**Comment by FlechazoW** [comment]
This issue has been open too long for us to help, if you still have the same problem, please re-open an issue.
