### ISSUE TITLE
chunjun是否支持断点续传？

### ISSUE THREAD

**Issue by liumengkai** [DTStack/chunjun#982]
场景：
业务场景是使用binlog reader读取mysql binlog日志，发送到kafka

问题：
请问chunjun目前是否支持binlog reader的断点续传功能？是程序down掉之后重启需要手动set 文件名称和position吗？
如果支持的话如何配置呢？

我在配置文件讲解中没有找到相关的说明？

非常感谢

**Comment by libailin** [comment]
https://dtstack.github.io/chunjun-web/docs/chunjunDocs/restore

参考请配置文档

**Comment by liumengkai** [comment]
感谢！我会阅读 & 尝试 & 反馈的
