### ISSUE TITLE
mysql写入doris失败

### ISSUE THREAD

**Issue by wl3207601** [DTStack/chunjun#986]
**Describe the bug**
写入doris的json中batchSize配置无效，任务运行时显示该参数为1，当同步501条时任务失败，导入过频繁，doris合并不过来，任务失败

<img width="975" alt="image" src="https://user-images.githubusercontent.com/74947120/174960988-a706a096-3783-4f72-a11c-c264e03fc94d.png">
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/74947120/174961420-498dfa2d-bef8-4a78-a491-e86ff7aaaed6.png">

**Comment by wl3207601** [comment]
<img width="881" alt="image" src="https://user-images.githubusercontent.com/74947120/174961633-76f36dc6-0654-406e-9980-f64e40edc199.png">

**Comment by FlechazoW** [comment]
问题已修复。
